# generated by datamodel-codegen:
#   filename:  _shared/kpi_metric.schema.json
#   timestamp: 2026-05-27T21:00:44+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Source(StrEnum):
    """
    platform_verified = pulled directly from IG / TikTok / YouTube Insights API; brand_reported = brand provided the figure; third_party = Tribe Dynamics / HypeAuditor / similar; calculated = derived from other fields (e.g. CPM from fee/impressions); self_reported = talent's claim (lowest confidence); estimated = back-calculated when no source. Email generator + report renderer strongly prefer platform_verified > brand_reported > third_party when citing metrics.
    """

    PLATFORM_VERIFIED = "platform_verified"
    BRAND_REPORTED = "brand_reported"
    THIRD_PARTY = "third_party"
    CALCULATED = "calculated"
    SELF_REPORTED = "self_reported"
    ESTIMATED = "estimated"


class KpiMetric(BaseModel):
    """
    Canonical shared definition for KPI metrics across the system. Each metric carries its value AND its provenance (source enum, optional source_name, as_of date, optional verified_at timestamp). Referenced via $ref by `brand_deal.schema.json` ($defs.kpiMetric) and `performance_report_pack.schema.json` ($defs.kpiMetric), and indirectly by `deal.schema.json` (via deal.close.final_kpis which carries the report's kpis verbatim). On agent send of a performance report, kpis values write into `deal.close.final_kpis` and ultimately into `brand_deal.kpis` on auto-archive — the SAME shape carries through that loop.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    value: float = Field(
        ...,
        description="The metric value. For rates (engagement_rate_pct, ctr_pct), this is a percentage 0-100.",
        ge=0.0,
    )
    source: Source = Field(
        ...,
        description="platform_verified = pulled directly from IG / TikTok / YouTube Insights API; brand_reported = brand provided the figure; third_party = Tribe Dynamics / HypeAuditor / similar; calculated = derived from other fields (e.g. CPM from fee/impressions); self_reported = talent's claim (lowest confidence); estimated = back-calculated when no source. Email generator + report renderer strongly prefer platform_verified > brand_reported > third_party when citing metrics.",
    )
    source_name: str | None = Field(
        None,
        description="Specific source identifier (e.g. 'Instagram Insights API', 'Tribe Dynamics Q4 2025 report').",
    )
    as_of: date_aliased | None = Field(
        None,
        description="When this figure was captured. KPIs continue to grow after campaign end (e.g. viral pickup); the as_of date tells us when the snapshot was taken.",
    )
    verified_at: AwareDatetime | None = None
