# generated by datamodel-codegen:
#   filename:  agency_profile.schema.json
#   timestamp: 2026-05-27T14:03:33+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    RootModel,
)


class Branding(BaseModel):
    """
    Visual brand identity captured at agency-setup time (Phase 0 Step 1.5). Used by downstream artefact generators — discovery-call prep decks (Phase 4.5), proposal decks (Phase 4 PROPOSAL), case-study leave-behinds, and any other agency-branded output. Single source of truth: every generated document picks up these values, so a rebrand in this block propagates everywhere on next render.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    logo_url: AnyUrl | None = Field(
        None,
        description="Primary logo. Web-accessible URL or local path. Used in HTML signatures + on cover slides + footers. Recommend 500-1000px wide PNG with transparent background.",
    )
    logo_dark_url: AnyUrl | None = Field(
        None,
        description="Optional. Logo variant for dark backgrounds. If absent, the renderer falls back to logo_url.",
    )
    primary_color: str | None = Field(
        None,
        description="Hex color for primary brand surfaces — slide titles, headings, accent shapes. Format `#RRGGBB`.",
        pattern="^#[0-9A-Fa-f]{6}$",
    )
    secondary_color: str | None = Field(
        None,
        description="Hex color for secondary surfaces — subtitles, dividers, secondary buttons.",
        pattern="^#[0-9A-Fa-f]{6}$",
    )
    accent_color: str | None = Field(
        None,
        description="Optional accent for callouts, highlighted KPI numbers, etc.",
        pattern="^#[0-9A-Fa-f]{6}$",
    )
    background_color: str | None = Field(
        "#FFFFFF",
        description="Default slide background. Most decks stay white but agencies with darker brand identities may override.",
        pattern="^#[0-9A-Fa-f]{6}$",
    )
    text_color: str | None = Field(
        "#1A1A1A",
        description="Default body text color. Must have sufficient contrast against background_color.",
        pattern="^#[0-9A-Fa-f]{6}$",
    )
    font_family_heading: str | None = Field(
        None,
        description='CSS font-family stack for headings (e.g. `"Inter", sans-serif`). Renderer must ensure the font is web-loadable or fall back to safe defaults.',
    )
    font_family_body: str | None = Field(
        None, description="CSS font-family stack for body text."
    )
    google_fonts: list[str] | None = Field(
        None,
        description='Optional list of Google Font family names to load (e.g. ["Inter", "Playfair Display"]). Renderer injects the corresponding <link> tags.',
    )
    tagline: str | None = Field(
        None,
        description="Short positioning line used on title slides + signature footers (e.g. `Talent representation that works.`).",
    )
    deck_template_id: str | None = Field(
        "default",
        description="Identifier for the deck visual template the renderer should use. v0.1: `default`. v2: agencies can register custom templates and select per-context (e.g. `editorial`, `bold`, `minimal`).",
    )


class DefaultVoiceMode(StrEnum):
    """
    How the LLM positions agent vs talent in generated emails. v0.1 default per user decision: agent-led on-behalf-of. v2 may add per-talent overrides.
    """

    AGENT_LED_ON_BEHALF_OF_TALENT = "agent_led_on_behalf_of_talent"
    TALENT_LED_VIA_AGENCY = "talent_led_via_agency"
    AGENCY_LED_TALENT_FEATURED = "agency_led_talent_featured"


class DefaultCommissionModel(StrEnum):
    """
    Agency-default money-flow model. agency_invoices_brand_pays_talent_net (most common): agency is the FROM party on brand-facing invoices; agency receives payment; agency settles talent net of commission. talent_invoices_brand_agency_invoices_talent: talent is FROM party; agency auto-generates a separate commission invoice to talent. talent_invoices_brand_talent_pays_agency: talent FROM party + talent manually settles agency. Per-talent override via `talent.commission_override.commission_model`.
    """

    AGENCY_INVOICES_BRAND_PAYS_TALENT_NET = "agency_invoices_brand_pays_talent_net"
    TALENT_INVOICES_BRAND_AGENCY_INVOICES_TALENT = (
        "talent_invoices_brand_agency_invoices_talent"
    )
    TALENT_INVOICES_BRAND_TALENT_PAYS_AGENCY = (
        "talent_invoices_brand_talent_pays_agency"
    )


class DueDateCalculation(StrEnum):
    CALENDAR_DAYS = "calendar_days"
    BUSINESS_DAYS = "business_days"


class TaxHandling(StrEnum):
    """
    none: no tax line. vat_inclusive: total already includes VAT (rendered as 'inclusive of VAT'). vat_added: subtotal + tax_amount = total (UK/EU pattern). sales_tax: same math as vat_added with sales tax labelling (US pattern).
    """

    NONE = "none"
    VAT_INCLUSIVE = "vat_inclusive"
    VAT_ADDED = "vat_added"
    SALES_TAX = "sales_tax"


class InvoiceTemplate(BaseModel):
    """
    Agency-wide invoice template used by the Phase 4.8 invoice pack generator (`docs/invoice_workflow.md`). Captured in Phase 0 agency setup. One template for all talent + deals; talent-specific billing entity is pulled from `talent.billing_entity` at generation time. Invoices are highly deterministic so this template is mostly merge fields + a payment-instructions block — far fewer placeholders than the per-talent contract template.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    markdown_source: str | None = Field(
        None,
        description="Invoice template body in markdown. Supports `{{merge_field}}` substitution. Optional `{{narrative_line_items}}` placeholder enables LLM-drafted per-line-item descriptions; absent = literal deliverable descriptions used. Renders to PDF via Puppeteer/pandoc.",
    )
    invoice_number_prefix: str | None = Field(
        "INV-",
        description="String prefix on every invoice number. e.g. 'INV-' produces INV-2026-0001.",
    )
    invoice_number_format: str | None = Field(
        "{prefix}{YYYY}-{seq:04d}",
        description="Format string for invoice numbers. Tokens: `{prefix}`, `{YYYY}`, `{YY}`, `{MM}`, `{seq:0Nd}` (zero-padded sequence). Default produces INV-2026-0042 style.",
    )
    invoice_number_sequence: int | None = Field(
        1,
        description="Auto-incrementing per-agency sequence counter. Persisted on the agency_profile — generator reads + increments atomically on each new invoice. Per-agency (not per-talent or per-deal) so numbering is contiguous across the whole agency.",
        ge=1,
    )
    default_payment_terms_days: int | None = Field(
        30,
        description="Default days from sent_at to due_at. Per-invoice can override (e.g. NET-15, NET-45 deals).",
        ge=0,
    )
    due_date_calculation: DueDateCalculation | None = "calendar_days"
    tax_handling: TaxHandling | None = Field(
        "none",
        description="none: no tax line. vat_inclusive: total already includes VAT (rendered as 'inclusive of VAT'). vat_added: subtotal + tax_amount = total (UK/EU pattern). sales_tax: same math as vat_added with sales tax labelling (US pattern).",
    )
    default_tax_rate: float | None = Field(
        None,
        description="Decimal default tax rate (0.20 = 20%). Applied when tax_handling is vat_added / vat_inclusive / sales_tax. Per-invoice override available.",
        ge=0.0,
        le=1.0,
    )
    tax_label: str | None = Field(
        None,
        description="Label on the rendered tax line (e.g. 'VAT', 'Sales Tax', 'GST'). Derived from tax_handling but overridable for unusual cases.",
    )
    payment_instructions_markdown: str | None = Field(
        None,
        description="Block rendered into the invoice footer. Bank details / IBAN / SWIFT / Stripe payment link / PayPal address. Supports merge fields for per-invoice substitution (e.g. `{{invoice_number}}` as bank reference).",
    )
    invoice_footer: str | None = Field(
        None,
        description="Legal text appended to the invoice (e.g. 'Late payment subject to 8% statutory interest per the Late Payment of Commercial Debts (Interest) Act 1998.'). Optional.",
    )
    template_version: str | None = Field(
        None,
        description="Updated whenever markdown_source / invoice_number_sequence settings / tax_handling / invoice_footer change. Captured in `invoice_pack.context_snapshot.agency_invoice_template_version` for traceability. ENFORCEMENT (GAP-07): API layer MUST bump this string + set template_updated_at on every modification to those fields. Version bump is a DB-enforced trigger or a service-layer guard — never trust manual update. Format suggestion: semver (e.g. '1.0.0' → '1.0.1' for footer tweak, '1.1.0' for new tax handling, '2.0.0' for major rewrite).",
    )
    template_updated_at: AwareDatetime | None = None


class RepresentsTalentId(RootModel[str]):
    root: str = Field(..., pattern="^[a-z0-9][a-z0-9-]*$")


class Agent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    agent_id: str = Field(
        ...,
        description="Stable slug identifier for the agent.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    name: str = Field(
        ..., description="Agent's full name as it appears in the FROM line + signature."
    )
    email: EmailStr = Field(
        ...,
        description="Agent's primary inbox. Replies route here. May or may not equal the sending mailbox (agencies sometimes send from `sarah@` and receive at `partnerships@`).",
    )
    phone: str | None = Field(
        None, description="E.164 preferred; appears in signature."
    )
    title: str | None = Field(
        None,
        description="Job title for the signature (e.g. 'Director of Brand Partnerships').",
    )
    linkedin_url: AnyUrl | None = None
    is_primary: bool = Field(
        ...,
        description="True for the agent who acts as the default sender when an explicit per-talent agent isn't assigned. v0.1: must be true (only one agent). v2: exactly one agent must be primary.",
    )
    represents_talent_ids: list[RepresentsTalentId] | None = Field(
        None,
        description="v0.1: agent represents all talents (this array may be empty as a 'represents everyone' signal, or contain all talent_ids). v2: explicit assignment enables agent-to-talent routing — each talent's outreach uses their assigned agent's mailbox + signature.",
    )


class Purpose(StrEnum):
    """
    named_agent_outreach: `sarah@agency.com` style, brand sees the agent's name on the FROM line — v0.1 default per user decision. generic_agency_outreach: `partnerships@agency.com` — used in v2 as fallback. transactional: agency's reply-handling inbox, not for outbound.
    """

    NAMED_AGENT_OUTREACH = "named_agent_outreach"
    GENERIC_AGENCY_OUTREACH = "generic_agency_outreach"
    TRANSACTIONAL = "transactional"


class WarmupStatus(StrEnum):
    """
    Lifecycle: pending = DNS not yet verified; in_progress = Smartlead warmup running (typically 2-4 weeks); complete = ready for cold outreach; paused = manually held.
    """

    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETE = "complete"
    PAUSED = "paused"


class SendingMailbox(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: EmailStr = Field(
        ...,
        description="The address emails are sent FROM. Must be on the agency's domain.",
    )
    agent_id: str = Field(
        ...,
        description="FK to `agents[].agent_id`. The agent this mailbox represents.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    purpose: Purpose = Field(
        ...,
        description="named_agent_outreach: `sarah@agency.com` style, brand sees the agent's name on the FROM line — v0.1 default per user decision. generic_agency_outreach: `partnerships@agency.com` — used in v2 as fallback. transactional: agency's reply-handling inbox, not for outbound.",
    )
    warmup_status: WarmupStatus = Field(
        ...,
        description="Lifecycle: pending = DNS not yet verified; in_progress = Smartlead warmup running (typically 2-4 weeks); complete = ready for cold outreach; paused = manually held.",
    )
    started_warmup_at: AwareDatetime | None = None
    completed_warmup_at: AwareDatetime | None = None
    dns_records_verified: bool | None = Field(
        None,
        description="True when SPF + DKIM + DMARC records are all confirmed for the agency's domain. Gating condition before warmup can start.",
    )
    smartlead_mailbox_id: str | None = Field(
        None,
        description="Identifier in Smartlead's mailbox registry. Set after Smartlead onboards the mailbox.",
    )
    daily_send_cap: int | None = Field(
        None,
        description="Maximum cold emails this mailbox sends per day. Ramps up during warmup; typically caps at 100-200/day for sustainable deliverability.",
        ge=10,
        le=500,
    )


class BillingEntity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    legal_name: str | None = None
    country: str | None = Field(None, pattern="^[A-Z]{2}$")
    tax_id: str | None = None


class AgencyProfile(BaseModel):
    """
    Single source of truth for the agency operating the system. Captures the agency identity, the named agent(s) who send outreach, the sending mailbox(es) + warmup state, and the signature template baked into every email. v0.1 = single agency, single agent (`agents` and `sending_mailboxes` arrays both length 1). v2 will lift the single-agent constraint to multi-agent (e.g. Sarah handles 5 talents, Tom handles 3) without breaking the v0.1 shape — the array structure is already in place. Lives at `data/agency_profile.json` (gitignored — contains real agent contact details).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: str | None = Field(None, alias="$schema")
    agency_id: str = Field(
        ...,
        description="Stable slug identifier for the agency. Used as the root identifier when v2 introduces multi-agency.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    name: str = Field(
        ...,
        description="Display name of the agency, used in email signatures + intros.",
    )
    domain: str = Field(
        ...,
        description="The agency's primary domain (e.g. `nativeagency.com`). All sending mailboxes are subdomains/addresses of this domain. SPF/DKIM/DMARC records live here.",
    )
    website_url: AnyUrl | None = None
    branding: Branding | None = Field(
        None,
        description="Visual brand identity captured at agency-setup time (Phase 0 Step 1.5). Used by downstream artefact generators — discovery-call prep decks (Phase 4.5), proposal decks (Phase 4 PROPOSAL), case-study leave-behinds, and any other agency-branded output. Single source of truth: every generated document picks up these values, so a rebrand in this block propagates everywhere on next render.",
    )
    agents: list[Agent] = Field(
        ...,
        description="v0.1: exactly one agent (constraint enforced via maxItems: 1). v2: maxItems lifted; multi-agent rosters supported with per-agent talent assignment.",
        max_length=1,
        min_length=1,
    )
    sending_mailboxes: list[SendingMailbox] = Field(
        ...,
        description="Mailboxes the agency sends outreach from. v0.1 typically = 1 (the primary agent's mailbox). Each mailbox is independently warmed up in Smartlead.",
        min_length=1,
    )
    company_address: str = Field(
        ...,
        description="Physical mailing address. REQUIRED for CAN-SPAM compliance — every cold email must include the sender's physical address in the footer. Composed into the email signature.",
    )
    unsubscribe_email: EmailStr | None = Field(
        None,
        description="Address that handles List-Unsubscribe responses. Typically `unsubscribe@{domain}` or a dedicated inbox. Drives the one-click unsubscribe required by Gmail/Yahoo Feb 2024 rules.",
    )
    default_signature_template: str = Field(
        ...,
        description="Email signature block. Supports merge fields: `{agent_name}`, `{agent_title}`, `{agent_email}`, `{agent_phone}`, `{agency_name}`, `{agency_website}`, `{agency_address}`, `{unsubscribe_link}`. Required to end every outreach email; the orchestrator validates presence at send-time.",
    )
    default_voice_mode: DefaultVoiceMode | None = Field(
        "agent_led_on_behalf_of_talent",
        description="How the LLM positions agent vs talent in generated emails. v0.1 default per user decision: agent-led on-behalf-of. v2 may add per-talent overrides.",
    )
    billing_entity: BillingEntity | None = Field(
        None,
        description="The agency's OWN legal entity. Used for outreach signature CAN-SPAM compliance (physical address requirement) + as a fallback FROM party on invoices when `commission_model = agency_invoices_brand_pays_talent_net`. Distinguished from `talent.billing_entity` which is the talent's legal entity. Different concept — agency may or may not be the invoicing party depending on the commission model.",
    )
    default_commission_rate: float | None = Field(
        0.2,
        description="Agency-default commission rate as decimal (0.20 = 20%). Applied to every talent unless overridden via `talent.commission_override.commission_rate`. Powers Phase 4.8 invoice flow — when `commission_model = agency_invoices_brand_pays_talent_net`, agency invoices brand for full fee; talent settlement = fee × (1 - commission_rate).",
        ge=0.0,
        le=1.0,
    )
    default_commission_model: DefaultCommissionModel | None = Field(
        "agency_invoices_brand_pays_talent_net",
        description="Agency-default money-flow model. agency_invoices_brand_pays_talent_net (most common): agency is the FROM party on brand-facing invoices; agency receives payment; agency settles talent net of commission. talent_invoices_brand_agency_invoices_talent: talent is FROM party; agency auto-generates a separate commission invoice to talent. talent_invoices_brand_talent_pays_agency: talent FROM party + talent manually settles agency. Per-talent override via `talent.commission_override.commission_model`.",
    )
    invoice_template: InvoiceTemplate | None = Field(
        None,
        description="Agency-wide invoice template used by the Phase 4.8 invoice pack generator (`docs/invoice_workflow.md`). Captured in Phase 0 agency setup. One template for all talent + deals; talent-specific billing entity is pulled from `talent.billing_entity` at generation time. Invoices are highly deterministic so this template is mostly merge fields + a payment-instructions block — far fewer placeholders than the per-talent contract template.",
    )
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
