# generated by datamodel-codegen:
#   filename:  brand_contact.schema.json
#   timestamp: 2026-05-27T14:03:33+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    RootModel,
)


class Name(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    full: str = Field(
        ...,
        description="Display name as commonly used (e.g. 'Jane Doe' or 'Unknown — Influencer Marketing Manager' for placeholders).",
    )
    first: str | None = None
    last: str | None = None
    preferred: str | None = Field(
        None,
        description="Preferred name to use in outreach (e.g. 'Jay' if their LinkedIn shows 'Jay Doe' but their formal name is 'Jane').",
    )


class Function(StrEnum):
    """
    Functional area. `influencer_marketing` and `brand_partnerships` are the headline targets for creator-deal outreach.
    """

    INFLUENCER_MARKETING = "influencer_marketing"
    BRAND_PARTNERSHIPS = "brand_partnerships"
    MARKETING = "marketing"
    BRAND_MANAGEMENT = "brand_management"
    SOCIAL_MEDIA = "social_media"
    PR_COMMS = "pr_comms"
    CREATIVE = "creative"
    DIGITAL = "digital"
    ECOMMERCE = "ecommerce"
    GROWTH = "growth"
    COMMUNITY = "community"
    EVENTS = "events"
    SALES = "sales"
    FOUNDER_CEO = "founder_ceo"
    AGENCY_OF_RECORD = "agency_of_record"
    OTHER = "other"


class Seniority(StrEnum):
    """
    Hierarchical level. Combined with brand size, drives the `decision_role` classification.
    """

    FOUNDER = "founder"
    C_SUITE = "c_suite"
    SVP = "svp"
    VP = "vp"
    SENIOR_DIRECTOR = "senior_director"
    DIRECTOR = "director"
    SENIOR_MANAGER = "senior_manager"
    MANAGER = "manager"
    IC = "ic"
    INTERN = "intern"
    UNKNOWN = "unknown"


class DecisionRole(StrEnum):
    """
    Likely role this person plays in a creator-deal decision. Simplified 5-value taxonomy: `buyer` = can say yes and holds the budget for this deal size; `influencer` = has input but no authority (CMOs at megabrands, senior brand managers, end-users who'd run the campaign); `gatekeeper` = controls access to the buyer (EAs, agency-of-record account managers); `champion` = internal advocate / known fan; `unknown` = default until classified. Note: a CMO of a multibillion brand is typically `influencer`, NOT `buyer` — creator-deal sign-off happens at the IM Manager level 2 levels down.
    """

    BUYER = "buyer"
    INFLUENCER = "influencer"
    GATEKEEPER = "gatekeeper"
    CHAMPION = "champion"
    UNKNOWN = "unknown"


class DecisionAuthoritySizeBand(StrEnum):
    """
    Estimated deal-size band this person can sign off on without further escalation. `micro` = <$5k, `low` = $5k–$25k, `medium` = $25k–$100k, `high` = $100k–$500k, `enterprise` = $500k+. Inferred from seniority + brand size.
    """

    MICRO = "micro"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    ENTERPRISE = "enterprise"
    UNKNOWN = "unknown"


class Location(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    city: str | None = None
    country: str | None = Field(
        None, description="ISO 3166-1 alpha-2.", pattern="^[A-Z]{2}$"
    )
    timezone: str | None = Field(
        None, description="IANA timezone string (e.g. 'America/Los_Angeles')."
    )


class VerificationStatus(StrEnum):
    """
    verified = vendor SMTP-checked and got a response; catchall = domain accepts everything (can't confirm); guessed_pattern = built from a known pattern (firstname.lastname@brand.com) but not verified; unverified = source provided but no check run; bounced = previous send returned hard bounce.
    """

    VERIFIED = "verified"
    CATCHALL = "catchall"
    GUESSED_PATTERN = "guessed_pattern"
    UNVERIFIED = "unverified"
    BOUNCED = "bounced"


class Source(StrEnum):
    """
    Vendor or method that supplied this email.
    """

    APOLLO = "apollo"
    HUNTER = "hunter"
    ROCKETREACH = "rocketreach"
    CLAY = "clay"
    LINKEDIN_API = "linkedin_api"
    WEB_SEARCH = "web_search"
    MANUAL_ENTRY = "manual_entry"
    PATTERN_INFERRED = "pattern_inferred"


class Email(BaseModel):
    """
    Primary email. Honesty policy applies — never fabricate; use verification status to communicate confidence.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    address: EmailStr | None = None
    verification_status: VerificationStatus | None = Field(
        None,
        description="verified = vendor SMTP-checked and got a response; catchall = domain accepts everything (can't confirm); guessed_pattern = built from a known pattern (firstname.lastname@brand.com) but not verified; unverified = source provided but no check run; bounced = previous send returned hard bounce.",
    )
    source: Source | None = Field(
        None, description="Vendor or method that supplied this email."
    )
    verified_at: AwareDatetime | None = None


class VerificationStatus1(StrEnum):
    VERIFIED = "verified"
    CATCHALL = "catchall"
    GUESSED_PATTERN = "guessed_pattern"
    UNVERIFIED = "unverified"
    BOUNCED = "bounced"


class AlternateEmail(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    address: EmailStr
    source: str | None = None
    verification_status: VerificationStatus1 | None = None


class Phone(BaseModel):
    """
    Phone numbers are rare for brand-side marketing contacts and should generally not be used for first outreach. Captured when available for high-value warm contacts only.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    number: str | None = Field(
        None, description="E.164 format preferred (e.g. '+1-503-555-0123')."
    )
    country_code: str | None = None
    source: str | None = None


class Linkedin(BaseModel):
    """
    LinkedIn is the primary identifier — emails change with job moves but LinkedIn URLs stick. Used as the merge key when two sources describe the same person.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    url: AnyUrl | None = Field(
        None, description="Full LinkedIn URL (e.g. 'https://linkedin.com/in/janedoe')."
    )
    handle: str | None = Field(
        None, description="Just the handle portion (e.g. 'janedoe')."
    )
    last_updated: AwareDatetime | None = Field(
        None, description="When LinkedIn API last reported a change to this profile."
    )
    last_activity: AwareDatetime | None = Field(
        None,
        description="Last time this person posted/commented on LinkedIn — informs the `recent_linkedin_activity` qualification signal.",
    )


class SocialHandles(BaseModel):
    """
    Other public social presences where the contact engages. Only relevant ones — not exhaustive.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    twitter_x: str | None = Field(None, description="Handle without leading @.")
    instagram: str | None = None
    threads: str | None = None
    tiktok: str | None = None
    bluesky: str | None = None
    personal_website: AnyUrl | None = None


class Tenure(BaseModel):
    """
    Time-at-brand context. Influences trust and qualification (a contact 6 months into a role probably isn't yet making big spend decisions).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    started_at: str | None = Field(
        None, description="YYYY-MM format when they started this role at this brand."
    )
    previous_brand: str | None = Field(
        None,
        description="Free text — the brand they came from. Useful for warm-intro mapping ('your previous Talent X worked with them at Adidas').",
    )
    is_current: bool | None = Field(
        True,
        description="False if they've left the brand. Stale contacts kept on file for history but excluded from outreach lists.",
    )


class Tier(StrEnum):
    """
    qualified ≥ 0.60 — top-of-list; speculative 0.30–0.60 — worth a try; unqualified < 0.30 — hidden from default outreach lists (but still in file).
    """

    QUALIFIED = "qualified"
    SPECULATIVE = "speculative"
    UNQUALIFIED = "unqualified"


class ChampionForTalent(RootModel[str]):
    root: str = Field(..., pattern="^[a-z0-9][a-z0-9-]*$")


class Source4(StrEnum):
    APOLLO = "apollo"
    HUNTER = "hunter"
    ROCKETREACH = "rocketreach"
    CLAY = "clay"
    LINKEDIN_API = "linkedin_api"
    EXA_WEB_SEARCH = "exa_web_search"
    MANUAL_ENTRY = "manual_entry"
    BRAND_WEBSITE_SCRAPE = "brand_website_scrape"
    AI_INFERENCE = "ai_inference"


class VerificationSource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Source4
    source_id: str | None = Field(
        None,
        description="The vendor's internal ID for this record (e.g. Apollo person_id), so we can re-query.",
    )
    fetched_at: AwareDatetime
    fields_provided: list[str] | None = Field(
        None,
        description="Which fields this source contributed (e.g. ['name','title','email','linkedin.url']).",
    )


class Signal(StrEnum):
    """
    Identifier of the contact-qualification signal. Positives first, then negatives. `holds_buyer_role` fires when decision_role == 'buyer'.
    """

    HAS_VERIFIED_EMAIL = "has_verified_email"
    HOLDS_BUYER_ROLE = "holds_buyer_role"
    TENURE_AT_LEAST_1Y = "tenure_at_least_1y"
    RECENT_LINKEDIN_ACTIVITY = "recent_linkedin_activity"
    CHAMPION_FOR_OTHER_TALENTS = "champion_for_other_talents"
    WARM_INTRO_AVAILABLE = "warm_intro_available"
    MATCHES_BRAND_TYPICAL_TIER = "matches_brand_typical_tier"
    IN_TARGET_AUDIENCE_COUNTRY = "in_target_audience_country"
    LEFT_BRAND = "left_brand"
    PLACEHOLDER_ONLY = "placeholder_only"
    EMAIL_BOUNCED_RECENTLY = "email_bounced_recently"
    SENIOR_EXECUTIVE_AT_LARGE_BRAND = "senior_executive_at_large_brand"
    UNVERIFIED_EMAIL = "unverified_email"
    NO_LINKEDIN_URL = "no_linkedin_url"
    STALE_DATA = "stale_data"


class QualificationSignal(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    signal: Signal = Field(
        ...,
        description="Identifier of the contact-qualification signal. Positives first, then negatives. `holds_buyer_role` fires when decision_role == 'buyer'.",
    )
    weight: float = Field(
        ...,
        description="Contribution to qualification.score. Positive = stronger likelihood-to-respond; negative = weaker. Typical magnitudes 0.05–0.30.",
        ge=-1.0,
        le=1.0,
    )
    details: str | None = Field(
        None,
        description="Human-readable explanation. e.g. 'Verified email via Apollo SMTP check 2026-05-20' or 'Senior Director at $51B brand — likely decision-makers are 2 levels below'.",
    )


class Channel(StrEnum):
    EMAIL = "email"
    LINKEDIN_MESSAGE = "linkedin_message"
    LINKEDIN_INMAIL = "linkedin_inmail"
    LINKEDIN_CONNECTION = "linkedin_connection"
    EMAIL_VIA_AOR = "email_via_aor"
    TWITTER_DM = "twitter_dm"
    INSTAGRAM_DM = "instagram_dm"
    IN_PERSON = "in_person"
    OTHER = "other"


class Outcome(StrEnum):
    """
    Narrowed high-level outcome for UI rendering — derived from the canonical `pitch_enrollment.outcomeClassification.outcome` (interested → replied_interested; declined → replied_declined; out_of_office / unrelated / needs_more_info / wrong_person_routed → replied_other; unsubscribe_request → unsubscribed). `in_flight` = enrollment.state in [drafted, awaiting_approval, active, paused] without a final outcome. The orchestrator syncs this field on enrollment state transitions; canonical source is the enrollment record.
    """

    IN_FLIGHT = "in_flight"
    NO_RESPONSE = "no_response"
    REPLIED_INTERESTED = "replied_interested"
    REPLIED_DECLINED = "replied_declined"
    REPLIED_OTHER = "replied_other"
    BOUNCED = "bounced"
    UNSUBSCRIBED = "unsubscribed"


class PitchHistoryEntry(BaseModel):
    """
    Denormalised per-(contact, talent) pitch summary for fast contact-record reads. The CANONICAL pitch record lives in `data/pitch_enrollments/{enrollment_id}.json` (`schemas/pitch_enrollment.schema.json`) — this entry is a summary index pointing back via `enrollment_id`. `outcome` enum here is intentionally narrow (high-level state for UI rendering); the rich classification + extracted_signals live on the enrollment's `outcomeClassification` block. Stays preserved across enrichment runs.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    talent_id: str = Field(
        ...,
        description="ID of the talent on whose behalf this pitch was sent. Links to `talents/{talent_id}.json`.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    pitched_at: AwareDatetime
    channel: Channel
    enrollment_id: str | None = Field(
        None,
        description="FK to the canonical pitch enrollment record (`data/pitch_enrollments/{enrollment_id}.json`). Anyone needing detailed pitch state — per-step engagement, classified outcome with extracted_signals, generated content — reads from there. This block is a summary index for fast contact-record scans.",
        pattern="^enr_[a-z0-9]+$",
    )
    template_id: str | None = Field(
        None,
        description="FK to a pitch template (`schemas/pitch_template.schema.json` — shipped in Phase 3b).",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    subject: str | None = Field(
        None,
        description="Subject line for email pitches; first-message preview for DM pitches.",
    )
    outcome: Outcome | None = Field(
        None,
        description="Narrowed high-level outcome for UI rendering — derived from the canonical `pitch_enrollment.outcomeClassification.outcome` (interested → replied_interested; declined → replied_declined; out_of_office / unrelated / needs_more_info / wrong_person_routed → replied_other; unsubscribe_request → unsubscribed). `in_flight` = enrollment.state in [drafted, awaiting_approval, active, paused] without a final outcome. The orchestrator syncs this field on enrollment state transitions; canonical source is the enrollment record.",
    )
    outcome_at: AwareDatetime | None = None
    next_followup_at: AwareDatetime | None = None
    notes: str | None = None
    linked_brand_candidate_run_id: str | None = Field(
        None,
        description="The discovery `search_run_id` (from `brand_candidates.schema.json`) that surfaced this brand and triggered the pitch. Useful for tracking which discovery run produced which conversions.",
    )


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    step: str
    error: str
    fatal: bool | None = None


class EnrichmentMeta(BaseModel):
    """
    Orchestrator telemetry for the most recent enrichment run that touched this file. Useful for monitoring job health and vendor-quota consumption.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    search_durations_ms: dict[str, int] | None = Field(
        None, description="Per-step wall-clock duration in milliseconds."
    )
    errors: list[Error] | None = None
    vendor_usage: dict[str, Any] | None = Field(
        None, description="Per-vendor usage and remaining quota."
    )
    target_roles_searched: list[str] | None = Field(
        None,
        description="Role titles that the orchestrator looked for on this run. Each unique title becomes a placeholder if no person was found.",
    )


class Qualification(BaseModel):
    """
    Likelihood this contact converts on a creator-deal pitch. Ranks contacts *within* a brand (different from brand-level qualification in `brand_candidates.schema.json`).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    score: float = Field(..., ge=0.0, le=1.0)
    tier: Tier = Field(
        ...,
        description="qualified ≥ 0.60 — top-of-list; speculative 0.30–0.60 — worth a try; unqualified < 0.30 — hidden from default outreach lists (but still in file).",
    )
    signals: list[QualificationSignal]
    threshold_applied: float | None = Field(None, ge=0.0, le=1.0)


class Contact(BaseModel):
    """
    One contact at one brand. Workflow-state fields (`pitch_history`, `tags`, `notes`, `do_not_contact`, `opt_out_at`) are PRESERVED across enrichment runs — the orchestrator must not overwrite them when refreshing the discovery-output fields.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contact_id: str = Field(
        ...,
        description="Stable slug derived from brand_id + name + role. Format suggestion: `{brand_id}-{name-slug}-{role-slug}` (e.g. `nike-jane-doe-vp-marketing`). Used as the merge key across enrichment runs.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    brand_id: str = Field(
        ...,
        description="Kebab-case slug matching a `name` (normalised) in `data/brand_industry_map.json`.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    is_placeholder: bool = Field(
        ...,
        description="True when the role exists (e.g. 'Nike has an Influencer Marketing Manager') but the person's name isn't yet known. Placeholders surface gaps in the contact coverage so they can be filled later. When true, `name.full` may be a role-derived stub (e.g. 'Unknown — Influencer Marketing Manager').",
    )
    name: Name
    title: str | None = Field(
        None,
        description="Job title verbatim from source. May vary across sources; use Apollo's canonical title when available.",
    )
    function: Function | None = Field(
        None,
        description="Functional area. `influencer_marketing` and `brand_partnerships` are the headline targets for creator-deal outreach.",
    )
    seniority: Seniority | None = Field(
        None,
        description="Hierarchical level. Combined with brand size, drives the `decision_role` classification.",
    )
    decision_role: DecisionRole = Field(
        ...,
        description="Likely role this person plays in a creator-deal decision. Simplified 5-value taxonomy: `buyer` = can say yes and holds the budget for this deal size; `influencer` = has input but no authority (CMOs at megabrands, senior brand managers, end-users who'd run the campaign); `gatekeeper` = controls access to the buyer (EAs, agency-of-record account managers); `champion` = internal advocate / known fan; `unknown` = default until classified. Note: a CMO of a multibillion brand is typically `influencer`, NOT `buyer` — creator-deal sign-off happens at the IM Manager level 2 levels down.",
    )
    decision_role_rationale: str | None = Field(
        None,
        description="LLM-generated one-line explanation of why this `decision_role` was assigned. e.g. 'VP Marketing at Nike ($51B revenue) — too senior to approve individual £5k Reel deals; useful for warm intros to the IM Manager 2 levels down (who is the actual buyer).'",
    )
    decision_authority_size_band: DecisionAuthoritySizeBand | None = Field(
        None,
        description="Estimated deal-size band this person can sign off on without further escalation. `micro` = <$5k, `low` = $5k–$25k, `medium` = $25k–$100k, `high` = $100k–$500k, `enterprise` = $500k+. Inferred from seniority + brand size.",
    )
    location: Location | None = None
    email: Email | None = Field(
        None,
        description="Primary email. Honesty policy applies — never fabricate; use verification status to communicate confidence.",
    )
    alternate_emails: list[AlternateEmail] | None = Field(
        None,
        description="Other email addresses observed for this person (e.g. personal email leaked in past breaches; alternate work address). Should be used cautiously and only with explicit user opt-in.",
    )
    phone: Phone | None = Field(
        None,
        description="Phone numbers are rare for brand-side marketing contacts and should generally not be used for first outreach. Captured when available for high-value warm contacts only.",
    )
    linkedin: Linkedin | None = Field(
        None,
        description="LinkedIn is the primary identifier — emails change with job moves but LinkedIn URLs stick. Used as the merge key when two sources describe the same person.",
    )
    social_handles: SocialHandles | None = Field(
        None,
        description="Other public social presences where the contact engages. Only relevant ones — not exhaustive.",
    )
    tenure: Tenure | None = Field(
        None,
        description="Time-at-brand context. Influences trust and qualification (a contact 6 months into a role probably isn't yet making big spend decisions).",
    )
    qualification: Qualification | None = Field(
        None,
        description="Likelihood this contact converts on a creator-deal pitch. Ranks contacts *within* a brand (different from brand-level qualification in `brand_candidates.schema.json`).",
    )
    qualification_filtered: bool | None = Field(
        False,
        description="True if qualification.score is below threshold. UI hides by default; user can override.",
    )
    tags: list[str] | None = Field(
        None,
        description="Free-form labels for the user's own organisation (e.g. 'primary_contact', 'warm_lead', 'event_met', 'agency_relationship').",
    )
    notes: str | None = Field(
        None, description="User-authored annotations. Preserved across enrichment runs."
    )
    champion_for_talents: list[ChampionForTalent] | None = Field(
        None,
        description="Talent IDs this contact has advocated for in the past (known fan, prior successful campaign, warm relationship). Major positive signal for re-outreach.",
    )
    pitch_history: list[PitchHistoryEntry] | None = Field(
        None,
        description="Per-talent log of outreach attempts to this specific person. Shared roster contact pool, per-talent history — so we know not to double-pitch the same person across two talents in a short window. PRESERVED across enrichment runs.",
    )
    do_not_contact: bool | None = Field(
        False,
        description="Hard flag. When true, this contact must be excluded from all outreach across all talents, indefinitely.",
    )
    do_not_contact_reason: str | None = Field(
        None,
        description="Free text: why this contact is flagged DNC. Common: 'explicit unsubscribe', 'asked to be removed', 'left brand', 'data inaccuracy reported'.",
    )
    opt_out_at: AwareDatetime | None = Field(
        None,
        description="When the contact unsubscribed or asked to be removed from outreach (CAN-SPAM honour-opt-out hygiene). Record is kept (so we don't accidentally re-enrich and re-pitch them later) but never included in outreach lists going forward.",
    )
    first_discovered_at: AwareDatetime
    last_verified_at: AwareDatetime = Field(
        ...,
        description="Most recent time the enrichment pipeline confirmed this contact still exists at this brand.",
    )
    verification_sources: list[VerificationSource] | None = Field(
        None,
        description="Each vendor/source that has provided data for this record, with the fields they provided and when.",
    )
    confidence: float | None = Field(
        None,
        description="Overall confidence in the record. Weighted average across populated fields' source confidences. Used as a tie-breaker when multiple records describe the same person.",
        ge=0.0,
        le=1.0,
    )


class BrandContactFile(BaseModel):
    """
    Per-brand contact records. One file per brand under `data/brand_contacts/{brand_id}.json`. The folder is gitignored — contacts contain PII (names, emails, phone numbers) and Apollo data is licensed. Schema in repo; data is generated. See `docs/contact_enrichment_workflow.md`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: str | None = Field(None, alias="$schema")
    agency_id: UUID | None = Field(
        None,
        description="Multi-tenant scope: FK to agency_profile.agency_id. Optional in v0.1 (single-tenant deploys may omit); required in v2 SaaS. When present, all cross-record queries MUST filter by agency_id to prevent cross-tenant data leakage. See docs/data_lineage.md GAP-01/02 for rationale.",
    )
    brand_id: str = Field(
        ...,
        description="Slug matching a `name` (normalised) in `data/brand_industry_map.json`. The merge key joining contacts to brand metadata.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    brand_name: str | None = Field(
        None,
        description="Denormalised display name for at-a-glance reading. Source of truth remains `brand_industry_map.json`.",
    )
    version: str = Field(
        ...,
        description="Schema version of this file. Bump when the contact shape changes.",
    )
    last_enriched_at: AwareDatetime = Field(
        ...,
        description="Most recent end-to-end enrichment-pipeline run that touched this file.",
    )
    enrichment_run_id: str | None = Field(
        None,
        description="Stable identifier for the run that produced this version. Correlates with orchestrator logs.",
    )
    contacts: list[Contact] = Field(
        ...,
        description="All known contacts at this brand. Includes placeholder entries (`is_placeholder: true`) for roles whose identity isn't yet known.",
    )
    enrichment_meta: EnrichmentMeta | None = None
