# generated by datamodel-codegen:
#   filename:  brand_deal.schema.json
#   timestamp: 2026-05-27T14:03:33+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel

from ._shared import kpi_metric_schema


class CampaignType(StrEnum):
    """
    Deal structure type. sponsored_post = single piece; sponsored_series = multi-post campaign; ambassador = long-term recurring; product_seeding = gifted product, no fee; affiliate = commission-based; ugc_license = brand licenses talent content; whitelisting = talent content used as brand paid social; paid_appearance = event/panel/host; brand_integration = paid mention in non-sponsored content; co_branded_product = co-creation.
    """

    SPONSORED_POST = "sponsored_post"
    SPONSORED_SERIES = "sponsored_series"
    AMBASSADOR = "ambassador"
    PRODUCT_SEEDING = "product_seeding"
    AFFILIATE = "affiliate"
    UGC_LICENSE = "ugc_license"
    WHITELISTING = "whitelisting"
    PAID_APPEARANCE = "paid_appearance"
    BRAND_INTEGRATION = "brand_integration"
    CO_BRANDED_PRODUCT = "co_branded_product"
    PODCAST_READ = "podcast_read"
    NEWSLETTER_MENTION = "newsletter_mention"
    OTHER = "other"


class CampaignObjective(StrEnum):
    """
    Brand's stated goal for the campaign. Drives which KPIs matter most for the post-campaign analysis.
    """

    AWARENESS = "awareness"
    CONSIDERATION = "consideration"
    CONVERSION = "conversion"
    BRAND_LIFT = "brand_lift"
    PRODUCT_LAUNCH = "product_launch"
    AUDIENCE_GROWTH = "audience_growth"
    RETENTION_LOYALTY = "retention_loyalty"
    CRISIS_RECOVERY = "crisis_recovery"
    OTHER = "other"


class Platform(StrEnum):
    INSTAGRAM = "instagram"
    TIKTOK = "tiktok"
    YOUTUBE = "youtube"
    TWITTER_X = "twitter_x"
    LINKEDIN = "linkedin"
    PINTEREST = "pinterest"
    TWITCH = "twitch"
    SNAPCHAT = "snapchat"
    FACEBOOK = "facebook"
    SUBSTACK = "substack"
    PODCAST = "podcast"
    OTHER = "other"


class Format(StrEnum):
    REEL = "reel"
    STORY = "story"
    FEED_POST = "feed_post"
    CAROUSEL = "carousel"
    LIVE = "live"
    VIDEO_LONG_FORM = "video_long_form"
    VIDEO_SHORT = "video_short"
    PODCAST_EPISODE = "podcast_episode"
    PODCAST_READ = "podcast_read"
    NEWSLETTER = "newsletter"
    TWEET_THREAD = "tweet_thread"
    LINKEDIN_POST = "linkedin_post"
    APPEARANCE = "appearance"
    CO_CREATED_PRODUCT = "co_created_product"
    OTHER = "other"


class Deliverable(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    platform: Platform
    format: Format
    count: int = Field(..., ge=1)
    post_urls: list[AnyUrl] | None = Field(
        None,
        description="Direct URLs to the published content. Useful for verification + showing the brand the work.",
    )


class UsageRightsGrantedEnum(StrEnum):
    ORGANIC = "organic"
    WHITELISTING_30D = "whitelisting_30d"
    WHITELISTING_60D = "whitelisting_60d"
    WHITELISTING_90D = "whitelisting_90d"
    WHITELISTING_UNLIMITED = "whitelisting_unlimited"
    PAID_SOCIAL_30D = "paid_social_30d"
    PAID_SOCIAL_90D = "paid_social_90d"
    PAID_SOCIAL_PERPETUAL = "paid_social_perpetual"
    WEBSITE_USE = "website_use"
    BROADCAST = "broadcast"
    PRINT = "print"
    PERPETUAL_ALL_CHANNELS = "perpetual_all_channels"


class Exclusivity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    category: str | None = Field(
        None, description="Industry / category the talent was exclusive in."
    )
    duration_days: int | None = Field(None, ge=0)
    starts_at: date_aliased | None = None
    ends_at: date_aliased | None = None


class Type(StrEnum):
    GIFTED_PRODUCT = "gifted_product"
    COMPED_EVENT = "comped_event"
    COMPED_TRAVEL = "comped_travel"
    EQUITY = "equity"
    DISCOUNT_CODE = "discount_code"
    OTHER = "other"


class AdditionalCompensationItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type
    value_usd: float | None = Field(None, ge=0.0)
    description: str | None = None


class VsIndustryBenchmark(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    category_avg: float | None = None
    category_p50: float | None = None
    category_p90: float | None = None
    performance_label: str | None = Field(
        None,
        description="Human-readable summary, e.g. '2.3x category', '+29% vs category', 'top 10%'.",
    )
    benchmark_source: str | None = None
    benchmark_as_of_year: int | None = None


class Outcome(StrEnum):
    """
    Overall outcome classification. successful_renewed = brand renewed for follow-on campaign; successful = completed cleanly, no renewal; mixed = some KPIs hit, some missed; underperformed = KPIs missed by >20%; unfulfilled = campaign didn't complete (talent or brand pulled out).
    """

    PENDING = "pending"
    SUCCESSFUL_RENEWED = "successful_renewed"
    SUCCESSFUL = "successful"
    MIXED = "mixed"
    UNDERPERFORMED = "underperformed"
    UNFULFILLED = "unfulfilled"


class DataSource(StrEnum):
    MEDIA_PACK = "media_pack"
    IG_INSIGHTS_EXPORT = "ig_insights_export"
    TIKTOK_ANALYTICS_EXPORT = "tiktok_analytics_export"
    YOUTUBE_ANALYTICS_EXPORT = "youtube_analytics_export"
    BRAND_INVOICE = "brand_invoice"
    BRAND_REPORT = "brand_report"
    TRIBE_DYNAMICS_REPORT = "tribe_dynamics_report"
    HYPEAUDITOR_REPORT = "hypeauditor_report"
    MANUAL_ENTRY = "manual_entry"
    PLATFORM_API = "platform_api"
    AI_INFERENCE_FROM_POST_URLS = "ai_inference_from_post_urls"


class KpiMetric(RootModel[kpi_metric_schema.KpiMetric]):
    root: kpi_metric_schema.KpiMetric


class Kpis(BaseModel):
    """
    Quantitative results. Every metric carries source provenance. Omit metrics with no confident value.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    reach: KpiMetric | None = None
    impressions: KpiMetric | None = None
    engagement_total: KpiMetric | None = None
    engagement_rate_pct: KpiMetric | None = None
    video_views: KpiMetric | None = None
    video_completion_rate_pct: KpiMetric | None = None
    avg_watch_time_seconds: KpiMetric | None = None
    likes: KpiMetric | None = None
    comments: KpiMetric | None = None
    shares: KpiMetric | None = None
    saves: KpiMetric | None = None
    link_clicks: KpiMetric | None = None
    ctr_pct: KpiMetric | None = None
    conversions: KpiMetric | None = None
    sales_attributed_usd: KpiMetric | None = None
    new_followers_for_brand: KpiMetric | None = None
    promo_code_redemptions: KpiMetric | None = None
    cpm_usd: KpiMetric | None = None
    cpe_usd: KpiMetric | None = None
    cpv_usd: KpiMetric | None = None
    emv_usd: KpiMetric | None = None


class Deal(BaseModel):
    """
    One brand campaign. KPI fields each carry source provenance per the honesty-floor policy — never fabricate. Re-engagement metadata captured separately so Search 1 of Brand Discovery has everything it needs without parsing dates.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    deal_id: str = Field(
        ...,
        description="Stable identifier. Suggested format: `deal_{year}_{brand_slug}_{quarter_or_seq}` (e.g. `deal_2025_gymshark_q4`).",
        pattern="^deal_[a-z0-9_]+$",
    )
    brand_id: str = Field(
        ...,
        description="FK to `data/brand_industry_map.json` (normalised name slug).",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    brand_name: str | None = Field(
        None,
        description="Denormalised display name for at-a-glance reading. Source of truth remains `brand_industry_map.json`.",
    )
    industry_id: str = Field(
        ...,
        description="FK to `data/industries.json`. Denormalised from brand_industry_map at deal-creation time.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    campaign_name: str | None = Field(
        None,
        description="Brand's name for the campaign (e.g. 'Lift Collection Launch', 'Holiday 2025').",
    )
    campaign_type: CampaignType = Field(
        ...,
        description="Deal structure type. sponsored_post = single piece; sponsored_series = multi-post campaign; ambassador = long-term recurring; product_seeding = gifted product, no fee; affiliate = commission-based; ugc_license = brand licenses talent content; whitelisting = talent content used as brand paid social; paid_appearance = event/panel/host; brand_integration = paid mention in non-sponsored content; co_branded_product = co-creation.",
    )
    campaign_objective: CampaignObjective | None = Field(
        None,
        description="Brand's stated goal for the campaign. Drives which KPIs matter most for the post-campaign analysis.",
    )
    started_at: date_aliased | None = None
    ended_at: date_aliased | None = None
    posted_dates: list[date_aliased] | None = Field(
        None,
        description="Specific dates when content was posted. Used for time-on-feed analysis and post-by-post KPI breakdowns.",
    )
    deliverables: list[Deliverable] | None = Field(
        None, description="What the talent agreed to produce."
    )
    fee_usd: float | None = Field(
        None,
        description="Total fee converted to USD. May be 0 for product_seeding deals.",
        ge=0.0,
    )
    fee_currency_original: str | None = Field(
        None, description="ISO 4217 (e.g. GBP, USD, EUR).", pattern="^[A-Z]{3}$"
    )
    fee_original_amount: float | None = Field(None, ge=0.0)
    usage_rights_granted: list[UsageRightsGrantedEnum] | None = None
    exclusivity: Exclusivity | None = None
    additional_compensation: list[AdditionalCompensationItem] | None = Field(
        None,
        description="Non-cash compensation: gifted product, event invites, equity, comped travel.",
    )
    kpis: Kpis | None = Field(
        None,
        description="Quantitative results. Every metric carries source provenance. Omit metrics with no confident value.",
    )
    vs_industry_benchmark: dict[str, VsIndustryBenchmark] | None = Field(
        None,
        description="Per-KPI comparison against industry benchmarks. SCHEMA SHIPS IN v0.1 but population requires `data/industry_kpi_benchmarks.json` which is deferred to v2 — until then, this object stays empty. When benchmarks data ships, the orchestrator computes these comparisons automatically from `kpis.*` against the benchmark file.",
    )
    audience_overlap_with_brand_target_pct: float | None = Field(
        None,
        description="Estimated percentage of the talent's audience that matches the brand's target customer profile. Computed at campaign-end from IAB segment overlap + any brand-provided audience-match data.",
        ge=0.0,
        le=100.0,
    )
    audience_demographics_at_campaign_time: dict[str, Any] | None = Field(
        None,
        description="Snapshot of the talent's audience_demographics. Snapshot timing convention (v0.1): captured at auto-archive time, NOT at campaign-end. This is best-effort — audience_demographics may have evolved between campaign-end and archive (typically a 30-90d window). For precise campaign-end demographics, downstream tooling can cross-reference `deal.delivery.interim_kpi_snapshots[]` capture timestamps + a future audience-demographics snapshot store. Same shape as `talent.audience_demographics`. See `docs/data_lineage.md` GAP-13.",
    )
    performance_notes: str | None = Field(
        None,
        description="Free-text qualitative summary. What worked, what didn't, brand feedback, lessons learned. Used as context by the email generator when citing this campaign.",
    )
    outcome: Outcome = Field(
        ...,
        description="Overall outcome classification. successful_renewed = brand renewed for follow-on campaign; successful = completed cleanly, no renewal; mixed = some KPIs hit, some missed; underperformed = KPIs missed by >20%; unfulfilled = campaign didn't complete (talent or brand pulled out).",
    )
    case_study_url: AnyUrl | None = Field(
        None,
        description="Optional public URL of the campaign case study (often on the brand or agency website). Powers the `case_study_available` pitch angle.",
    )
    do_not_recontact: bool | None = Field(
        False,
        description="Hard flag. When true, Brand Discovery Search 1 (re-engagement) will never surface this brand for this talent. Set after a soured deal or explicit 'don't come back' from the brand.",
    )
    cool_down_override_days: int | None = Field(
        None,
        description="Days to wait before this brand is eligible for re-engagement. Null = use default 180 days from ended_at. Set per-deal to honour brand-specific cadences (e.g. 'come back in March' = explicit date).",
        ge=0,
    )
    last_re_engagement_pitch_date: date_aliased | None = Field(
        None,
        description="When we last sent a re-engagement pitch to this brand for this talent. Used to extend cool-down on no-response (anti-spam — see Brand Discovery Search 1 § De-spam).",
    )
    renewal_eligibility_date: date_aliased | None = Field(
        None,
        description="Computed: ended_at + cool_down_override_days (or default 180). Null while campaign is `pending`. The orchestrator updates this whenever ended_at or cool_down_override_days changes.",
    )
    main_brand_contact_id: str | None = Field(
        None,
        description="FK to a contact_id in `data/brand_contacts/{brand_id}.json`. The person at the brand who ran this campaign. Powers warm-intro identification — when this person changes brands, we know we have a warm relationship to leverage.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    agency_contact_id: str | None = Field(
        None,
        description="FK if the deal went through an agency-of-record. Contact at the AOR brand_id.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    originated_from_pitch_enrollment_id: str | None = Field(
        None,
        description="Optional FK to `data/pitch_enrollments/{enrollment_id}.json` if this deal originated from a pitch our outreach engine sent. Closes the loop: we can compute 'reply → deal' conversion rates by talent / template / angle for the analytics layer.",
        pattern="^enr_[a-z0-9]+$",
    )
    archived_from_deal_id: str | None = Field(
        None,
        description="Optional FK to the Phase 4 pipeline deal (`data/deals/{deal_id}.json`) that this historical brand_deal was auto-archived from. Closes the bidirectional link: the pipeline deal's `close.archived_to_brand_deal_id` points here, and this field points back. Anyone reviewing this archived deal can navigate to the full pipeline history.",
        pattern="^deal_pipeline_[a-z0-9_-]+$",
    )
    data_sources: list[DataSource] | None = Field(
        None,
        description="Which sources contributed data to this record. Honesty-floor: every populated KPI's `source` should be reflected here.",
    )
    first_recorded_at: AwareDatetime
    last_updated_at: AwareDatetime
    manually_verified_by_talent: bool | None = Field(
        False,
        description="Whether the talent has reviewed and confirmed the data. Distinguishes AI-extracted-but-unreviewed from talent-verified records. Email generator weights verified records higher when citing metrics.",
    )
    notes: str | None = Field(
        None,
        description="Free-text internal notes (agency-side). Not surfaced to brand contacts.",
    )


class BrandDealsPerTalent(BaseModel):
    """
    Per-talent file capturing the rich record of every brand campaign the talent has done. One file per talent at `data/brand_deals/{talent_id}.json` (folder gitignored — commercial KPI data and exact fees shouldn't be in the repo). Powers: Brand Discovery Search 1 (re-engagement timing), Pitch Angles (5 KPI-driven angles + enrichment of 3 existing), Outreach AI generation (citation material in pitch prompts), and Contact Enrichment (warm-intro candidate identification). See `docs/brand_deals_workflow.md`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: str | None = Field(None, alias="$schema")
    agency_id: UUID | None = Field(
        None,
        description="Multi-tenant scope: FK to agency_profile.agency_id. Optional in v0.1 (single-tenant deploys may omit); required in v2 SaaS. When present, all cross-record queries MUST filter by agency_id to prevent cross-tenant data leakage. See docs/data_lineage.md GAP-01/02 for rationale.",
    )
    talent_id: str = Field(
        ...,
        description="Slug matching the `id` in the source `talents/{id}.json`.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    version: str
    last_updated_at: AwareDatetime | None = None
    deals: list[Deal] = Field(
        ...,
        description="All known brand campaigns for this talent — past + active + upcoming. Sorted newest first by convention.",
    )
