# generated by datamodel-codegen:
#   filename:  brand_industry_map.schema.json
#   timestamp: 2026-05-28T08:49:29+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class SellsInCountries(StrEnum):
    GLOBAL = "global"


class SellsInCountry(RootModel[str]):
    root: str = Field(..., pattern="^[A-Z]{2}$")


class CompanyStage(StrEnum):
    BOOTSTRAPPED = "bootstrapped"
    SEED = "seed"
    SERIES_A = "series_a"
    SERIES_B = "series_b"
    SERIES_C = "series_c"
    SERIES_D = "series_d"
    PRIVATE_GROWTH = "private_growth"
    PUBLIC = "public"
    SUBSIDIARY = "subsidiary"
    STATE_OWNED = "state_owned"
    UNKNOWN = "unknown"


class TypicalCampaignTier(StrEnum):
    NANO = "nano"
    MICRO = "micro"
    MID = "mid"
    MACRO = "macro"
    PREMIUM = "premium"
    UNKNOWN = "unknown"


class CreatorProgramPresenceEnum(StrEnum):
    DIRECT = "direct"
    ASPIRE = "aspire"
    GRIN = "grin"
    LTK = "ltk"
    SHOPMY = "shopmy"
    AGENCY_OF_RECORD = "agency_of_record"


class Source(StrEnum):
    PUBLIC_FILING = "public_filing"
    PRESS_RELEASE = "press_release"
    REPORTED_ESTIMATE = "reported_estimate"


class Revenue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    amount_usd: int = Field(..., ge=0)
    as_of_year: int = Field(..., ge=1900, le=2100)
    source: Source


class Band(StrEnum):
    FIELD_1_10 = "1_10"
    FIELD_11_50 = "11_50"
    FIELD_51_200 = "51_200"
    FIELD_201_500 = "201_500"
    FIELD_501_1000 = "501_1000"
    FIELD_1001_5000 = "1001_5000"
    FIELD_5001_10000 = "5001_10000"
    FIELD_10000_PLUS = "10000_plus"


class Source6(StrEnum):
    LINKEDIN = "linkedin"
    PUBLIC_FILING = "public_filing"
    PRESS_RELEASE = "press_release"
    REPORTED_ESTIMATE = "reported_estimate"


class Headcount(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    band: Band
    source: Source6


class SocialFollowers(BaseModel):
    """
    Brand's own social-media follower counts per platform. Integer counts as of as_of_year. Platforms with minimal/uncertain presence omitted.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    instagram: int | None = Field(None, ge=0)
    tiktok: int | None = Field(None, ge=0)
    youtube: int | None = Field(None, ge=0)
    twitter_x: int | None = Field(None, ge=0)
    facebook: int | None = Field(None, ge=0)
    linkedin: int | None = Field(None, ge=0)
    pinterest: int | None = Field(None, ge=0)
    as_of_year: int = Field(..., ge=2000, le=2100)


class SocialHandles(BaseModel):
    """
    Brand's own social-media handles per platform (NOT contact handles — those live on `brand_contact.social_handles`). Handles WITHOUT the leading `@` symbol (e.g. `nike` not `@nike`). Critical input to Phase 4.8 deliverable detection — cron uses `{platform}_handle` to score whether the talent's candidate post mentions the brand (e.g. searches captions/tags for `@nike`). Refreshed weekly via Exa; on change detected, last_handle_change timestamp logged for audit. Populated as discovered — absent = handle unknown for that platform.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    instagram: str | None = None
    tiktok: str | None = None
    youtube: str | None = Field(
        None,
        description="Channel handle (the @-style handle YouTube introduced in 2022, not the legacy channel name).",
    )
    twitter_x: str | None = None
    facebook: str | None = None
    linkedin: str | None = Field(
        None, description="Company-page slug (e.g. `nike-inc`)."
    )
    pinterest: str | None = None
    last_handle_change_at: date_aliased | None = Field(
        None,
        description="Most recent date any handle here changed (rebrand detection).",
    )


class Source7(StrEnum):
    EXA_RESEARCH = "exa_research"
    AGENT_UPLOADED_W9 = "agent_uploaded_w9"
    AGENT_UPLOADED_REGISTRATION = "agent_uploaded_registration"
    MANUAL_ENTRY = "manual_entry"
    PRIOR_CONTRACT = "prior_contract"


class LegalEntity(BaseModel):
    """
    Brand's legal entity for contracts/invoicing. Often differs from trading name (e.g. brand 'Nike' = legal entity 'Nike, Inc.'). Captured opportunistically — agent may also provide via contract_pack.context_artefacts.brand_legal_info upload. Populating this field once at the brand level avoids per-deal re-capture friction.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    legal_name: str | None = Field(
        None,
        description="Full legal entity name (e.g. 'Nike, Inc.', 'Lululemon Athletica Inc.', 'GymShark Limited').",
    )
    entity_type: str | None = Field(
        None, description="Free-text (e.g. 'Delaware C-Corp', 'UK Limited', 'GmbH')."
    )
    registered_address: str | None = None
    registered_country: str | None = Field(None, pattern="^[A-Z]{2}$")
    tax_id: str | None = None
    last_verified_at: date_aliased | None = None
    source: Source7 | None = None


class Brand(BaseModel):
    """
    One brand entry. `brand_id` is implicit — derived from `name` via normalisation (lowercase + kebab-case + suffix stripping). All other fields optional; absence = unknown for that brand.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(
        ...,
        description="Display name (e.g. 'Lululemon Athletica'). The normalised slug of this becomes the brand_id used as FK in brand_candidates / brand_contacts / brand_deals / deals / etc.",
    )
    industry_id: str = Field(
        ..., description="FK to `data/industries.json`.", pattern="^[a-z0-9][a-z0-9-]*$"
    )
    aliases: list[str] | None = Field(
        None,
        description="Alternate names the brand goes by (parent company names, abbreviations, legacy names). Used for fuzzy matching during enrichment + outreach reply classification.",
    )
    domain: str | None = Field(
        None,
        description="Primary web domain (e.g. 'nike.com'). No https://; no path. Used as merge key for Apollo contact lookups + Exa search seeding.",
    )
    hq_country: str | None = Field(
        None, description="ISO 3166-1 alpha-2.", pattern="^[A-Z]{2}$"
    )
    sells_in_countries: SellsInCountries | list[SellsInCountry] | None = None
    company_stage: CompanyStage | None = None
    typical_campaign_tier: TypicalCampaignTier | None = None
    creator_program_presence: list[CreatorProgramPresenceEnum] | None = None
    revenue: Revenue | None = None
    headcount: Headcount | None = None
    social_followers: SocialFollowers | None = Field(
        None,
        description="Brand's own social-media follower counts per platform. Integer counts as of as_of_year. Platforms with minimal/uncertain presence omitted.",
    )
    social_handles: SocialHandles | None = Field(
        None,
        description="Brand's own social-media handles per platform (NOT contact handles — those live on `brand_contact.social_handles`). Handles WITHOUT the leading `@` symbol (e.g. `nike` not `@nike`). Critical input to Phase 4.8 deliverable detection — cron uses `{platform}_handle` to score whether the talent's candidate post mentions the brand (e.g. searches captions/tags for `@nike`). Refreshed weekly via Exa; on change detected, last_handle_change timestamp logged for audit. Populated as discovered — absent = handle unknown for that platform.",
    )
    legal_entity: LegalEntity | None = Field(
        None,
        description="Brand's legal entity for contracts/invoicing. Often differs from trading name (e.g. brand 'Nike' = legal entity 'Nike, Inc.'). Captured opportunistically — agent may also provide via contract_pack.context_artefacts.brand_legal_info upload. Populating this field once at the brand level avoids per-deal re-capture friction.",
    )


class BrandIndustryMap(BaseModel):
    """
    The canonical brand reference dataset — agency-wide source-of-truth for brand metadata (industry classification, domain, social handles + follower counts, company stage, revenue, headcount, creator-program presence). Lives at `data/brand_industry_map.json` (committed; not gitignored — global reference data, not per-talent). Every brand-related schema in the system references entries here by `brand_id` (kebab-case slug derived from `name`). Refreshed by Phase 2 brand discovery + Phase 3a contact enrichment. Brand handles in `social_handles` are critical input to Phase 4.8 deliverable detection (the cron scores candidate posts on whether the talent tagged the brand via `@{handle}`).
    """

    model_config = ConfigDict(
        extra="allow",
    )
    field_schema: str | None = Field(None, alias="$schema")
    field_comment: str | None = Field(None, alias="$comment")
    version: str = Field(
        ...,
        description="Schema version of the file shape. Bump on breaking shape changes (additive changes don't require version bump).",
    )
    updated: date_aliased | None = Field(
        None, description="When this file was last regenerated."
    )
    brands: list[Brand] = Field(
        ...,
        description="Canonical brand records. Sorted by name for deterministic git diffs.",
    )
    enrichment_field_definitions: dict[str, Any] | None = Field(
        None,
        description="Optional documentation of what each field means + source authority. Not required for validation.",
    )
