# generated by datamodel-codegen:
#   filename:  brand_candidates.schema.json
#   timestamp: 2026-06-01T11:52:22+00:00

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Any
from uuid import UUID

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    RootModel,
    constr,
)


class Tier(StrEnum):
    PRIMARY = "primary"
    SECONDARY = "secondary"
    TERTIARY = "tertiary"


class Tier1(StrEnum):
    """
    Tier assignment based on score + presence of re-engagement source. Used to group the UI.
    """

    RE_ENGAGE = "re-engage"
    PRIMARY = "primary"
    SECONDARY = "secondary"
    TERTIARY = "tertiary"


class BlockedReason(Enum):
    """
    Reason category if blocked. Free-text explanation lives in `next_action_hint` or top-level `blocked[].details`.
    """

    NONE_TYPE_NONE = None
    BLOCKED_INDUSTRY = "blocked_industry"
    ACTIVE_EXCLUSIVITY = "active_exclusivity"
    DO_NOT_RECONTACT = "do_not_recontact"
    QUALIFICATION_BELOW_FLOOR = "qualification_below_floor"


class Status(StrEnum):
    """
    Workflow state. PRESERVED across discovery re-runs. Sync direction: pre-pitch states (`new`, `shortlisted`, `parked`) are user-driven and live here as source-of-truth. Post-pitch states (`pitched`, `responded`, `negotiating`, `closed_won`, `closed_lost`) are DENORMALISED from upstream canonical sources — the orchestrator updates them on state changes in (a) `pitch_enrollment` (pitched/responded transitions) and (b) Phase 4 `deal.stage` + `deal.is_won` / `is_terminal` (negotiating/closed_won/closed_lost). When this field disagrees with the canonical source, the canonical wins on next sync; this field is for fast UI rendering only.
    """

    NEW = "new"
    SHORTLISTED = "shortlisted"
    PITCHED = "pitched"
    RESPONDED = "responded"
    NEGOTIATING = "negotiating"
    CLOSED_WON = "closed_won"
    CLOSED_LOST = "closed_lost"
    PARKED = "parked"


class LegalEntityOverride(BaseModel):
    """
    Per-talent override of `brand_industry_map.brands[].legal_entity` for this brand. Used when the talent/agency has reason to invoice a different legal entity than the canonical brand entity (e.g. brand subsidiary, distributor, agency-of-record). Captured opportunistically during proposal stage; absent = use the canonical entity from brand_industry_map. Same field shape as `brand_industry_map.brands[].legal_entity`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    legal_name: str | None = None
    entity_type: str | None = None
    registered_address: str | None = None
    registered_country: str | None = Field(None, pattern="^[A-Z]{2}$")
    tax_id: str | None = None
    signatory_name: str | None = Field(
        None,
        description="Person signing on behalf of the brand for this specific deal. Often differs from primary_contact.",
    )
    signatory_title: str | None = None
    signatory_email: EmailStr | None = None
    override_reason: str | None = Field(
        None,
        description="Why this brand uses a non-canonical legal entity for this talent (e.g. 'EU subsidiary handles all UK creator deals').",
    )
    captured_at: AwareDatetime | None = None


class Search(StrEnum):
    """
    Identifier of the search that surfaced this brand. The first 16 are in-scope today (Searches 1-16 in docs/brand_discovery.md); the rest correspond to future-version searches and may appear once those are wired up. `preferred_industry` is an additive boost source — applied to every candidate whose industry_id is in talent.brand_preferences.preferred_industries.
    """

    PREVIOUS_BRAND_REENGAGE = "previous_brand_reengage"
    SIMILAR_TALENT_WORKED_WITH = "similar_talent_worked_with"
    COMPETITOR_OF_PREVIOUS = "competitor_of_previous"
    COMPETITOR_OF_SIMILAR_TALENT = "competitor_of_similar_talent"
    PRIMARY_INDUSTRY = "primary_industry"
    SECONDARY_INDUSTRY = "secondary_industry"
    TERTIARY_INDUSTRY = "tertiary_industry"
    PARENT_SIBLING_NICHE = "parent_sibling_niche"
    DEMOGRAPHIC_BRIDGE = "demographic_bridge"
    GEOGRAPHIC_ALIGNMENT = "geographic_alignment"
    LIFE_STAGE_SIGNAL = "life_stage_signal"
    COMPLEMENTARY_TO_EXCLUSIVITY = "complementary_to_exclusivity"
    VALUES_ALIGNED = "values_aligned"
    GRAPH_EXPANSION_2ND_DEGREE = "graph_expansion_2nd_degree"
    RECENTLY_FUNDED = "recently_funded"
    TRENDING_30D = "trending_30d"
    PREFERRED_INDUSTRY = "preferred_industry"
    CURRENTLY_RUNNING_CREATOR_CAMPAIGN = "currently_running_creator_campaign"
    ACTIVE_AFFILIATE_PROGRAM = "active_affiliate_program"
    RATE_CARD_TIER_MATCH_LIVE = "rate_card_tier_match_live"
    TRADE_SHOW_EXHIBITOR = "trade_show_exhibitor"
    RETAIL_ACCELERATOR_ALUMNI = "retail_accelerator_alumni"
    RECENT_INFLUENCER_AGENCY_APPOINTMENT = "recent_influencer_agency_appointment"
    SEASONAL_PRODUCT_LAUNCH = "seasonal_product_launch"
    CREATOR_MARKETPLACE_LISTED = "creator_marketplace_listed"
    EMV_TOP_PERFORMER = "emv_top_performer"
    AUDIENCE_LOOKALIKE = "audience_lookalike"
    VALUES_COMMITMENT_MATCH = "values_commitment_match"


class Source(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    search: Search = Field(
        ...,
        description="Identifier of the search that surfaced this brand. The first 16 are in-scope today (Searches 1-16 in docs/brand_discovery.md); the rest correspond to future-version searches and may appear once those are wired up. `preferred_industry` is an additive boost source — applied to every candidate whose industry_id is in talent.brand_preferences.preferred_industries.",
    )
    weight: float = Field(
        ...,
        description="Contribution to the candidate's score from this source. Per `docs/brand_discovery.md` source-weight table.",
        ge=0.0,
        le=1.0,
    )
    note: str | None = Field(
        None,
        description="Free-form, human-readable explanation of this match (e.g. 'fitness primary -> activewear; well-documented creator program'). UI shows this verbatim.",
    )


class SellsInCountries(StrEnum):
    GLOBAL = "global"


class SellsInCountry(RootModel[str]):
    root: str = Field(..., pattern="^[A-Z]{2}$")


class CompanyStage(StrEnum):
    BOOTSTRAPPED = "bootstrapped"
    SEED = "seed"
    SERIES_A = "series_a"
    SERIES_B = "series_b"
    SERIES_C = "series_c"
    SERIES_D = "series_d"
    PRIVATE_GROWTH = "private_growth"
    PUBLIC = "public"
    SUBSIDIARY = "subsidiary"
    STATE_OWNED = "state_owned"
    UNKNOWN = "unknown"


class TypicalCampaignTier(StrEnum):
    NANO = "nano"
    MICRO = "micro"
    MID = "mid"
    MACRO = "macro"
    PREMIUM = "premium"
    UNKNOWN = "unknown"


class CreatorProgramPresenceEnum(StrEnum):
    DIRECT = "direct"
    ASPIRE = "aspire"
    GRIN = "grin"
    LTK = "ltk"
    SHOPMY = "shopmy"
    AGENCY_OF_RECORD = "agency_of_record"


class Source1(StrEnum):
    PUBLIC_FILING = "public_filing"
    PRESS_RELEASE = "press_release"
    REPORTED_ESTIMATE = "reported_estimate"


class Revenue(BaseModel):
    """
    Annual revenue in USD, with year reported and source.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    amount_usd: int = Field(..., ge=0)
    as_of_year: int = Field(..., ge=1900, le=2100)
    source: Source1


class Band(StrEnum):
    FIELD_1_10 = "1_10"
    FIELD_11_50 = "11_50"
    FIELD_51_200 = "51_200"
    FIELD_201_500 = "201_500"
    FIELD_501_1000 = "501_1000"
    FIELD_1001_5000 = "1001_5000"
    FIELD_5001_10000 = "5001_10000"
    FIELD_10000_PLUS = "10000_plus"


class Source2(StrEnum):
    LINKEDIN = "linkedin"
    PUBLIC_FILING = "public_filing"
    PRESS_RELEASE = "press_release"
    REPORTED_ESTIMATE = "reported_estimate"


class Headcount(BaseModel):
    """
    Employee count as a LinkedIn-standard band, with source.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    band: Band
    source: Source2


class SocialFollowers(BaseModel):
    """
    Brand's own social-media follower counts per platform, integer counts, with as_of_year. Platforms with minimal/uncertain presence are omitted.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    instagram: int | None = Field(None, ge=0)
    tiktok: int | None = Field(None, ge=0)
    youtube: int | None = Field(None, ge=0)
    twitter_x: int | None = Field(None, ge=0)
    facebook: int | None = Field(None, ge=0)
    linkedin: int | None = Field(None, ge=0)
    pinterest: int | None = Field(None, ge=0)
    as_of_year: int = Field(..., ge=2000, le=2100)


class BrandSnapshot(BaseModel):
    """
    Fields copied from brand_industry_map.json at discovery time. Absence of a field means it was missing in the source.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    domain: str | None = None
    hq_country: str | None = Field(None, pattern="^[A-Z]{2}$")
    sells_in_countries: SellsInCountries | list[SellsInCountry] | None = None
    company_stage: CompanyStage | None = None
    typical_campaign_tier: TypicalCampaignTier | None = None
    creator_program_presence: list[CreatorProgramPresenceEnum] | None = None
    revenue: Revenue | None = Field(
        None, description="Annual revenue in USD, with year reported and source."
    )
    headcount: Headcount | None = Field(
        None, description="Employee count as a LinkedIn-standard band, with source."
    )
    social_followers: SocialFollowers | None = Field(
        None,
        description="Brand's own social-media follower counts per platform, integer counts, with as_of_year. Platforms with minimal/uncertain presence are omitted.",
    )


class Tier2(StrEnum):
    """
    qualified: score >= 0.60; speculative: 0.30-0.60; unqualified: < 0.30.
    """

    QUALIFIED = "qualified"
    SPECULATIVE = "speculative"
    UNQUALIFIED = "unqualified"


class Signal(StrEnum):
    """
    Identifier of the qualification signal. New signals can be added — keep the enum sorted by direction (positives first, then negatives) for review-ability.
    """

    ACTIVE_CREATOR_PROGRAM = "active_creator_program"
    MACRO_OR_PREMIUM_CAMPAIGN_TIER = "macro_or_premium_campaign_tier"
    MID_CAMPAIGN_TIER = "mid_campaign_tier"
    MICRO_OR_NANO_CAMPAIGN_TIER = "micro_or_nano_campaign_tier"
    ESTABLISHED_COMPANY = "established_company"
    BOOTSTRAPPED_OR_EARLY_STAGE = "bootstrapped_or_early_stage"
    SUBSIDIARY_OF_MAJOR_PARENT = "subsidiary_of_major_parent"
    ACTIVE_PAID_PARTNERSHIPS_OBSERVED = "active_paid_partnerships_observed"
    RECENT_FUNDING_ROUND = "recent_funding_round"
    ENTERPRISE_REVENUE = "enterprise_revenue"
    SIGNIFICANT_REVENUE = "significant_revenue"
    MINIMAL_REVENUE = "minimal_revenue"
    LARGE_HEADCOUNT = "large_headcount"
    MID_HEADCOUNT = "mid_headcount"
    SMALL_HEADCOUNT = "small_headcount"
    HIGH_OWN_BRAND_FOLLOWER_COUNT = "high_own_brand_follower_count"
    MODERATE_OWN_BRAND_FOLLOWER_COUNT = "moderate_own_brand_follower_count"
    LOW_OWN_BRAND_FOLLOWER_COUNT = "low_own_brand_follower_count"
    B2B_VERTICAL = "b2b_vertical"
    NO_CREATOR_PARTNERSHIPS_OBSERVED = "no_creator_partnerships_observed"
    HIGH_EMV_IN_CATEGORY = "high_emv_in_category"
    SENSITIVE_VERTICAL_WARNING = "sensitive_vertical_warning"


class QualificationSignal(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    signal: Signal = Field(
        ...,
        description="Identifier of the qualification signal. New signals can be added — keep the enum sorted by direction (positives first, then negatives) for review-ability.",
    )
    weight: float = Field(
        ...,
        description="Contribution to qualification score. Positive = stronger likelihood-to-buy; negative = weaker. Typical magnitudes: 0.05-0.30.",
        ge=-1.0,
        le=1.0,
    )
    details: str | None = Field(
        None,
        description="Human-readable explanation. e.g. 'creator_program_presence: [direct, aspire]' or 'IG followers: 8.2k (below 50k threshold for active creator-marketing buyers)'.",
    )


class Type(StrEnum):
    """
    Warning category. UI renders an appropriate badge per type.
    """

    SENSITIVE_CATEGORY = "sensitive_category"
    EXCLUSIVITY_ADJACENT = "exclusivity_adjacent"
    VALUES_RED_LINE_NEUTRAL = "values_red_line_neutral"
    LOW_QUALIFICATION = "low_qualification"
    STALE_IN_PIPELINE = "stale_in_pipeline"


class Warning(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type = Field(
        ..., description="Warning category. UI renders an appropriate badge per type."
    )
    details: str = Field(
        ..., description="Free-text explanation shown next to the badge."
    )


class Channel(StrEnum):
    EMAIL = "email"
    INSTAGRAM_DM = "instagram_dm"
    LINKEDIN_MESSAGE = "linkedin_message"
    CREATOR_MARKETPLACE_APPLY = "creator_marketplace_apply"
    AGENCY_INTRO = "agency_intro"
    OTHER = "other"


class Outcome(StrEnum):
    SENT = "sent"
    DELIVERED = "delivered"
    OPENED = "opened"
    REPLIED = "replied"
    INTERESTED = "interested"
    DECLINED = "declined"
    NO_RESPONSE = "no_response"
    BOUNCED = "bounced"


class PitchHistoryEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pitched_at: AwareDatetime
    channel: Channel
    template_id: str | None = None
    recipient_contact: str | None = Field(
        None,
        description="Identifier of the contact pitched (email or handle). Format depends on channel.",
    )
    outcome: Outcome
    next_followup_at: AwareDatetime | None = None
    notes: str | None = None


class Reason(StrEnum):
    BLOCKED_INDUSTRY = "blocked_industry"
    ACTIVE_EXCLUSIVITY = "active_exclusivity"
    DO_NOT_RECONTACT = "do_not_recontact"
    QUALIFICATION_BELOW_FLOOR = "qualification_below_floor"


class ByTier(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    re_engage: int | None = Field(None, alias="re-engage", ge=0)
    primary: int | None = Field(None, ge=0)
    secondary: int | None = Field(None, ge=0)
    tertiary: int | None = Field(None, ge=0)


class ByStatus(BaseModel):
    """
    Distribution of workflow statuses across the candidates.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    new: int | None = Field(None, ge=0)
    shortlisted: int | None = Field(None, ge=0)
    pitched: int | None = Field(None, ge=0)
    responded: int | None = Field(None, ge=0)
    negotiating: int | None = Field(None, ge=0)
    closed_won: int | None = Field(None, ge=0)
    closed_lost: int | None = Field(None, ge=0)
    parked: int | None = Field(None, ge=0)


class ByQualificationTier(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    qualified: int | None = Field(None, ge=0)
    speculative: int | None = Field(None, ge=0)
    unqualified: int | None = Field(None, ge=0)


class Stats(BaseModel):
    """
    Summary statistics across this run. Pre-computed so the UI doesn't need to scan candidates[] for every render.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    total_candidates: int | None = Field(None, ge=0)
    total_blocked: int | None = Field(None, ge=0)
    total_qualification_filtered: int | None = Field(None, ge=0)
    by_tier: ByTier | None = None
    by_source_count: dict[constr(pattern=r"^([1-4]|5\+)$"), int] | None = Field(
        None,
        description="Distribution of candidates by how many searches surfaced them. Keys '1','2','3','4','5+'.",
    )
    by_status: ByStatus | None = Field(
        None, description="Distribution of workflow statuses across the candidates."
    )
    by_qualification_tier: ByQualificationTier | None = None


class SearchError(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    search: str
    error: str
    fatal: bool | None = Field(
        None,
        description="If true, the run is considered degraded and the user is notified. If false, the search silently failed but the overall run completed.",
    )


class Writebacks(BaseModel):
    """
    Records mutated outside this file as a side effect of the run (e.g. new brands added to brand_industry_map.json via the Search 15/16 growth loop).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    brand_industry_map_additions: list[str] | None = None
    brand_competitors_additions: list[str] | None = None


class RunMetadata(BaseModel):
    """
    Orchestrator-side telemetry for this run. Useful for monitoring scheduled-job health and vendor-quota consumption.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    search_durations_ms: dict[str, int] | None = Field(
        None, description="Per-search wall-clock duration in milliseconds."
    )
    search_errors: list[SearchError] | None = None
    vendor_usage: dict[str, Any] | None = Field(
        None,
        description="Per-vendor quota usage on this run. Keys are vendor identifiers; values are vendor-specific usage records.",
    )
    writebacks: Writebacks | None = Field(
        None,
        description="Records mutated outside this file as a side effect of the run (e.g. new brands added to brand_industry_map.json via the Search 15/16 growth loop).",
    )


class NicheSignal(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    niche_id: str = Field(
        ...,
        description="Kebab-case slug that MUST match an `id` in data/niches.json.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    tier: Tier


class Qualification(BaseModel):
    """
    Likelihood this brand is an active creator-marketing buyer. Used to filter out candidates unlikely to convert before they clutter the UI. Surfaces both positive and negative signals so a user can override the auto-filter when context warrants.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    score: float = Field(
        ...,
        description="0-1, likelihood this brand actively buys creator marketing. Capped sum of qualification signals. Default filter threshold: 0.30 (candidates below get qualification_filtered: true).",
        ge=0.0,
        le=1.0,
    )
    tier: Tier2 = Field(
        ...,
        description="qualified: score >= 0.60; speculative: 0.30-0.60; unqualified: < 0.30.",
    )
    signals: list[QualificationSignal] = Field(
        ...,
        description="Individual signals contributing to the qualification score. Positive weights add; negative weights subtract.",
    )
    threshold_applied: float | None = Field(
        None,
        description="The threshold used for qualification_filtered determination on this run. Logged so user-set overrides are auditable.",
        ge=0.0,
        le=1.0,
    )


class BlockedBrand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    brand: str
    brand_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    industry_id: str | None = Field(
        None,
        description="Kebab-case slug that MUST match an `id` in data/industries.json.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    reason: Reason
    details: str | None = Field(
        None,
        description="Free-text explanation (e.g. 'Active exclusivity in sportswear until 2026-12-31').",
    )


class Candidate(BaseModel):
    """
    One brand candidate. Discovery-output fields are rebuilt every run; workflow-state fields (status, pitch_history, user_notes, assigned_to) are preserved across runs by the orchestrator's merge logic.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    brand: str = Field(..., description="Display name of the brand (e.g. 'Lululemon').")
    brand_id: str = Field(
        ...,
        description="Stable slug derived from `brand`. Used as the merge key across discovery runs. Matches the brand's canonical `name` in data/brand_industry_map.json after normalization (lowercase, kebab-case, suffixes stripped).",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    industry_id: str = Field(
        ...,
        description="Kebab-case slug that MUST match an `id` in data/industries.json.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    niche_signals: list[NicheSignal] | None = Field(
        None,
        description="Which of the talent's content_niches rolled this brand up. Helps the UI explain *why* this brand surfaced for this talent.",
    )
    score: float = Field(
        ...,
        description="Capped sum of source weights, normalised 0-1. Multi-source candidates hit the ceiling fast by design.",
        ge=0.0,
        le=1.0,
    )
    tier: Tier1 = Field(
        ...,
        description="Tier assignment based on score + presence of re-engagement source. Used to group the UI.",
    )
    found_in_searches: int = Field(
        ...,
        description="Count of distinct sources that surfaced this candidate this run. Denormalised from sources[].length for fast UI.",
        ge=1,
    )
    sources: list[Source] = Field(
        ...,
        description="Provenance: which of the 16 in-scope (or future-version) searches surfaced this brand, with the contribution weight and a free-form note explaining the match.",
        min_length=1,
    )
    brand_snapshot: BrandSnapshot | None = Field(
        None,
        description="Snapshotted enrichment fields from brand_industry_map.json at discovery time. Makes the candidate self-contained so downstream consumers don't need to re-resolve the brand.",
    )
    qualification: Qualification | None = None
    qualification_filtered: bool | None = Field(
        False,
        description="If true, qualification.score is below threshold (default 0.30). The UI hides these by default but they stay in the file for transparency and so a user can override.",
    )
    warnings: list[Warning] | None = Field(
        None,
        description="Policy-layer flags. Candidate stays in the list (unless `blocked: true`), UI surfaces these.",
    )
    blocked: bool | None = Field(
        False,
        description="Hard-excluded by the policy layer. Should not appear in `candidates[]` — gets moved to top-level `blocked[]`. Kept in the schema for symmetry so a partial extraction can carry the flag.",
    )
    blocked_reason: BlockedReason | None = Field(
        None,
        description="Reason category if blocked. Free-text explanation lives in `next_action_hint` or top-level `blocked[].details`.",
    )
    next_action_hint: str | None = Field(
        None,
        description="Free-text suggested next step for the UI. e.g. 'Re-engage with existing contact; reference last campaign performance' or 'Cold outreach; no prior contact'.",
    )
    status: Status = Field(
        "new",
        description="Workflow state. PRESERVED across discovery re-runs. Sync direction: pre-pitch states (`new`, `shortlisted`, `parked`) are user-driven and live here as source-of-truth. Post-pitch states (`pitched`, `responded`, `negotiating`, `closed_won`, `closed_lost`) are DENORMALISED from upstream canonical sources — the orchestrator updates them on state changes in (a) `pitch_enrollment` (pitched/responded transitions) and (b) Phase 4 `deal.stage` + `deal.is_won` / `is_terminal` (negotiating/closed_won/closed_lost). When this field disagrees with the canonical source, the canonical wins on next sync; this field is for fast UI rendering only.",
    )
    assigned_to: str | None = Field(
        None,
        description="FK to `agency_profile.agents[].agent_id` — agent responsible for moving this candidate forward. Null for unassigned. For agency roster views. v0.1 (single-agent constraint): typically auto-set to the primary agent; v2 multi-agent rosters use this for per-candidate assignment.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    legal_entity_override: LegalEntityOverride | None = Field(
        None,
        description="Per-talent override of `brand_industry_map.brands[].legal_entity` for this brand. Used when the talent/agency has reason to invoice a different legal entity than the canonical brand entity (e.g. brand subsidiary, distributor, agency-of-record). Captured opportunistically during proposal stage; absent = use the canonical entity from brand_industry_map. Same field shape as `brand_industry_map.brands[].legal_entity`.",
    )
    user_notes: str | None = Field(
        "", description="Free-form annotations from the user. Preserved across runs."
    )
    pitch_history: list[PitchHistoryEntry] | None = Field(
        None,
        description="Append-only log of outreach attempts. Populated by the Outreach phase (Phase 2). Preserved across discovery re-runs.",
    )
    first_surfaced_at: AwareDatetime = Field(
        ...,
        description="When this brand first appeared as a candidate for this talent. Set on creation, never modified.",
    )
    last_surfaced_at: AwareDatetime = Field(
        ...,
        description="Most recent discovery run that surfaced this brand. Updated on each run.",
    )
    last_seen_in_searches: list[str] | None = Field(
        None,
        description="Sources from the most recent run only. If this candidate exists in the file but `last_seen_in_searches` is empty, this brand dropped out of discovery this cycle — useful signal for stale-pipeline detection.",
    )


class BrandCandidatesFile(BaseModel):
    """
    Per-talent output of the Brand Discovery long-list generator (docs/brand_discovery.md). One file per talent under data/brand_candidates/current/{talent_id}.json (latest view; rewritten on each discovery run with workflow state preserved by merge) plus immutable per-run snapshots under data/brand_candidates/runs/{talent_id}/run_{date}.json. The folder is gitignored — generated artifact, not source.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: str | None = Field(None, alias="$schema")
    agency_id: UUID | None = Field(
        None,
        description="Multi-tenant scope: FK to agency_profile.agency_id. Optional in v0.1 (single-tenant deploys may omit); required in v2 SaaS. When present, all cross-record queries MUST filter by agency_id to prevent cross-tenant data leakage. See docs/data_lineage.md GAP-01/02 for rationale.",
    )
    talent_id: str = Field(
        ...,
        description="Slug matching the `id` in the source talents/{id}.json file.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    version: str = Field(
        ..., description="Schema version of this file. Bump when the shape changes."
    )
    generated_at: AwareDatetime = Field(..., description="Wall-clock time of this run.")
    search_run_id: str = Field(
        ...,
        description="Stable identifier for this discovery run. Used to correlate run metadata with the per-run snapshot file.",
    )
    candidates: list[Candidate] = Field(
        ...,
        description="Ranked brand candidates. Sorted by score descending then tier.",
    )
    blocked: list[BlockedBrand] | None = Field(
        None,
        description="Brands excluded by the policy layer (blocked industries, active exclusivities, do_not_recontact). Kept for transparency — the user can see what was filtered.",
    )
    stats: Stats | None = None
    run_metadata: RunMetadata | None = None
