# generated by datamodel-codegen:
#   filename:  contract_pack.schema.json
#   timestamp: 2026-05-27T21:00:44+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, EmailStr, Field


class Trigger(StrEnum):
    """
    agent_initiated_v1: first draft. agent_*regenerate: NL-feedback regen of various scopes. brand_redline_response: agent uploaded brand's redlined version + triggered regen targeting the redlined sections. amendment_request: post-execution amendment (writes to `deal.contract.amendment_log[]` instead of replacing the executed contract).
    """

    AGENT_INITIATED_V1 = "agent_initiated_v1"
    AGENT_FULL_REGENERATE = "agent_full_regenerate"
    AGENT_SECTION_REGENERATE = "agent_section_regenerate"
    AGENT_PER_CLAUSE_REGENERATE = "agent_per_clause_regenerate"
    BRAND_REDLINE_RESPONSE = "brand_redline_response"
    AMENDMENT_REQUEST = "amendment_request"


class PassName(StrEnum):
    CONTEXT_ARTEFACT_SUMMARIZE = "context_artefact_summarize"
    MERGE_FIELD_EXTRACT = "merge_field_extract"
    CLAUSE_EVALUATE = "clause_evaluate"
    NARRATIVE_DRAFT = "narrative_draft"
    COMPOSE = "compose"
    SECTION_REGEN = "section_regen"
    CLAUSE_REGEN = "clause_regen"


class LlmPass(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pass_name: PassName
    model: str | None = None
    input_tokens: int = Field(..., ge=0)
    output_tokens: int = Field(..., ge=0)
    cached_tokens: int | None = Field(None, ge=0)
    cost_usd: float | None = Field(None, ge=0.0)
    duration_ms: int | None = Field(None, ge=0)


class Generation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trigger: Trigger = Field(
        ...,
        description="agent_initiated_v1: first draft. agent_*regenerate: NL-feedback regen of various scopes. brand_redline_response: agent uploaded brand's redlined version + triggered regen targeting the redlined sections. amendment_request: post-execution amendment (writes to `deal.contract.amendment_log[]` instead of replacing the executed contract).",
    )
    pre_generation_guidance: str | None = Field(
        None,
        description="Free-text guidance from the agent before generation. e.g. 'Brand mentioned in call they have strict NDAs — make sure confidentiality clause is comprehensive.'",
    )
    regeneration_feedback: str | None = Field(
        None, description="NL feedback on parent_version. Populated when version > 1."
    )
    target_sections: list[str] | None = Field(
        None,
        description="For section/per-clause regen: which sections were rebuilt. e.g. ['merge_field_values', 'conditional_clause_decisions.gdpr', 'narrative_sections.scope_of_work'].",
    )
    amendment_log_entry_ref: AwareDatetime | None = Field(
        None,
        description="If trigger=amendment_request: ISO-timestamp matching the `deal.contract.amendment_log[].at` entry this version documents. Closes the bidirectional link with `amendment_log[].contract_pack_version` (parallel to negotiation_log_entry_ref on proposal_pack).",
    )
    generated_at: AwareDatetime
    generated_by_agent_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    llm_model: str
    llm_passes: list[LlmPass] | None = None


class BrandLegalEntityAtGen(BaseModel):
    """
    Brand's legal entity info as known at generation time. Often provided via context_artefacts (agent-uploaded W-9 / company registration / etc.).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    legal_name: str | None = None
    entity_type: str | None = Field(
        None, description="e.g. 'Delaware C-Corp', 'UK Limited', 'GmbH'."
    )
    registered_address: str | None = None
    country: str | None = Field(None, description="ISO 3166-1 alpha-2.")
    tax_id: str | None = None
    signatory_name: str | None = Field(
        None,
        description="Person signing on behalf of the brand. Often different from primary_contact.",
    )
    signatory_title: str | None = None
    signatory_email: EmailStr | None = None


class ContextSnapshot(BaseModel):
    """
    Frozen upstream context this version was generated from. If the talent template or deal data evolves, this version stays anchored.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    captured_at: AwareDatetime
    template_version_used: str | None = Field(
        None,
        description="Value of `talent.contract_template.template_version` at generation time. Anchors this pack to the template version it used — template updates don't retroactively change historic packs.",
    )
    talent_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    talent_billing_entity_snapshot: dict[str, Any] | None = Field(
        None,
        description="Frozen snapshot of `talent.billing_entity` at generation time. Legal-name changes don't break old contracts.",
    )
    proposal_pack_id_at_gen: str | None = Field(
        None,
        description="Which proposal pack version provided the canonical commercial values consumed.",
        pattern="^pp_[a-z0-9_-]+_v[0-9]+$",
    )
    discovery_debrief_snapshot: dict[str, Any] | None = Field(
        None,
        description="Frozen copy of `deal.lead.discovery_debrief` at generation time. Informs conditional clause evaluation.",
    )
    brand_legal_entity_at_gen: BrandLegalEntityAtGen | None = Field(
        None,
        description="Brand's legal entity info as known at generation time. Often provided via context_artefacts (agent-uploaded W-9 / company registration / etc.).",
    )
    comparable_contracts_referenced: list[str] | None = Field(
        None,
        description="FKs to context_artefacts of prior contracts with this brand (or similar brands). Helps the LLM mirror prior conventions where appropriate.",
    )


class Source(StrEnum):
    """
    Which source the value came from. `default` = fell back to merge_field_definitions[].default. `agent_input` = agent provided directly (typically brand legal info).
    """

    TALENT_PROFILE = "talent_profile"
    TALENT_BILLING_ENTITY = "talent_billing_entity"
    TALENT_WORKING_TERMS = "talent_working_terms"
    AGENCY_PROFILE = "agency_profile"
    DEAL_PROPOSAL = "deal_proposal"
    DISCOVERY_DEBRIEF = "discovery_debrief"
    CONTEXT_ARTEFACT = "context_artefact"
    AGENT_INPUT = "agent_input"
    COMPUTED = "computed"
    DEFAULT = "default"


class Confidence(StrEnum):
    """
    high: deterministic extraction (e.g. fee_usd from deal.proposal). medium: LLM-inferred with strong signal. low: LLM guess. missing: no value found, needs_review flag set.
    """

    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    MISSING = "missing"


class MergeFieldValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field: str = Field(
        ..., description="Matches the merge_field_definitions[].field name."
    )
    value: Any | None = Field(
        None,
        description="Extracted/computed/agent-supplied value. Type varies — string, number, date.",
    )
    source: Source = Field(
        ...,
        description="Which source the value came from. `default` = fell back to merge_field_definitions[].default. `agent_input` = agent provided directly (typically brand legal info).",
    )
    source_path: str | None = Field(
        None,
        description="Specific path within source (e.g. 'billing_entity.legal_name').",
    )
    confidence: Confidence | None = Field(
        None,
        description="high: deterministic extraction (e.g. fee_usd from deal.proposal). medium: LLM-inferred with strong signal. low: LLM guess. missing: no value found, needs_review flag set.",
    )
    needs_review: bool | None = Field(
        False,
        description="If true, blocks legal review gate until agent reviews + confirms. Auto-set for low/missing confidence on required fields.",
    )
    agent_overridden: bool | None = Field(
        False, description="True if agent edited LLM-extracted value."
    )
    agent_override_note: str | None = None


class Decision(StrEnum):
    INCLUDE = "include"
    EXCLUDE = "exclude"


class DecidedBy(StrEnum):
    """
    How the decision was reached. template_default: rule had default_decision=include/exclude. llm: rule had llm_decide and Stage C evaluated. agent: agent overrode the LLM decision.
    """

    TEMPLATE_DEFAULT = "template_default"
    LLM = "llm"
    AGENT = "agent"


class ConditionalClauseDecision(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    clause_id: str = Field(
        ..., description="Matches `clause_applicability_rules[].clause_id`."
    )
    decision: Decision
    decided_by: DecidedBy | None = Field(
        None,
        description="How the decision was reached. template_default: rule had default_decision=include/exclude. llm: rule had llm_decide and Stage C evaluated. agent: agent overrode the LLM decision.",
    )
    applicability_rationale: str | None = Field(
        None,
        description="LLM's explanation for the decision. Cites which context signals drove inclusion/exclusion.",
    )
    agent_overridden: bool | None = False
    agent_override_note: str | None = None


class NarrativeSection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    placeholder: str = Field(
        ..., description="Matches narrative_placeholders[].placeholder name."
    )
    content: str = Field(..., description="LLM-drafted markdown content.")
    sources: list[str] | None = Field(
        None,
        description="Which context paths the LLM drew from (e.g. 'deal.proposal.deliverables[0..2]', 'discovery_debrief.objectives_heard[1]').",
    )
    word_count: int | None = Field(None, ge=0)
    agent_edited: bool | None = False
    agent_edited_at: AwareDatetime | None = None


class Category(StrEnum):
    MERGE_FIELD = "merge_field"
    CLAUSE_DECISION = "clause_decision"
    NARRATIVE_SECTION = "narrative_section"
    AGENT_FLAGGED = "agent_flagged"


class BlockingIssue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    category: Category
    field_or_id: str
    issue: str
    resolved_at: AwareDatetime | None = None


class PreviousApproval(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    approved_at: AwareDatetime
    approved_by_agent_id: str = Field(..., pattern="^[a-z0-9][a-z0-9-]*$")
    approval_notes: str | None = None
    reset_at: AwareDatetime
    reset_reason: str | None = Field(
        None,
        description="What edit triggered the reset (e.g. 'agent edited merge_field fee_usd', 'narrative scope_of_work regenerated').",
    )


class LegalReview(BaseModel):
    """
    The HARD LEGAL REVIEW GATE. Word + PDF artefacts cannot render until approved_at is set. Any edit post-approval resets the gate (re-approval required) unless trivial_edit_override is true.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    required: bool = Field(
        True,
        description="v0.1: always true. v0.2 if agency-configurable gate is added, agencies can opt out.",
    )
    reviewer_id: str | None = Field(
        None,
        description="Defaulted from talent.contract_template.legal_reviewer_id (if set) or deal.assigned_agent_id. Only this identity can approve.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    blocking_issues: list[BlockingIssue] | None = Field(
        None,
        description="Automatically populated: merge_field_values entries where needs_review=true OR required field is missing/low-confidence; clause_decisions agent has flagged for re-evaluation; narrative sections agent has flagged. Gate cannot pass with non-empty blocking_issues.",
    )
    approved_at: AwareDatetime | None = Field(
        None,
        description="When the reviewer passed the gate. ABSENT = Word + PDF artefacts blocked. Setting this enables Stage G render.",
    )
    approved_by_agent_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    approval_notes: str | None = Field(
        None,
        description="Optional notes captured at approval (e.g. 'reviewed by external counsel; minor wording change on indemnification — see edit log').",
    )
    previous_approvals: list[PreviousApproval] | None = Field(
        None,
        description="If edits reset the gate, prior approvals are pushed here as an audit trail. Each entry is the prior {approved_at, approved_by_agent_id, approval_notes} + the timestamp the approval was reset + reset_reason.",
    )


class Type(StrEnum):
    CONTRACT_MD = "contract_md"
    CONTRACT_DOCX = "contract_docx"
    CONTRACT_PDF = "contract_pdf"


class Status(StrEnum):
    RENDERED = "rendered"
    PENDING = "pending"
    FAILED = "failed"
    BLOCKED_BY_LEGAL_GATE = "blocked_by_legal_gate"


class RenderedBy(StrEnum):
    MARKDOWN_WRITER = "markdown_writer"
    PYTHON_DOCX = "python_docx"
    PUPPETEER_PDF = "puppeteer_pdf"
    PANDOC = "pandoc"


class ExportArtifact(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type
    status: Status
    path: str | None = None
    size_bytes: int | None = Field(None, ge=0)
    rendered_at: AwareDatetime | None = None
    rendered_by: RenderedBy | None = None
    error: str | None = None


class EditType(StrEnum):
    MERGE_FIELD_OVERRIDE = "merge_field_override"
    CLAUSE_DECISION_OVERRIDE = "clause_decision_override"
    NARRATIVE_SECTION_EDIT = "narrative_section_edit"
    COMPOSED_MARKDOWN_EDIT = "composed_markdown_edit"
    CONTEXT_ARTEFACT_RETAG = "context_artefact_retag"
    CONTEXT_ARTEFACT_EXCLUDE = "context_artefact_exclude"
    BRAND_LEGAL_ENTITY_UPDATE = "brand_legal_entity_update"


class AgentEdit(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    edit_id: str = Field(..., pattern="^edit_[a-z0-9]+$")
    edited_at: AwareDatetime
    edited_by_agent_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    edit_type: EditType
    target: str = Field(
        ...,
        description="What was edited. e.g. 'merge_field_values[fee_usd]', 'conditional_clause_decisions[gdpr]', 'narrative_sections[scope_of_work]'.",
    )
    before_excerpt: str | None = None
    after_excerpt: str | None = None
    resets_legal_gate: bool | None = Field(
        True,
        description="Most edits reset the gate. Trivial edits (whitespace, typo) can be flagged to NOT reset — agent decides at edit time.",
    )
    trivial_edit_override: bool | None = Field(
        False,
        description="If true, edit does NOT reset legal_review.approved_at. Agent must explicitly mark trivial.",
    )


class Type3(StrEnum):
    """
    brand_legal_info: W-9, company registration, corporate structure documents. brand_requested_clauses: specific clauses the brand has asked be included. prior_contract: previous executed contract with this brand (for convention matching). brand_redline / talent_redline: redlined versions received during review.
    """

    BRAND_LEGAL_INFO = "brand_legal_info"
    BRAND_REQUESTED_CLAUSES = "brand_requested_clauses"
    PRIOR_CONTRACT = "prior_contract"
    BRAND_REDLINE = "brand_redline"
    TALENT_REDLINE = "talent_redline"
    REFERENCE_MATERIAL = "reference_material"
    OTHER = "other"


class Role(StrEnum):
    PRIMARY_INPUT = "primary_input"
    SUPPLEMENTARY = "supplementary"
    REFERENCE = "reference"


class Parser(StrEnum):
    PYPDF = "pypdf"
    PYTHON_DOCX = "python_docx"
    TEXT_READER = "text_reader"
    EXTERNAL_URL = "external_url"


class RelevanceTag(StrEnum):
    CORE = "core"
    CONTEXT = "context"
    LOW = "low"
    DROP = "drop"


class ContextArtefact(BaseModel):
    """
    Same shape as proposal_pack.context_artefact, with contract-specific type enum values.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    artefact_id: str = Field(..., pattern="^ctx_[a-z0-9]+$")
    type: Type3 = Field(
        ...,
        description="brand_legal_info: W-9, company registration, corporate structure documents. brand_requested_clauses: specific clauses the brand has asked be included. prior_contract: previous executed contract with this brand (for convention matching). brand_redline / talent_redline: redlined versions received during review.",
    )
    role: Role | None = "primary_input"
    original_filename: str
    stored_filepath: str | None = None
    mime_type: str | None = None
    size_bytes: int | None = Field(None, ge=0)
    uploaded_at: AwareDatetime
    uploaded_by_agent_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    parser: Parser
    parsed_text: str | None = None
    parsed_text_length: int | None = Field(None, ge=0)
    external_url: AnyUrl | None = None
    llm_summary: str | None = None
    llm_extracted_signals: dict[str, Any] | None = Field(
        None,
        description="Optional structured extraction (e.g. brand_legal_info → legal_name, registered_address, tax_id, signatory).",
    )
    relevance_tag: RelevanceTag | None = "core"
    include_in_generation: bool | None = True


class ContractPack(BaseModel):
    """
    Phase 4.7 — a versioned contract draft generated from the talent's contract template (Phase 1 onboarding) + the deal's confirmed proposal commercials (Phase 4.6) + agent-uploaded brand legal info. 7-stage pipeline: context augmentation → merge field extraction → conditional clause evaluation → narrative drafting → composition → HARD LEGAL REVIEW GATE → render. Output: markdown source (canonical) + Word .docx (editable) + PDF (read-only). Existing `deal.contract.draft_contract_attachment_id` and `contract_attachment_id` auto-populate from the latest contract pack render. Stored at `data/deals/{deal_id}/contract_packs/v{N}.json` (gitignored). See `docs/contract_pack_workflow.md`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: str | None = Field(None, alias="$schema")
    agency_id: UUID | None = Field(
        None,
        description="Multi-tenant scope: FK to agency_profile.agency_id. Optional in v0.1 (single-tenant deploys may omit); required in v2 SaaS. When present, all cross-record queries MUST filter by agency_id to prevent cross-tenant data leakage. See docs/data_lineage.md GAP-01/02 for rationale.",
    )
    contract_pack_id: str = Field(
        ...,
        description="Globally unique identifier. Format: `cp_{deal_id_short}_v{N}`. The `cp_` prefix distinguishes from prep packs (`prep_*`) and proposal packs (`pp_*`).",
        pattern="^cp_[a-z0-9_-]+_v[0-9]+$",
    )
    deal_id: str = Field(
        ...,
        description="FK to the Phase 4 deal. The deal's `contract.contract_pack_ids[]` array references all versions; `contract.latest_contract_pack_id` points to the current `is_latest: true` version.",
        pattern="^deal_pipeline_[a-z0-9_-]+$",
    )
    version: int = Field(..., ge=1)
    parent_version: int | None = Field(None, ge=1)
    is_latest: bool
    generation: Generation
    context_snapshot: ContextSnapshot = Field(
        ...,
        description="Frozen upstream context this version was generated from. If the talent template or deal data evolves, this version stays anchored.",
    )
    context_artefacts: list[ContextArtefact] | None = Field(
        None,
        description="Files uploaded by the agent in Stage A — brand legal info, brand-requested clauses, prior contracts. Same shape as `proposal_pack.context_artefacts` (parser metadata, parsed_text, llm_summary, relevance_tag).",
    )
    merge_field_values: list[MergeFieldValue] = Field(
        ...,
        description="Every merge field declared in `talent.contract_template.merge_field_definitions[]`, with extracted/agent-supplied value + provenance + confidence. Stage B output. Critical fields (legal names, fees, dates) with low confidence or missing values block the legal review gate.",
    )
    conditional_clause_decisions: list[ConditionalClauseDecision] = Field(
        ...,
        description="Per-conditional-block decision from Stage C. Each entry covers one `{{#if clause_id}}...{{/if}}` block in the template.",
    )
    narrative_sections: list[NarrativeSection] = Field(
        ...,
        description="LLM-drafted content for each `{{narrative_*}}` placeholder declared in `talent.contract_template.narrative_placeholders[]`. Stage D output.",
    )
    composed_markdown: str | None = Field(
        None,
        description="The final composed contract — template markdown_source with all merge fields substituted, conditional blocks resolved (included blocks kept verbatim, excluded blocks stripped), narrative placeholders filled. Stage E output. This is the canonical source-of-truth that the Word and PDF artefacts render from. Agent direct edits update this string + log to agent_edits[]; subsequent renders regenerate Word + PDF from the updated source.",
    )
    legal_review: LegalReview = Field(
        ...,
        description="The HARD LEGAL REVIEW GATE. Word + PDF artefacts cannot render until approved_at is set. Any edit post-approval resets the gate (re-approval required) unless trivial_edit_override is true.",
    )
    export_artifacts: list[ExportArtifact] | None = None
    agent_edits: list[AgentEdit] | None = Field(
        None,
        description="Append-only audit log of direct edits (no LLM regen). Edits that change merge field values / clause decisions / narrative content / composed markdown reset the legal review gate (push current approval to previous_approvals[]).",
    )
    created_at: AwareDatetime
    updated_at: AwareDatetime | None = None
