# generated by datamodel-codegen:
#   filename:  deal.schema.json
#   timestamp: 2026-06-01T11:52:22+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class AdditionalContactId(RootModel[str]):
    root: str = Field(..., pattern="^[a-z0-9][a-z0-9-]*$")


class OriginatingDecisionRoleAtPitch(StrEnum):
    """
    Snapshot of `brand_contact.decision_role` at the time the originating pitch went out. Captured here on deal creation (vs reading from contact record live) because the contact's role may evolve (promotions, role changes) and we want to anchor 'won-deal-by-decision-role' analytics to the role at pitch time. Powers cross-cuts like 'we win more deals when champion is the originating contact'.
    """

    BUYER = "buyer"
    INFLUENCER = "influencer"
    GATEKEEPER = "gatekeeper"
    CHAMPION = "champion"
    UNKNOWN = "unknown"


class Stage(StrEnum):
    """
    Top-level lifecycle stage. `archived` is the post-close terminal state after auto-archive into Phase 1.5 brand_deals.
    """

    LEAD = "lead"
    PROPOSAL = "proposal"
    CONTRACT = "contract"
    DELIVERY = "delivery"
    CLOSE = "close"
    ARCHIVED = "archived"


class Substage(StrEnum):
    """
    Granular state within (or terminal-state outside of) the current stage. Transition validity is enforced by the orchestrator per the state machine in docs/deal_lifecycle_workflow.md.
    """

    NEW_LEAD = "new_lead"
    INITIAL_CALL_SCHEDULED = "initial_call_scheduled"
    INITIAL_CALL_COMPLETED = "initial_call_completed"
    BRIEF_RECEIVED = "brief_received"
    QUALIFIED = "qualified"
    DISQUALIFIED = "disqualified"
    PROPOSAL_DRAFTING = "proposal_drafting"
    PROPOSAL_SENT = "proposal_sent"
    UNDER_REVIEW = "under_review"
    NEGOTIATION = "negotiation"
    TERMS_AGREED = "terms_agreed"
    CONTRACT_DRAFTING = "contract_drafting"
    CONTRACT_IN_REVIEW_BRAND = "contract_in_review_brand"
    CONTRACT_IN_REVIEW_TALENT = "contract_in_review_talent"
    CONTRACT_REVISIONS = "contract_revisions"
    CONTRACT_EXECUTED = "contract_executed"
    CONTRACT_FAILED = "contract_failed"
    PRE_PRODUCTION = "pre_production"
    CONTENT_IN_PRODUCTION = "content_in_production"
    PENDING_BRAND_APPROVAL = "pending_brand_approval"
    REVISIONS_REQUESTED = "revisions_requested"
    APPROVED_FOR_POSTING = "approved_for_posting"
    LIVE = "live"
    PERFORMANCE_WINDOW = "performance_window"
    INVOICE_SENT = "invoice_sent"
    INVOICE_PAID = "invoice_paid"
    POST_CAMPAIGN_REPORTING = "post_campaign_reporting"
    ARCHIVED = "archived"
    LOST = "lost"
    KILLED = "killed"
    PAUSED = "paused"


class StageHistoryItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    stage: str
    substage: str
    at: AwareDatetime
    by_agent_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    note: str | None = Field(None, description="Optional context on the transition.")


class Reason(StrEnum):
    """
    budget: brand insufficient budget; timing: schedule didn't work; competitor_won: brand picked another creator; internal_pivot: brand strategy changed; talent_no_fit: talent declined; terms_disagreed: couldn't agree on usage rights/exclusivity/etc; unresponsive: went dark; compliance_block: values/red-lines conflict; other: free-text.
    """

    BUDGET = "budget"
    TIMING = "timing"
    COMPETITOR_WON = "competitor_won"
    INTERNAL_PIVOT = "internal_pivot"
    TALENT_NO_FIT = "talent_no_fit"
    TERMS_DISAGREED = "terms_disagreed"
    UNRESPONSIVE = "unresponsive"
    COMPLIANCE_BLOCK = "compliance_block"
    OTHER = "other"


class LostAtStage(StrEnum):
    """
    Which stage we were in when the deal went sideways.
    """

    LEAD = "lead"
    PROPOSAL = "proposal"
    CONTRACT = "contract"
    DELIVERY = "delivery"


class Loss(BaseModel):
    """
    Populated only when substage is `lost`, `killed`, `disqualified`, or `contract_failed`. Captures structured loss-reason for funnel analytics.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    reason: Reason = Field(
        ...,
        description="budget: brand insufficient budget; timing: schedule didn't work; competitor_won: brand picked another creator; internal_pivot: brand strategy changed; talent_no_fit: talent declined; terms_disagreed: couldn't agree on usage rights/exclusivity/etc; unresponsive: went dark; compliance_block: values/red-lines conflict; other: free-text.",
    )
    at: AwareDatetime
    by_agent_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    notes: str | None = Field(
        None, description="Free-text detail on the loss circumstances."
    )
    competitor_brand: str | None = Field(
        None, description="If reason=competitor_won, who won."
    )
    lost_at_stage: LostAtStage | None = Field(
        None, description="Which stage we were in when the deal went sideways."
    )


class QualificationDecision(StrEnum):
    QUALIFIED = "qualified"
    DISQUALIFIED = "disqualified"
    PENDING = "pending"


class DiscoveryPrepPackId(RootModel[str]):
    root: str = Field(..., pattern="^prep_[a-z0-9_-]+_v[0-9]+$")


class ExtractedFromArtefactId(RootModel[str]):
    root: str = Field(..., pattern="^ctx_[a-z0-9]+$")


class Confidence(StrEnum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class BudgetSignal(BaseModel):
    """
    Budget hints from the call. Numeric range optional — sometimes only qualitative signal ('flexible', 'tight') is captured.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    statement: str | None = None
    confidence: Confidence | None = None
    range_usd_low: float | None = Field(None, ge=0.0)
    range_usd_high: float | None = Field(None, ge=0.0)


class DecisionProcess(BaseModel):
    """
    Who else needs to weigh in + how + when.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    stakeholders: list[str] | None = Field(
        None,
        description="Roles or names of other approvers (legal, finance, CMO, etc.).",
    )
    process_description: str | None = None
    timeline: str | None = None
    confidence: Confidence | None = None


class AgentEditsPostExtractionItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    edited_at: AwareDatetime
    field: str
    from_: Any = Field(..., alias="from")
    to: Any
    note: str | None = None


class ProposalPackId(RootModel[str]):
    root: str = Field(..., pattern="^pp_[a-z0-9_-]+_v[0-9]+$")


class Platform(StrEnum):
    INSTAGRAM = "instagram"
    TIKTOK = "tiktok"
    YOUTUBE = "youtube"
    TWITTER_X = "twitter_x"
    LINKEDIN = "linkedin"
    PINTEREST = "pinterest"
    TWITCH = "twitch"
    SNAPCHAT = "snapchat"
    FACEBOOK = "facebook"
    SUBSTACK = "substack"
    PODCAST = "podcast"
    OTHER = "other"


class Format(StrEnum):
    REEL = "reel"
    STORY = "story"
    FEED_POST = "feed_post"
    CAROUSEL = "carousel"
    LIVE = "live"
    VIDEO_LONG_FORM = "video_long_form"
    VIDEO_SHORT = "video_short"
    PODCAST_EPISODE = "podcast_episode"
    PODCAST_READ = "podcast_read"
    NEWSLETTER = "newsletter"
    TWEET_THREAD = "tweet_thread"
    LINKEDIN_POST = "linkedin_post"
    APPEARANCE = "appearance"
    CO_CREATED_PRODUCT = "co_created_product"
    OTHER = "other"


class Deliverable(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    platform: Platform
    format: Format
    count: int = Field(..., ge=1)


class UsageRightsGrantedEnum(StrEnum):
    ORGANIC = "organic"
    WHITELISTING_30D = "whitelisting_30d"
    WHITELISTING_60D = "whitelisting_60d"
    WHITELISTING_90D = "whitelisting_90d"
    WHITELISTING_UNLIMITED = "whitelisting_unlimited"
    PAID_SOCIAL_30D = "paid_social_30d"
    PAID_SOCIAL_90D = "paid_social_90d"
    PAID_SOCIAL_PERPETUAL = "paid_social_perpetual"
    WEBSITE_USE = "website_use"
    BROADCAST = "broadcast"
    PRINT = "print"
    PERPETUAL_ALL_CHANNELS = "perpetual_all_channels"


class Exclusivity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    category: str | None = None
    duration_days: int | None = Field(None, ge=0)


class Type(StrEnum):
    GIFTED_PRODUCT = "gifted_product"
    COMPED_EVENT = "comped_event"
    COMPED_TRAVEL = "comped_travel"
    EQUITY = "equity"
    DISCOUNT_CODE = "discount_code"
    OTHER = "other"


class AdditionalCompensationItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type
    value_usd: float | None = Field(None, ge=0.0)
    description: str | None = None


class Direction(StrEnum):
    SENT_TO_BRAND = "sent_to_brand"
    RECEIVED_FROM_BRAND = "received_from_brand"
    INTERNAL_DECISION = "internal_decision"


class Channel(StrEnum):
    EMAIL = "email"
    CALL = "call"
    MEETING = "meeting"
    MESSAGE = "message"
    OTHER = "other"


class NegotiationLogItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    at: AwareDatetime
    direction: Direction
    channel: Channel | None = None
    summary: str
    terms_changed: str | None = Field(
        None,
        description="Description of what changed in the proposal as a result of this exchange.",
    )
    attachment_ids: list[str] | None = None
    proposal_pack_version: int | None = Field(
        None,
        description="Which proposal pack version this negotiation event refers to. For `received_from_brand` entries: the version they pushed back on. For `sent_to_brand` entries: the version that was sent. Forms the bidirectional link with `proposal_pack.generation.negotiation_log_entry_ref`.",
        ge=1,
    )


class ProposalStage(BaseModel):
    """
    Captured during PROPOSAL stage. Mirrors brand_deal.deliverables/commercials shape — when archived, these fields carry into the brand_deal record. Generated by the Phase 4.6 proposal pack pipeline (`docs/proposal_pack_workflow.md`): the LLM proposes commercials, the agent confirms (passing the commercial gate), and confirmed values write into the fields below. `proposal_pack_ids[]` references all versions of the proposal pack generated for this deal.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    proposal_pack_ids: list[ProposalPackId] | None = Field(
        None,
        description="FK list to all versions of the proposal pack generated for this deal (Phase 4.6). Each version is a file at `data/deals/{deal_id}/proposal_packs/v{N}.json`. Append-only — v1, v2, v3... all retained as history including negotiation-response regens.",
    )
    latest_proposal_pack_id: str | None = Field(
        None,
        description="Pointer to the current `is_latest: true` proposal pack version.",
        pattern="^pp_[a-z0-9_-]+_v[0-9]+$",
    )
    commercial_confirmed_at: AwareDatetime | None = Field(
        None,
        description="When the agent passed the Phase 4.6 commercial gate — confirmed the LLM-proposed deliverables + fee + usage_rights + exclusivity etc. Setting this triggers slide generation. The commercial fields below (deliverables, fee_usd, etc.) are populated from the confirmed values.",
    )
    commercial_confirmed_by_agent_id: str | None = Field(
        None, pattern="^[a-z0-9][a-z0-9-]*$"
    )
    proposal_attachment_id: str | None = Field(
        None,
        description="FK to attachments[] for the formal proposal PDF — typically the leave-behind PDF from the latest proposal pack version.",
    )
    proposal_sent_at: AwareDatetime | None = None
    deliverables: list[Deliverable] | None = None
    fee_usd: float | None = Field(None, ge=0.0)
    fee_currency_original: str | None = Field(None, pattern="^[A-Z]{3}$")
    fee_original_amount: float | None = Field(None, ge=0.0)
    usage_rights_granted: list[UsageRightsGrantedEnum] | None = None
    exclusivity: Exclusivity | None = None
    additional_compensation: list[AdditionalCompensationItem] | None = None
    negotiation_log: list[NegotiationLogItem] | None = Field(
        None,
        description="Chronological back-and-forth during negotiation. Each entry bidirectionally links to a Phase 4.6 proposal pack version: `proposal_pack_version` captures which version this pushback was on; the responding proposal pack version's `generation.negotiation_log_entry_ref` (an ISO timestamp matching `at`) points back here. Closes the audit loop between negotiation events and proposal artefacts.",
    )
    terms_agreed_at: AwareDatetime | None = None
    agreed_final_terms_summary: str | None = Field(
        None,
        description="One-paragraph summary of what got verbally agreed at terms_agreed transition. The legal contract written in CONTRACT stage should match this.",
    )


class ContractPackId(RootModel[str]):
    root: str = Field(..., pattern="^cp_[a-z0-9_-]+_v[0-9]+$")


class ESignProvider(StrEnum):
    """
    v0.1: manual (PDF upload + dates tracked). v2: API integration with the chosen provider auto-populates signed_at fields and the contract_attachment_id.
    """

    MANUAL = "manual"
    DOCUSIGN = "docusign"
    PANDADOC = "pandadoc"
    HELLOSIGN = "hellosign"
    OTHER = "other"


class AmendmentLogItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    at: AwareDatetime
    summary: str
    attachment_id: str | None = None
    contract_pack_version: int | None = Field(
        None,
        description="Version number of the contract_pack generated with `trigger: amendment_request` to document this amendment. Forms the bidirectional link with `contract_pack.generation.amendment_log_entry_ref`.",
        ge=1,
    )


class ContractStage(BaseModel):
    """
    Captured during CONTRACT stage. Drafts are generated by the Phase 4.7 contract pack pipeline (`docs/contract_pack_workflow.md`) from the talent's contract template + the deal's confirmed proposal commercials. v0.1: manual PDF + dates after auto-generation. v2: DocuSign/PandaDoc/HelloSign integration via API.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contract_pack_ids: list[ContractPackId] | None = Field(
        None,
        description="FK list to all versions of the Phase 4.7 contract pack. Each version is a file at `data/deals/{deal_id}/contract_packs/v{N}.json`. Append-only — v1, v2, v3... all retained including brand-redline-response regens.",
    )
    latest_contract_pack_id: str | None = Field(
        None,
        description="Pointer to current `is_latest: true` contract pack version.",
        pattern="^cp_[a-z0-9_-]+_v[0-9]+$",
    )
    legal_reviewer_id: str | None = Field(
        None,
        description="Identity authorised to pass the Phase 4.7 hard legal review gate. Defaults to `talent.contract_template.legal_reviewer_id` if set; otherwise defaults to `deal.assigned_agent_id`. Captured here at deal level so per-deal overrides are possible (e.g. specific deal goes to external counsel).",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    contract_attachment_id: str | None = Field(
        None,
        description="FK to attachments[] for the final signed PDF. v0.1: agent uploads after both sides sign. v2: e-sign provider auto-populates.",
    )
    draft_contract_attachment_id: str | None = Field(
        None,
        description="Pre-signature draft PDF. Auto-populated from the latest contract pack's rendered PDF on Stage G render (after legal review gate passed). Updated each time a new contract pack version is rendered.",
    )
    e_sign_provider: ESignProvider | None = Field(
        "manual",
        description="v0.1: manual (PDF upload + dates tracked). v2: API integration with the chosen provider auto-populates signed_at fields and the contract_attachment_id.",
    )
    e_sign_envelope_id: str | None = Field(
        None, description="Provider's identifier for the e-sign envelope. v2."
    )
    contract_drafting_started_at: AwareDatetime | None = None
    sent_to_brand_for_review_at: AwareDatetime | None = None
    sent_to_talent_for_review_at: AwareDatetime | None = None
    talent_signed_at: AwareDatetime | None = None
    brand_signed_at: AwareDatetime | None = None
    contract_executed_at: AwareDatetime | None = Field(
        None,
        description="When BOTH sides have signed. This is the moment legally + the moment delivery can begin.",
    )
    amendment_log: list[AmendmentLogItem] | None = Field(
        None,
        description="Post-execution amendments (scope changes, extensions). Each entry is bidirectionally linked to a Phase 4.7 contract pack version generated with `trigger: amendment_request`: `contract_pack_version` here captures which version documented the amendment; the responding contract pack's `generation` block captures the amendment event timestamp. Closes the audit loop between amendment events and contract artefacts (parallel to `proposal.negotiation_log[].proposal_pack_version`).",
    )


class BrandReviewStatus(StrEnum):
    PENDING = "pending"
    APPROVED = "approved"
    REVISIONS_REQUESTED = "revisions_requested"
    REJECTED = "rejected"


class ContentDraft(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    deliverable_ref: str = Field(
        ...,
        description="Reference to which entry in `proposal.deliverables[]` this is (e.g. 'instagram-reel-1').",
    )
    version: int = Field(..., ge=1)
    draft_attachment_id: str | None = None
    draft_url: AnyUrl | None = Field(None, description="Optional external preview URL.")
    submitted_at: AwareDatetime
    brand_review_status: BrandReviewStatus
    brand_review_at: AwareDatetime | None = None
    brand_review_notes: str | None = None


class Method(StrEnum):
    """
    meta_graph_auto/tiktok_api_auto: v0.1 direct API detection. phyllo_auto: v2 via Phyllo. agent_confirmed_suggestion: API suggested + agent confirmed. manual_url_entry: agent (or talent) entered URL directly (typical for platforms without v0.1 API coverage).
    """

    META_GRAPH_AUTO = "meta_graph_auto"
    TIKTOK_API_AUTO = "tiktok_api_auto"
    PHYLLO_AUTO = "phyllo_auto"
    AGENT_CONFIRMED_SUGGESTION = "agent_confirmed_suggestion"
    MANUAL_URL_ENTRY = "manual_url_entry"
    TALENT_SELF_REPORTED = "talent_self_reported"


class MatchSignal(StrEnum):
    TIME_WINDOW = "time_window"
    BRAND_HANDLE = "brand_handle"
    CAMPAIGN_HASHTAG = "campaign_hashtag"
    CONTENT_TYPE = "content_type"


class PostedDetection(BaseModel):
    """
    Provenance for how this post was matched to the expected deliverable. Surfaced to the agent in UI so the confirmation decision is informed.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    method: Method | None = Field(
        None,
        description="meta_graph_auto/tiktok_api_auto: v0.1 direct API detection. phyllo_auto: v2 via Phyllo. agent_confirmed_suggestion: API suggested + agent confirmed. manual_url_entry: agent (or talent) entered URL directly (typical for platforms without v0.1 API coverage).",
    )
    detected_at: AwareDatetime | None = Field(
        None, description="When the cron first surfaced the candidate."
    )
    match_score: int | None = Field(
        None,
        description="Confidence 0-100. ≥80 = strong auto-suggest; 50-79 = weak suggest with flag; <50 = log only.",
        ge=0,
        le=100,
    )
    match_signals: list[MatchSignal] | None = Field(
        None,
        description="Which signals contributed to the match score. Helps agent + audit understand why this post was suggested.",
    )
    candidate_post_ids_considered: list[str] | None = Field(
        None,
        description="Other candidate post IDs the cron considered but didn't suggest. Captured for audit + debugging (why did we suggest this one vs that one?).",
    )
    agent_confirmed_at: AwareDatetime | None = None
    agent_confirmed_by: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    agent_rejection_note: str | None = Field(
        None,
        description="If agent rejected an auto-suggestion, why. Helps tune the matcher over time.",
    )


class PostingScheduleItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    deliverable_ref: str
    scheduled_for: AwareDatetime
    posted_at: AwareDatetime | None = Field(
        None,
        description="When it actually went live. Populated on agent confirmation of detected post (or manual URL entry).",
    )
    post_url: AnyUrl | None = None
    posted_detection: PostedDetection | None = Field(
        None,
        description="Provenance for how this post was matched to the expected deliverable. Surfaced to the agent in UI so the confirmation decision is informed.",
    )


class CampaignHashtag(RootModel[str]):
    root: str = Field(..., pattern="^#")


class CaptureMethod(StrEnum):
    META_GRAPH_INSIGHTS = "meta_graph_insights"
    TIKTOK_DISPLAY_METRICS = "tiktok_display_metrics"
    YOUTUBE_ANALYTICS = "youtube_analytics"
    LINKEDIN_ANALYTICS = "linkedin_analytics"
    TWITTER_ANALYTICS = "twitter_analytics"
    PHYLLO = "phyllo"
    MANUAL_ENTRY = "manual_entry"
    BRAND_REPORTED = "brand_reported"


class InterimKpiSnapshot(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    captured_at: AwareDatetime
    post_url: AnyUrl
    deliverable_ref: str
    platform: Platform
    capture_method: CaptureMethod | None = None
    kpis: dict[str, Any] = Field(
        ...,
        description="Per-post KPIs at this capture timestamp. Same kpiMetric shape as brand_deal.kpis and performance_report_pack.kpis — { value, source, source_name?, as_of, verified_at? } per metric.",
    )


class DeliveryStage(BaseModel):
    """
    Captured during DELIVERY stage. Content production, brand approval, posting, performance capture.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    production_kickoff_at: AwareDatetime | None = None
    products_shipped_to_talent_at: AwareDatetime | None = Field(
        None, description="If applicable — brand sent product samples."
    )
    products_received_by_talent_at: AwareDatetime | None = None
    content_drafts: list[ContentDraft] | None = Field(
        None,
        description="Per-deliverable content drafts submitted for brand approval. Versioned — revisions add new entries.",
    )
    posting_schedule: list[PostingScheduleItem] | None = Field(
        None,
        description="When content is scheduled to / has gone live. The Phase 4.8 detection cron polls platform APIs (Meta Graph + TikTok Display in v0.1; YouTube/LinkedIn/X/podcast via Phyllo in v2) and surfaces candidate post matches to the agent for confirmation. `posted_detection` block captures the detection method + match signals + agent confirmation.",
    )
    performance_capture_window_starts_at: AwareDatetime | None = Field(
        None,
        description="Typically the day the first piece of content goes live. KPI capture cron starts pulling platform insights from this point. Set automatically when first posting_schedule[].posted_at confirms.",
    )
    performance_capture_window_ends_at: AwareDatetime | None = Field(
        None,
        description="Typically 30 days after last post — KPIs continue to grow during this window. Reaching this timestamp triggers Phase 4.9 performance_report_pack auto-generation. Configurable per agency (default 30d).",
    )
    campaign_hashtags: list[CampaignHashtag] | None = Field(
        None,
        description="Campaign-specific hashtags the talent should use in posts (e.g. ['#AloYogaPartner', '#ad']). Captured during proposal_pack generation (LLM extracts from brand brief / discovery_debrief) or contract_pack generation (legal clauses often specify required disclosure hashtags). Used by Phase 4.8 detection cron as a +20pt match signal when scoring candidate posts. Empty array = no hashtag-based matching available (rely on time + brand_handle + content_type signals only).",
    )
    interim_kpi_snapshots: list[InterimKpiSnapshot] | None = Field(
        None,
        description="Daily snapshots of per-post KPIs captured during the performance_window by the Phase 4.9 KPI cron (`docs/performance_report_workflow.md`). Each entry = one post × one capture timestamp. Most recent snapshot per post is the source-of-truth for that post's current KPIs; the performance_report_pack aggregates across all snapshots into the final report. Bounded growth: 1 snapshot per post per day for ~30 days = ~30 entries per deliverable per deal.",
    )


class TriggerCondition(StrEnum):
    """
    When this invoice fires. contract_executed = immediately on contract_executed_at. first_post_live = when first posting_schedule[].posted_at is set. all_deliverables_live = when all posting_schedule[] entries have posted_at. specific_date = on a calendar date. manual = agent fires explicitly.
    """

    CONTRACT_EXECUTED = "contract_executed"
    FIRST_POST_LIVE = "first_post_live"
    ALL_DELIVERABLES_LIVE = "all_deliverables_live"
    SPECIFIC_DATE = "specific_date"
    MANUAL = "manual"


class InvoiceScheduleItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sequence: int = Field(
        ...,
        description="Ordering. Used in invoice_pack_id format `inv_..._seq{N}_v{M}`.",
        ge=1,
    )
    percentage: float | None = Field(
        None,
        description="Share of total deal fee (e.g. 50 for 50%). LLM-parsed from payment_terms. May be null for fixed-amount schedules.",
        ge=0.0,
        le=100.0,
    )
    amount_usd: float = Field(
        ...,
        description="Computed as deal.proposal.fee_usd × (percentage / 100). Captured here at confirmation time so subsequent fee changes don't retroactively rewrite the schedule.",
        ge=0.0,
    )
    trigger_condition: TriggerCondition = Field(
        ...,
        description="When this invoice fires. contract_executed = immediately on contract_executed_at. first_post_live = when first posting_schedule[].posted_at is set. all_deliverables_live = when all posting_schedule[] entries have posted_at. specific_date = on a calendar date. manual = agent fires explicitly.",
    )
    specific_date: date_aliased | None = Field(
        None, description="Required if trigger_condition = specific_date."
    )
    payment_terms_days: int | None = Field(
        None,
        description="Days from sent_at to due_at. Per-entry override of agency_profile.invoice_template.default_payment_terms_days.",
        ge=0,
    )
    description: str | None = Field(
        None,
        description="LLM-extracted description (e.g. '50% upon contract execution'). Renders into the invoice line item or memo.",
    )
    fired_at: AwareDatetime | None = Field(
        None,
        description="When the trigger_condition was detected as met. Triggers invoice_pack generation. Null until fired.",
    )
    invoice_pack_id: str | None = Field(
        None,
        description="FK to the latest invoice_pack version generated for this schedule entry. Updates as new versions generate.",
        pattern="^inv_[a-z0-9_-]+_seq[0-9]+_v[0-9]+$",
    )
    schedule_confirmed_at: AwareDatetime | None = Field(
        None,
        description="When agent confirmed the LLM-parsed schedule. Required before any entry can fire. Confirms the entire schedule at once (not per-entry).",
    )
    schedule_confirmed_by_agent_id: str | None = Field(
        None, pattern="^[a-z0-9][a-z0-9-]*$"
    )


class InvoicePackId(RootModel[str]):
    root: str = Field(..., pattern="^inv_[a-z0-9_-]+_seq[0-9]+_v[0-9]+$")


class PerformanceReportPackId(RootModel[str]):
    root: str = Field(..., pattern="^perf_[a-z0-9_-]+_v[0-9]+$")


class CloseStage(BaseModel):
    """
    Captured during CLOSE stage. Multi-invoice via Phase 4.8 invoice pack pipeline (`docs/invoice_workflow.md`). LLM auto-parses the contract pack's payment_terms into `invoice_schedule[]` on contract execution; agent confirms; each entry fires its own invoice_pack when its trigger_condition is met. All invoices must be paid before the deal auto-archives into Phase 1.5 brand_deals.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    invoice_schedule: list[InvoiceScheduleItem] | None = Field(
        None,
        description="Structured payment schedule, LLM-parsed from the contract pack's `commercial_proposal.llm_proposed.payment_terms` free-text field on contract execution. One-time agent gate: agent confirms parsed schedule before any invoice fires. Locked thereafter (amendments use the contract amendment workflow). Each entry corresponds to one invoice_pack.",
    )
    invoice_pack_ids: list[InvoicePackId] | None = Field(
        None,
        description="Flat FK list to ALL invoice pack versions across all schedule sequences. Append-only — v1 of seq=1, v1 of seq=2, v2 of seq=2 (revision), etc. Each schedule_entry.invoice_pack_id points to the latest version for that sequence; this list captures every version ever generated.",
    )
    all_invoices_paid_at: AwareDatetime | None = Field(
        None,
        description="Computed: max of payment_received_at across all invoice_packs once every schedule entry has been fulfilled + paid. One of three required conditions for auto-archive (others: final_performance_report_attachment_id + final_kpis).",
    )
    performance_report_pack_ids: list[PerformanceReportPackId] | None = Field(
        None,
        description="FK list to all Phase 4.9 performance report pack versions generated for this deal. Each version is a file at `data/deals/{deal_id}/performance_report_packs/v{N}.json`. Append-only — v1, v2 (regenerated with kpi_refresh), etc.",
    )
    latest_performance_report_pack_id: str | None = Field(
        None,
        description="Pointer to the current `is_latest: true` performance report pack version.",
        pattern="^perf_[a-z0-9_-]+_v[0-9]+$",
    )
    final_performance_report_attachment_id: str | None = Field(
        None,
        description="FK to attachments[] for the post-campaign performance report sent to brand. AUTO-POPULATED on `performance_report_pack.agent_review.sent_at` — set to the report.pdf path of the latest performance_report_pack version. One of three required conditions for auto-archive.",
    )
    final_kpis: dict[str, Any] | None = Field(
        None,
        description="Final KPI snapshot at archive time. Shape mirrors `brand_deal.kpis` from the Phase 1.5 schema — when auto-archived, these fields carry directly into the brand_deal record. Each metric has {value, source, as_of, verified_at} per the honesty-floor policy. AUTO-POPULATED on `performance_report_pack.agent_review.sent_at` — copied verbatim from the latest report pack's `kpis` block. One of three required conditions for auto-archive.",
    )
    archived_to_brand_deal_id: str | None = Field(
        None,
        description="FK to the created entry in `data/brand_deals/{talent_id}.json` after auto-archive fires. Closes the loop — anyone looking at this deal can navigate forward to its archived historical record.",
        pattern="^deal_[a-z0-9_-]+$",
    )
    archived_at: AwareDatetime | None = None


class Confidence3(StrEnum):
    """
    high = brand stated explicitly; medium = brand implied / agent inferred from context; low = LLM extracted weakly, agent should verify.
    """

    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class DebriefSignal(BaseModel):
    """
    A single signal extracted from the discovery call (an objective heard, a pain point surfaced, a critical event mentioned, etc.). Each signal carries a confidence level reflecting how clearly the brand stated it — used downstream to weight LLM-driven proposal generation.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    statement: str = Field(
        ...,
        description="The signal in plain language, ideally close to the brand's own words.",
    )
    confidence: Confidence3 | None = Field(
        "medium",
        description="high = brand stated explicitly; medium = brand implied / agent inferred from context; low = LLM extracted weakly, agent should verify.",
    )
    source_quote: str | None = Field(
        None,
        description="Optional verbatim quote from the source artefact (call notes, transcript).",
    )
    source_artefact_id: str | None = Field(
        None,
        description="FK to the proposal_pack.context_artefacts[] entry this signal came from.",
        pattern="^ctx_[a-z0-9]+$",
    )


class Type5(StrEnum):
    BRIEF = "brief"
    PROPOSAL = "proposal"
    CONTRACT = "contract"
    AMENDMENT = "amendment"
    CONTENT_DRAFT = "content_draft"
    APPROVAL_ARTIFACT = "approval_artifact"
    POST_SCREENSHOT = "post_screenshot"
    INVOICE = "invoice"
    PAYMENT_CONFIRMATION = "payment_confirmation"
    PERFORMANCE_REPORT = "performance_report"
    OTHER = "other"


class Attachment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    attachment_id: str = Field(
        ...,
        description="Stable identifier. Other fields reference this (e.g. proposal.proposal_attachment_id).",
        pattern="^att_[a-z0-9]+$",
    )
    type: Type5
    filename: str
    url: AnyUrl | None = Field(
        None,
        description="Reference to where the file actually lives. v0.1: filesystem path or external link. v2: signed S3 URL.",
    )
    size_bytes: int | None = Field(None, ge=0)
    mime_type: str | None = None
    uploaded_at: AwareDatetime
    uploaded_by_agent_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    description: str | None = None


class MentionedContactId(RootModel[str]):
    root: str = Field(..., pattern="^[a-z0-9][a-z0-9-]*$")


class Note(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    note_id: str = Field(..., pattern="^note_[a-z0-9]+$")
    agent_id: str = Field(..., pattern="^[a-z0-9][a-z0-9-]*$")
    created_at: AwareDatetime
    content: str
    mentioned_contact_ids: list[MentionedContactId] | None = None


class DiscoveryDebrief(BaseModel):
    """
    Structured debrief of what was learned in the discovery call. Populated via the hybrid extraction flow in Phase 4.6 Stage B: agent dumps free-form notes (or uploads transcript file), LLM extracts structured fields, agent reviews + edits inline + confirms. Each field carries a confidence level. Cross-version anchor — multiple proposal pack versions can share the same debrief; if debrief evolves (e.g. follow-up call adds context), each proposal_pack version snapshots its state in `context_snapshot.discovery_debrief_snapshot`. See `docs/proposal_pack_workflow.md`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    extracted_at: AwareDatetime | None = None
    extracted_from_artefact_ids: list[ExtractedFromArtefactId] | None = Field(
        None,
        description="FKs to `proposal_pack.context_artefacts[]` entries the LLM used as source material (discovery_call_notes, call_transcript, etc.).",
    )
    confirmed_at: AwareDatetime | None = Field(
        None,
        description="When the agent reviewed + confirmed the extracted debrief. Required before proposal generation Stage C can fire.",
    )
    confirmed_by_agent_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    objectives_heard: list[DebriefSignal] | None = Field(
        None, description="What the brand stated they want to achieve."
    )
    pain_points: list[DebriefSignal] | None = Field(
        None,
        description="Current friction the brand surfaced (e.g. 'past creator partnerships felt transactional, no continuity').",
    )
    critical_event: DebriefSignal | None = Field(
        None,
        description="Why now — what's triggering the brand to act (e.g. 'spring launch in 6 weeks', 'CMO pressure to show creator-driven growth').",
    )
    scope_signal: DebriefSignal | None = Field(
        None, description="Campaign size / ambition hints from the call."
    )
    timing_signal: DebriefSignal | None = Field(
        None, description="When brand needs to act / launch."
    )
    budget_signal: BudgetSignal | None = Field(
        None,
        description="Budget hints from the call. Numeric range optional — sometimes only qualitative signal ('flexible', 'tight') is captured.",
    )
    exclusivity_signals: list[DebriefSignal] | None = Field(
        None,
        description="Competing-creator concerns, category exclusivity expectations.",
    )
    usage_rights_signals: list[DebriefSignal] | None = Field(
        None, description="Paid social / whitelisting / broadcast hints from the call."
    )
    decision_process: DecisionProcess | None = Field(
        None, description="Who else needs to weigh in + how + when."
    )
    red_flags_surfaced: list[DebriefSignal] | None = Field(
        None,
        description="Anything from the call that conflicts with talent's red_lines or values.",
    )
    agent_edits_post_extraction: list[AgentEditsPostExtractionItem] | None = Field(
        None,
        description="Audit log of agent edits to LLM-extracted fields during the review-and-confirm step. Captures what the agent changed before clicking Confirm.",
    )


class LeadStage(BaseModel):
    """
    Captured during LEAD stage. Discovery call notes, brand brief, qualification decision, discovery prep pack references (Phase 4.5).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    discovery_call_scheduled_at: AwareDatetime | None = None
    discovery_call_completed_at: AwareDatetime | None = None
    discovery_call_notes: str | None = None
    brief_text: str | None = Field(
        None, description="Inline brief text if brand sent in email/chat."
    )
    brief_attachment_id: str | None = Field(
        None, description="FK to attachments[] if brief is a PDF/doc."
    )
    brief_received_at: AwareDatetime | None = None
    qualification_decision: QualificationDecision | None = None
    qualification_decision_at: AwareDatetime | None = None
    qualification_rationale: str | None = Field(
        None,
        description="Why qualified or disqualified — used by analytics to learn what we say yes/no to.",
    )
    discovery_prep_pack_ids: list[DiscoveryPrepPackId] | None = Field(
        None,
        description="FK list to all versions of the discovery-call prep pack generated for this deal (Phase 4.5). Each version is a file at `data/deals/{deal_id}/prep_packs/v{N}.json`. Append-only — v1, v2, v3... all retained as history. See `docs/discovery_prep_workflow.md`.",
    )
    latest_prep_pack_id: str | None = Field(
        None,
        description="Pointer to the current `is_latest: true` prep pack version. Updates whenever a new version is generated. The agent's UI surfaces this version; older versions are accessed via the audit log.",
        pattern="^prep_[a-z0-9_-]+_v[0-9]+$",
    )
    discovery_debrief: DiscoveryDebrief | None = Field(
        None,
        description="Structured debrief of what was learned in the discovery call. Populated via the hybrid extraction flow in Phase 4.6 Stage B: agent dumps free-form notes (or uploads transcript file), LLM extracts structured fields, agent reviews + edits inline + confirms. Each field carries a confidence level. Cross-version anchor — multiple proposal pack versions can share the same debrief; if debrief evolves (e.g. follow-up call adds context), each proposal_pack version snapshots its state in `context_snapshot.discovery_debrief_snapshot`. See `docs/proposal_pack_workflow.md`.",
    )


class DealLifecycleRecord(BaseModel):
    """
    Phase 4 deal record — moves through 5 stages from a Phase 3b `interested` reply through to a paid + archived deal. Per-deal file at `data/deals/{deal_id}.json` (gitignored — commercial data, signed contracts, invoice amounts). On close + payment + KPI capture, the orchestrator auto-archives this into `data/brand_deals/{talent_id}.json` (Phase 1.5). See `docs/deal_lifecycle_workflow.md`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: str | None = Field(None, alias="$schema")
    agency_id: UUID | None = Field(
        None,
        description="Multi-tenant scope: FK to agency_profile.agency_id. Optional in v0.1 (single-tenant deploys may omit); required in v2 SaaS. When present, all cross-record queries MUST filter by agency_id to prevent cross-tenant data leakage. See docs/data_lineage.md GAP-01/02 for rationale.",
    )
    deal_id: str = Field(
        ...,
        description="Globally unique pipeline-deal identifier. Format: `deal_pipeline_{year}_{quarter}_{brand_slug}_{talent_slug}` or similar (slugs allowed to contain hyphens). Distinguished from Phase 1.5 `brand_deals[].deal_id` (which starts `deal_`) so we never collide IDs between pipeline + archived.",
        pattern="^deal_pipeline_[a-z0-9_-]+$",
    )
    talent_id: str = Field(..., pattern="^[a-z0-9][a-z0-9-]*$")
    brand_id: str = Field(..., pattern="^[a-z0-9][a-z0-9-]*$")
    brand_name: str | None = Field(
        None, description="Denormalised for at-a-glance reading."
    )
    industry_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    primary_contact_id: str | None = Field(
        None,
        description="FK to a contact in `data/brand_contacts/{brand_id}.json`. The buyer driving the deal.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    additional_contact_ids: list[AdditionalContactId] | None = Field(
        None,
        description="Other contacts looped in (legal, finance, brand manager, agency-of-record).",
    )
    originating_enrollment_id: str | None = Field(
        None,
        description="FK to `data/pitch_enrollments/{enrollment_id}.json` — which Phase 3b outreach pitch produced the `interested` reply that created this deal. Closes the outreach→deal analytics loop (bidirectional with `pitch_enrollment.created_deal_id`).",
        pattern="^enr_[a-z0-9]+$",
    )
    originating_decision_role_at_pitch: OriginatingDecisionRoleAtPitch | None = Field(
        None,
        description="Snapshot of `brand_contact.decision_role` at the time the originating pitch went out. Captured here on deal creation (vs reading from contact record live) because the contact's role may evolve (promotions, role changes) and we want to anchor 'won-deal-by-decision-role' analytics to the role at pitch time. Powers cross-cuts like 'we win more deals when champion is the originating contact'.",
    )
    assigned_agent_id: str = Field(
        ...,
        description="FK to an agent in `agency_profile.agents[]`. v0.1: always the single primary agent. v2: per-deal assignment.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    stage: Stage = Field(
        ...,
        description="Top-level lifecycle stage. `archived` is the post-close terminal state after auto-archive into Phase 1.5 brand_deals.",
    )
    substage: Substage = Field(
        ...,
        description="Granular state within (or terminal-state outside of) the current stage. Transition validity is enforced by the orchestrator per the state machine in docs/deal_lifecycle_workflow.md.",
    )
    is_terminal: bool | None = Field(
        False,
        description="True if substage is one of: disqualified, lost, killed, contract_failed, archived. Used to filter pipeline views.",
    )
    is_won: bool | None = Field(
        False,
        description="True only after stage=archived with payment_received. Distinguished from terminal-but-lost.",
    )
    stage_history: list[StageHistoryItem] | None = Field(
        None, description="Audit trail of every stage/substage transition. Append-only."
    )
    expected_value_usd: float | None = Field(
        None,
        description="Best estimate of deal value, updated as the deal progresses. At lead stage = ballpark; at proposal stage = the proposed fee; at contract stage = the contracted fee.",
        ge=0.0,
    )
    expected_close_date: date_aliased | None = Field(
        None,
        description="Best estimate of when the deal will reach `archived` (i.e. signed + delivered + paid). Used for pipeline forecasting.",
    )
    actual_final_value_usd: float | None = Field(
        None,
        description="Final paid amount. Set when stage=archived. May differ from expected_value_usd if scope changed mid-deal.",
        ge=0.0,
    )
    next_action: str | None = Field(
        None,
        description="Free-text or templated next action the agent needs to take. e.g. 'Send revised proposal with adjusted usage rights'. Drives the agent's daily task list.",
    )
    next_action_due_at: AwareDatetime | None = Field(
        None,
        description="When the next_action is due. Drives the daily reminder cron — overdue actions surface in the agent's morning summary.",
    )
    lead: LeadStage | None = None
    proposal: ProposalStage | None = None
    contract: ContractStage | None = None
    delivery: DeliveryStage | None = None
    close: CloseStage | None = None
    loss: Loss | None = Field(
        None,
        description="Populated only when substage is `lost`, `killed`, `disqualified`, or `contract_failed`. Captures structured loss-reason for funnel analytics.",
    )
    attachments: list[Attachment] | None = Field(
        None,
        description="All documents associated with the deal: briefs, proposals, contracts, content drafts, approvals, invoices, reports. Files stored externally (S3/cloud storage); this array holds metadata + references.",
    )
    notes: list[Note] | None = Field(
        None,
        description="Free-text notes from the agent. Append-only audit trail of insights, conversations, decisions.",
    )
    created_at: AwareDatetime
    updated_at: AwareDatetime | None = None
    created_by_agent_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
