# generated by datamodel-codegen:
#   filename:  discovery_prep_pack.schema.json
#   timestamp: 2026-06-01T11:52:22+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Trigger(StrEnum):
    """
    auto_*: fired by the orchestrator when the deal transitioned to initial_call_scheduled. agent_full_regenerate: agent asked for a full rebuild with new feedback. agent_section_regenerate: targeted just briefing OR agenda OR a subset of slides. agent_per_slide_regenerate: targeted specific slide(s) only.
    """

    AUTO_ON_INITIAL_CALL_SCHEDULED = "auto_on_initial_call_scheduled"
    AGENT_FULL_REGENERATE = "agent_full_regenerate"
    AGENT_SECTION_REGENERATE = "agent_section_regenerate"
    AGENT_PER_SLIDE_REGENERATE = "agent_per_slide_regenerate"


class PassName(StrEnum):
    BRIEFING = "briefing"
    AGENDA = "agenda"
    SLIDES = "slides"
    EXTERNAL_RESEARCH = "external_research"
    SECTION_REGEN = "section_regen"
    SLIDE_REGEN = "slide_regen"


class LlmPass(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pass_name: PassName
    model: str | None = None
    input_tokens: int = Field(..., ge=0)
    output_tokens: int = Field(..., ge=0)
    cached_tokens: int | None = Field(
        None, description="Tokens served from prompt cache.", ge=0
    )
    cost_usd: float | None = Field(None, ge=0.0)
    duration_ms: int | None = Field(None, ge=0)


class Generation(BaseModel):
    """
    Provenance + parameters for this version's generation. Captures what the agent asked for and what the LLM produced.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    trigger: Trigger = Field(
        ...,
        description="auto_*: fired by the orchestrator when the deal transitioned to initial_call_scheduled. agent_full_regenerate: agent asked for a full rebuild with new feedback. agent_section_regenerate: targeted just briefing OR agenda OR a subset of slides. agent_per_slide_regenerate: targeted specific slide(s) only.",
    )
    pre_generation_guidance: str | None = Field(
        None,
        description="Free-text guidance the agent provided BEFORE generation fired. Example: 'Brand specifically mentioned wanting activewear with established performance credibility — lead with our Lululemon case study; downplay the lifestyle/fashion angle.' Captured for the LLM prompt and for audit (so future versions can see what each round was steered toward).",
    )
    regeneration_feedback: str | None = Field(
        None,
        description="Natural-language feedback the agent gave on the parent version. Populated when version > 1. Example: 'Slide 4 audience claim feels overstated — tone it down and add the as-of date. Drop the sustainability angle entirely, brand told me on the intro email they're focused on performance, not values.' The LLM consumes this PLUS the parent version PLUS the original context to produce the new version.",
    )
    target_sections: list[str] | None = Field(
        None,
        description="For agent_section_regenerate / agent_per_slide_regenerate: which sections were rebuilt. e.g. ['briefing.likely_objections', 'slides[3]', 'slides[7]']. Sections not listed are carried forward unchanged from parent_version.",
    )
    generated_at: AwareDatetime
    generated_by_agent_id: str | None = Field(
        None,
        description="Which agent triggered this generation. Same as `deal.assigned_agent_id` for v1; can differ for later versions if the deal was reassigned mid-prep.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    llm_model: str = Field(
        ...,
        description="Model identifier used. Recorded for reproducibility — if generation quality changes after a model upgrade, we can see which version used which model.",
    )
    llm_passes: list[LlmPass] | None = Field(
        None,
        description="Multi-pass generation log. v0.1 = 3 passes (briefing, agenda, slides). Each pass shares context via prompt-caching where supported.",
    )


class ComparableBrandDealId(RootModel[str]):
    root: str = Field(..., pattern="^deal_[a-z0-9_-]+$")


class TopScoringAngleId(RootModel[str]):
    root: str = Field(..., pattern="^pa_[a-z0-9_-]+$")


class Provider(StrEnum):
    EXA = "exa"
    NONE = "none"


class Purpose(StrEnum):
    BRAND_RECENT_CAMPAIGNS = "brand_recent_campaigns"
    BRAND_NEWS = "brand_news"
    BRAND_SOCIAL_SIGNALS = "brand_social_signals"
    CONTACT_BACKGROUND = "contact_background"
    COMPETITOR_LANDSCAPE = "competitor_landscape"
    OTHER = "other"


class Query(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    query: str
    purpose: Purpose | None = None
    executed_at: AwareDatetime
    results_summary: str | None = Field(
        None,
        description="LLM-summarised digest of the top results. The raw Exa response is NOT stored long-term — only the summary.",
    )
    result_urls: list[AnyUrl] | None = Field(
        None, description="URLs of the top results, kept for citation provenance."
    )


class ExternalResearch(BaseModel):
    """
    Web research pulled via Exa during generation. Captures queries + summarised results + as-of timestamp so claims sourced from external research can be cited.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    provider: Provider | None = "exa"
    queries: list[Query] | None = None


class ContextSnapshot(BaseModel):
    """
    Frozen snapshot of the upstream context this version was generated from. If the deal/talent/brand data evolves later, this version stays anchored to the data it actually consumed. Drives the 'V1 stays locked unless agent asks' decision: we can detect upstream drift but don't auto-regenerate.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    captured_at: AwareDatetime
    deal_stage_at_gen: str | None = None
    deal_substage_at_gen: str | None = None
    talent_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    talent_profile_updated_at: AwareDatetime | None = Field(
        None,
        description="Timestamp of the talent profile we read. If the profile updates after generation, the orchestrator can detect drift and surface 'Regenerate prep pack?' but doesn't force it.",
    )
    brand_candidate_id: str | None = None
    brand_candidate_updated_at: AwareDatetime | None = None
    primary_contact_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    originating_enrollment_id: str | None = Field(None, pattern="^enr_[a-z0-9]+$")
    originating_reply_text: str | None = Field(
        None,
        description="Verbatim text of the brand's `interested` reply that created this deal. Anchor citation throughout the briefing.",
    )
    comparable_brand_deal_ids: list[ComparableBrandDealId] | None = Field(
        None,
        description="FK list to past `data/brand_deals` entries the LLM cited as comparables for the case-study slides + commercial range.",
    )
    top_scoring_angle_ids: list[TopScoringAngleId] | None = Field(
        None,
        description="FK list to `data/pitch_angles.json` entries scored highest for this brand × niche pair.",
    )
    external_research: ExternalResearch | None = Field(
        None,
        description="Web research pulled via Exa during generation. Captures queries + summarised results + as-of timestamp so claims sourced from external research can be cited.",
    )


class LikelyObjection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    objection: str
    response: str
    source: str | None = Field(
        None,
        description="Why we expect this objection — e.g. 'Brand previously raised exclusivity concern in pitch reply.'",
    )


class QuestionsTheyMightAskItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    question: str
    prepared_answer: str


class ComparableDealId(RootModel[str]):
    root: str = Field(..., pattern="^deal_[a-z0-9_-]+$")


class CommercialRange(BaseModel):
    """
    Suggested fee range for this scope. Computed from comparable past `brand_deals` fees in similar industries × similar deliverable scope. Surface in briefing only — NOT shown to brand on the call unless they ask.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    low_usd: float | None = Field(None, ge=0.0)
    high_usd: float | None = Field(None, ge=0.0)
    currency: str | None = Field("USD", pattern="^[A-Z]{3}$")
    comparable_deal_ids: list[ComparableDealId] | None = None
    rationale: str | None = Field(
        None,
        description="How the range was derived. e.g. '3 comparable activewear deals in the last 12 months: $8k, $12k, $14k. Brand size + scope suggests upper-mid of this range.'",
    )


class BriefingNotes(BaseModel):
    """
    Internal, agent-only briefing document. Markdown rendered from these structured fields. Talent does not see this (per the agent-solo-on-call decision).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    deal_summary: str | None = Field(
        None,
        description="What won this meeting — the pitch we sent + the brand's reply, summarised. Cites originating_reply_text verbatim.",
    )
    about_brand: str | None = Field(
        None,
        description="Brand context: who they are, recent campaigns, recent news, current priorities. Sourced from Phase 2 brand_candidates + Exa external_research. Each non-obvious claim should have a source citation.",
    )
    about_contact: str | None = Field(
        None,
        description="Buyer's role, decision_role classification, signals from prior Phase 3a `pitch_history`, what they've previously engaged with.",
    )
    about_talent_for_call: str | None = Field(
        None,
        description="Talent positioning for THIS conversation: relevant past work, KPIs to lead with (with provenance per honesty-floor), values-fit check against brand.",
    )
    fit_hypothesis: str | None = Field(
        None,
        description="Why these two together. Synthesises the top-scoring angles into a 1-paragraph thesis.",
    )
    likely_objections: list[LikelyObjection] | None = Field(
        None,
        description="Anticipated brand objections + prepared responses. Mined from past `objection`-classified outcomes in the outreach analyzer when available.",
    )
    red_flags: str | None = Field(
        None,
        description="Anything in brand data conflicting with talent's `red_lines` / values. Agent must steer the conversation away from these (or surface early if a blocker).",
    )
    questions_to_ask: list[str] | None = Field(
        None,
        description="Discovery questions the agent should ask to qualify scope + budget + timing + decision process.",
    )
    questions_they_might_ask: list[QuestionsTheyMightAskItem] | None = None
    commercial_range: CommercialRange | None = Field(
        None,
        description="Suggested fee range for this scope. Computed from comparable past `brand_deals` fees in similar industries × similar deliverable scope. Surface in briefing only — NOT shown to brand on the call unless they ask.",
    )


class Section(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    duration_min: int = Field(..., ge=1)
    purpose: str | None = Field(
        None, description="One-line description of what this section achieves."
    )
    talking_points: list[str] | None = None


class Agenda(BaseModel):
    """
    The discovery-call agenda. Customised per deal — if brief already received, the 'brand context check' section is dropped and 'open exploration' is expanded.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    duration_total_min: int = Field(..., ge=15, le=120)
    sections: list[Section] = Field(..., min_length=3)


class Type(StrEnum):
    HTML_LIVE = "html_live"
    HTML_LEAVE_BEHIND = "html_leave_behind"
    PDF_LIVE = "pdf_live"
    PDF_LEAVE_BEHIND = "pdf_leave_behind"
    SPEAKER_NOTES_MD = "speaker_notes_md"
    PPTX = "pptx"
    BRIEFING_NOTES_MD = "briefing_notes_md"
    AGENDA_MD = "agenda_md"


class Status(StrEnum):
    RENDERED = "rendered"
    PENDING = "pending"
    FAILED = "failed"


class RenderedBy(StrEnum):
    """
    Which renderer produced this artefact.
    """

    JINJA2_HTML = "jinja2_html"
    PUPPETEER_PDF = "puppeteer_pdf"
    SLIDE_SKILL = "slide_skill"
    MARKDOWN_WRITER = "markdown_writer"


class ExportArtifact(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type
    status: Status
    path: str | None = Field(
        None,
        description="Local filesystem path (v0.1) or S3 key (production). Relative to `data/deals/{deal_id}/prep_packs/v{N}_artifacts/`.",
    )
    size_bytes: int | None = Field(None, ge=0)
    rendered_at: AwareDatetime | None = None
    rendered_by: RenderedBy | None = Field(
        None, description="Which renderer produced this artefact."
    )
    error: str | None = Field(None, description="If status=failed, what went wrong.")


class EditType(StrEnum):
    """
    Direct edit (no LLM regen). For LLM-regen of a slide/section, see `generation.target_sections` on the NEXT version.
    """

    SLIDE_HTML_DIRECT = "slide_html_direct"
    BRIEFING_TEXT_DIRECT = "briefing_text_direct"
    AGENDA_TEXT_DIRECT = "agenda_text_direct"
    SLIDE_REORDER = "slide_reorder"
    SLIDE_DELETE = "slide_delete"
    SLIDE_INSERT = "slide_insert"


class AgentEdit(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    edit_id: str = Field(..., pattern="^edit_[a-z0-9]+$")
    edited_at: AwareDatetime
    edited_by_agent_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    edit_type: EditType = Field(
        ...,
        description="Direct edit (no LLM regen). For LLM-regen of a slide/section, see `generation.target_sections` on the NEXT version.",
    )
    target: str = Field(
        ...,
        description="What was edited. e.g. 'slides[3].live_body', 'briefing.about_brand'.",
    )
    before_excerpt: str | None = Field(
        None,
        description="Short excerpt of the prior content (for audit; not a full snapshot — full history is reconstructable from version history).",
    )
    after_excerpt: str | None = None


class Type7(StrEnum):
    """
    Drives the renderer's layout template. The slide skill picks a layout per type — e.g. `audience_snapshot` lays out KPI tiles in a grid; `case_study` uses a quote+image layout.
    """

    TITLE = "title"
    CONTEXT = "context"
    TALENT_OVERVIEW = "talent_overview"
    AUDIENCE_SNAPSHOT = "audience_snapshot"
    RECENT_WORK = "recent_work"
    BRAND_OBSERVATION = "brand_observation"
    FIT_ANGLE = "fit_angle"
    CASE_STUDY = "case_study"
    PROOF_POINT = "proof_point"
    PROCESS = "process"
    NEXT_STEPS = "next_steps"
    CUSTOM = "custom"


class KpiTile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    value: str = Field(
        ...,
        description="The number/figure to display (string so we can include `M`, `%`, `k`, etc.).",
    )
    label: str
    source: str | None = Field(
        None, description="Citation for the figure (per honesty-floor)."
    )
    as_of: date_aliased | None = None


class ImageRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    alt: str | None = None
    caption: str | None = None


class LiveBody(BaseModel):
    """
    Sparse content for the live screen-share variant. Big visuals, short text. The agent talks; the slide is wallpaper.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    headline: str | None = Field(
        None, description="Big top-line — typically 3-8 words."
    )
    subheadline: str | None = None
    body_text: str | None = Field(
        None,
        description="Short, scannable. Bullets fine. Avoid paragraphs in live mode.",
    )
    bullets: list[str] | None = None
    kpi_tiles: list[KpiTile] | None = Field(
        None,
        description="For audience_snapshot / proof_point slides. Each tile renders as a big-number-with-label.",
    )
    image_refs: list[ImageRef] | None = Field(
        None,
        description="Image URLs/paths the renderer should compose into the slide. For case_study + recent_work slides.",
    )
    callout: str | None = Field(
        None, description="Highlighted quote or stat in accent color."
    )


class LeaveBehindExtension(BaseModel):
    """
    Additional written context that appears ONLY in the leave-behind variant (post-call read by buyer to share internally). Empty in live mode.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    expanded_body: str | None = Field(
        None,
        description="Paragraph-form context. The 'why this matters' written out for someone reading without the agent's voiceover.",
    )
    supporting_data: str | None = None
    footnotes: list[str] | None = None


class Source(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    claim: str = Field(
        ..., description="The claim being sourced (excerpt of slide text)."
    )
    source: str = Field(
        ...,
        description="Where it came from — 'Phase 1.5 brand_deal deal_2025_lululemon', 'Exa search 2026-05-26: nytimes.com/...', 'IG Insights API'.",
    )
    as_of: date_aliased | None = None


class Slide(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    slide_id: str = Field(..., pattern="^slide_[a-z0-9_-]+$")
    position: int = Field(..., ge=1)
    title: str
    type: Type7 = Field(
        ...,
        description="Drives the renderer's layout template. The slide skill picks a layout per type — e.g. `audience_snapshot` lays out KPI tiles in a grid; `case_study` uses a quote+image layout.",
    )
    live_body: LiveBody = Field(
        ...,
        description="Sparse content for the live screen-share variant. Big visuals, short text. The agent talks; the slide is wallpaper.",
    )
    leave_behind_extension: LeaveBehindExtension | None = Field(
        None,
        description="Additional written context that appears ONLY in the leave-behind variant (post-call read by buyer to share internally). Empty in live mode.",
    )
    speaker_notes: str | None = Field(
        None,
        description="What the agent says when this slide is up. Talking points, transitions to the next slide, anticipated questions. Rendered into the separate speaker_notes.md artefact (second-screen reference).",
    )
    sources: list[Source] | None = Field(
        None,
        description="Citations for any factual claim on the slide. Honesty-floor: every KPI / market stat / brand claim has a source + as_of date.",
    )
    agent_edited: bool | None = Field(
        False,
        description="True if the agent has directly edited this slide post-generation (via the slide skill's editor). Edits to LLM-regenerated slides reset this to false (a fresh draft). Used by the UI to badge edited slides.",
    )
    agent_edited_at: AwareDatetime | None = None


class DiscoveryCallPrepPack(BaseModel):
    """
    Phase 4.5 — a versioned prep pack the agent walks into a discovery call with. Generated when a Phase 4 LEAD-stage deal transitions to substage `initial_call_scheduled`. Bundles agenda + briefing notes (internal, agent-only) + slide deck (live + leave-behind variants + speaker notes) — all auto-drafted end-to-end by Claude Sonnet, with optional pre-generation guidance from the agent and an iterative natural-language feedback loop for regeneration. Stored at `data/deals/{deal_id}/prep_packs/v{N}.json` (gitignored). See `docs/discovery_prep_workflow.md`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: str | None = Field(None, alias="$schema")
    agency_id: UUID | None = Field(
        None,
        description="Multi-tenant scope: FK to agency_profile.agency_id. Optional in v0.1 (single-tenant deploys may omit); required in v2 SaaS. When present, all cross-record queries MUST filter by agency_id to prevent cross-tenant data leakage. See docs/data_lineage.md GAP-01/02 for rationale.",
    )
    prep_pack_id: str = Field(
        ...,
        description="Globally unique identifier. Format: `prep_{deal_id_short}_v{N}` (e.g. `prep_2026_q2_alo-yoga_jane-doe_v3`). Encodes the deal + version for easy human reading.",
        pattern="^prep_[a-z0-9_-]+_v[0-9]+$",
    )
    deal_id: str = Field(
        ...,
        description="FK to the Phase 4 deal this prep pack belongs to. The deal's `lead.discovery_prep_pack_ids[]` array references all versions; its `lead.latest_prep_pack_id` points to the current `is_latest: true` version.",
        pattern="^deal_pipeline_[a-z0-9_-]+$",
    )
    version: int = Field(
        ...,
        description="Monotonically increasing. v1 = initial auto-generation triggered by `substage = initial_call_scheduled`. v2+ = agent-requested regenerations (whole-pack or section-targeted).",
        ge=1,
    )
    parent_version: int | None = Field(
        None,
        description="Which version this one was regenerated from. Null/absent for v1. Forms a linear history — every regen is from the most recent version.",
        ge=1,
    )
    is_latest: bool = Field(
        ...,
        description="True for exactly one version per deal_id at any time. When v3 generates, v2's is_latest flips to false. The deal's `latest_prep_pack_id` always points to the is_latest=true version.",
    )
    generation: Generation = Field(
        ...,
        description="Provenance + parameters for this version's generation. Captures what the agent asked for and what the LLM produced.",
    )
    context_snapshot: ContextSnapshot = Field(
        ...,
        description="Frozen snapshot of the upstream context this version was generated from. If the deal/talent/brand data evolves later, this version stays anchored to the data it actually consumed. Drives the 'V1 stays locked unless agent asks' decision: we can detect upstream drift but don't auto-regenerate.",
    )
    briefing_notes: BriefingNotes = Field(
        ...,
        description="Internal, agent-only briefing document. Markdown rendered from these structured fields. Talent does not see this (per the agent-solo-on-call decision).",
    )
    agenda: Agenda = Field(
        ...,
        description="The discovery-call agenda. Customised per deal — if brief already received, the 'brand context check' section is dropped and 'open exploration' is expanded.",
    )
    slides: list[Slide] = Field(
        ...,
        description="The deck — structured JSON, ordered by `position`. Renderer produces three artefacts from this array: live HTML (live_body only), leave-behind HTML (live_body + leave_behind_extension), and speaker notes markdown (speaker_notes paired with titles).",
        min_length=1,
    )
    export_artifacts: list[ExportArtifact] | None = Field(
        None,
        description="Paths to rendered output files. Populated by the renderer post-generation. Status field tracks whether each artefact rendered successfully or is pending (e.g. PPT is pending until the slide skill is wired).",
    )
    agent_edits: list[AgentEdit] | None = Field(
        None,
        description="Append-only audit log of agent edits to this version. Direct edits to slide HTML (via the slide skill's editor) are logged here so we can see what changed vs the LLM-generated draft. Natural-language feedback that triggered a NEW version (regeneration) is captured in that next version's `generation.regeneration_feedback`, not here.",
    )
    created_at: AwareDatetime
    updated_at: AwareDatetime | None = None
