# generated by datamodel-codegen:
#   filename:  invoice_pack.schema.json
#   timestamp: 2026-05-28T08:49:29+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, EmailStr, Field


class Trigger(StrEnum):
    """
    schedule_trigger_fired: cron detected the schedule entry's trigger_condition met (e.g. all_deliverables_live). agent_initiated: agent manually fired (e.g. for `manual` trigger entries). agent_regenerate: NL feedback regen of this invoice. brand_revision_request: brand asked for a change (line item description, tax adjustment) → new version. amendment_invoice: post-execution amendment created a new invoice via the contract amendment_log flow.
    """

    SCHEDULE_TRIGGER_FIRED = "schedule_trigger_fired"
    AGENT_INITIATED = "agent_initiated"
    AGENT_REGENERATE = "agent_regenerate"
    BRAND_REVISION_REQUEST = "brand_revision_request"
    AMENDMENT_INVOICE = "amendment_invoice"


class TriggerConditionFired(StrEnum):
    """
    Which condition from the invoice_schedule entry actually fired. Captured for audit.
    """

    CONTRACT_EXECUTED = "contract_executed"
    FIRST_POST_LIVE = "first_post_live"
    ALL_DELIVERABLES_LIVE = "all_deliverables_live"
    SPECIFIC_DATE = "specific_date"
    MANUAL = "manual"


class PassName(StrEnum):
    LINE_ITEM_NARRATIVE = "line_item_narrative"
    COMPOSE_REFINEMENT = "compose_refinement"
    SECTION_REGEN = "section_regen"


class LlmPass(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pass_name: PassName
    model: str | None = None
    input_tokens: int = Field(..., ge=0)
    output_tokens: int = Field(..., ge=0)
    cached_tokens: int | None = Field(None, ge=0)
    cost_usd: float | None = Field(None, ge=0.0)
    duration_ms: int | None = Field(None, ge=0)


class Generation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trigger: Trigger = Field(
        ...,
        description="schedule_trigger_fired: cron detected the schedule entry's trigger_condition met (e.g. all_deliverables_live). agent_initiated: agent manually fired (e.g. for `manual` trigger entries). agent_regenerate: NL feedback regen of this invoice. brand_revision_request: brand asked for a change (line item description, tax adjustment) → new version. amendment_invoice: post-execution amendment created a new invoice via the contract amendment_log flow.",
    )
    trigger_condition_fired: TriggerConditionFired | None = Field(
        None,
        description="Which condition from the invoice_schedule entry actually fired. Captured for audit.",
    )
    fired_at: AwareDatetime | None = Field(
        None,
        description="When the trigger condition was met (vs `generated_at` which is when generation completed).",
    )
    regeneration_feedback: str | None = Field(
        None, description="NL feedback for regenerate triggers."
    )
    generated_at: AwareDatetime
    generated_by_agent_id: str | None = Field(
        None,
        description="Agent who triggered. Null/absent for cron-triggered (schedule_trigger_fired) generations.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    llm_model: str | None = Field(
        None,
        description="Only present if any LLM passes ran (e.g. narrative line item drafting). Many invoices generate with 0 LLM passes.",
    )
    llm_passes: list[LlmPass] | None = None


class DetectionMethod(StrEnum):
    META_GRAPH_AUTO = "meta_graph_auto"
    TIKTOK_API_AUTO = "tiktok_api_auto"
    AGENT_CONFIRMED_SUGGESTION = "agent_confirmed_suggestion"
    MANUAL_URL_ENTRY = "manual_url_entry"


class MatchedPost(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    deliverable_ref: str
    post_url: AnyUrl
    posted_at: AwareDatetime
    detection_method: DetectionMethod | None = None


class ContextSnapshot(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    captured_at: AwareDatetime
    contract_pack_id_at_gen: str | None = Field(
        None,
        description="Which executed contract pack version this invoice was generated against. Anchors line-item descriptions + amounts to the contract that authorised them.",
        pattern="^cp_[a-z0-9_-]+_v[0-9]+$",
    )
    talent_billing_entity_snapshot: dict[str, Any] | None = Field(
        None,
        description="Frozen copy of `talent.billing_entity` at generation time. Talent legal-name changes after invoice generation don't retroactively rewrite issued invoices.",
    )
    brand_legal_entity_snapshot: dict[str, Any] | None = Field(
        None,
        description="Frozen copy of `contract_pack.context_snapshot.brand_legal_entity_at_gen`. Same anchoring rationale.",
    )
    agency_invoice_template_version: str | None = Field(
        None,
        description="Value of `agency_profile.invoice_template.template_version` at generation. Template changes don't retroactively rewrite issued invoices.",
    )
    invoice_schedule_entry_snapshot: dict[str, Any] | None = Field(
        None,
        description="Frozen copy of the `deal.close.invoice_schedule[sequence]` entry being fulfilled.",
    )
    matched_posts: list[MatchedPost] | None = Field(
        None,
        description="If trigger_condition involved post detection (first_post_live / all_deliverables_live), captures the matched posts. Each entry references the posting_schedule[] entry that triggered.",
    )


class Source(StrEnum):
    TALENT_BILLING_ENTITY = "talent_billing_entity"
    AGENCY_PROFILE = "agency_profile"
    AGENCY_INVOICE_TEMPLATE = "agency_invoice_template"
    DEAL_PROPOSAL = "deal_proposal"
    CONTRACT_PACK = "contract_pack"
    SCHEDULE_ENTRY = "schedule_entry"
    COMPUTED = "computed"
    AGENT_INPUT = "agent_input"
    DEFAULT = "default"


class Confidence(StrEnum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    MISSING = "missing"


class MergeFieldValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field: str
    value: Any | None = None
    source: Source
    source_path: str | None = None
    confidence: Confidence | None = None
    needs_review: bool | None = False
    agent_overridden: bool | None = False
    agent_override_note: str | None = None


class LineItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    deliverable_ref: str | None = Field(
        None,
        description="Reference to `deal.proposal.deliverables[].` entry this line item represents. Null for non-deliverable line items (e.g. expense reimbursement).",
    )
    description: str = Field(
        ..., description="Human-readable line item. LLM-drafted or template-default."
    )
    quantity: int = Field(..., ge=1)
    unit_price_usd: float = Field(..., ge=0.0)
    amount_usd: float = Field(
        ...,
        description="quantity × unit_price_usd. Computed; redundant for clarity in rendered output.",
        ge=0.0,
    )
    narrative_drafted_by_llm: bool | None = Field(
        False,
        description="True if description was LLM-generated. False if template-default or agent-edited.",
    )


class Amounts(BaseModel):
    """
    Computed totals. subtotal_usd = sum of line_items[].amount_usd. tax handling per agency_profile.invoice_template.tax_handling.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    subtotal_usd: float = Field(..., ge=0.0)
    tax_rate: float | None = Field(
        None,
        description="Decimal (0.20 = 20%). From agency_profile.invoice_template.default_tax_rate or per-deal override.",
        ge=0.0,
        le=1.0,
    )
    tax_amount_usd: float | None = Field(None, ge=0.0)
    tax_label: str | None = Field(
        None,
        description="What this tax is called on the rendered invoice (e.g. 'VAT', 'Sales Tax', 'GST').",
    )
    total_usd: float = Field(..., ge=0.0)
    currency: str = Field("USD", pattern="^[A-Z]{3}$")
    fx_rate_to_usd: float | None = Field(
        None,
        description="If the deal's contract specifies a non-USD currency, this captures the FX rate used at generation. Both the original currency amount and the USD-normalised amount may be rendered.",
        ge=0.0,
    )


class SendMethod(StrEnum):
    """
    v0.1: always manual_email (agent emails the PDF). v2: API-driven send via Stripe Invoices / Xero / QuickBooks auto-populates this + the external invoice_id.
    """

    MANUAL_EMAIL = "manual_email"
    STRIPE_INVOICE_SEND = "stripe_invoice_send"
    XERO_SEND = "xero_send"
    QUICKBOOKS_SEND = "quickbooks_send"
    OTHER = "other"


class AgentReview(BaseModel):
    """
    Soft gate. Agent reviews rendered PDF + can edit any merge field / line item / template content. Edits regenerate the PDF. Clicking 'Send' sets sent_at — sending IS the approval (no separate 'approve' event like contracts). All fields optional — absence of `sent_at` means the invoice is still in draft.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    viewed_at: AwareDatetime | None = Field(
        None, description="When agent first opened the rendered PDF."
    )
    sent_at: AwareDatetime | None = Field(
        None,
        description="When agent clicked Send. ABSENT = invoice is in draft state. Setting this transitions payment_state.status from `draft` to `sent`.",
    )
    sent_by_agent_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    send_method: SendMethod | None = Field(
        "manual_email",
        description="v0.1: always manual_email (agent emails the PDF). v2: API-driven send via Stripe Invoices / Xero / QuickBooks auto-populates this + the external invoice_id.",
    )
    sent_to_email: EmailStr | None = Field(
        None,
        description="Recipient on the brand side. Captured for audit + reminder follow-up.",
    )


class Type(StrEnum):
    """
    v0.1: markdown source + PDF only. No Word — invoices are typically PDF-only artefacts.
    """

    INVOICE_MD = "invoice_md"
    INVOICE_PDF = "invoice_pdf"


class Status(StrEnum):
    RENDERED = "rendered"
    PENDING = "pending"
    FAILED = "failed"


class RenderedBy(StrEnum):
    MARKDOWN_WRITER = "markdown_writer"
    PUPPETEER_PDF = "puppeteer_pdf"
    PANDOC = "pandoc"


class ExportArtifact(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type = Field(
        ...,
        description="v0.1: markdown source + PDF only. No Word — invoices are typically PDF-only artefacts.",
    )
    status: Status
    path: str | None = None
    size_bytes: int | None = Field(None, ge=0)
    rendered_at: AwareDatetime | None = None
    rendered_by: RenderedBy | None = None
    error: str | None = None


class Status4(StrEnum):
    """
    draft: agent hasn't sent yet. sent: agent_review.sent_at set, awaiting payment. viewed_by_brand: v2 only (Stripe/etc. webhook for invoice viewed). paid: payment_received_at set. overdue: due_at < now and not paid. disputed: brand has formally disputed (agent sets manually). void: invoice cancelled.
    """

    DRAFT = "draft"
    SENT = "sent"
    VIEWED_BY_BRAND = "viewed_by_brand"
    PAID = "paid"
    OVERDUE = "overdue"
    DISPUTED = "disputed"
    VOID = "void"


class PaymentMethod(StrEnum):
    BANK_TRANSFER = "bank_transfer"
    WIRE = "wire"
    ACH = "ach"
    STRIPE = "stripe"
    PAYPAL = "paypal"
    WISE = "wise"
    CHECK = "check"
    OTHER = "other"


class PaymentState(BaseModel):
    """
    Payment lifecycle for this specific invoice. Multiple invoice packs per deal each track independently. The deal's auto-archive trigger requires ALL invoices to have status=paid.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    status: Status4 = Field(
        ...,
        description="draft: agent hasn't sent yet. sent: agent_review.sent_at set, awaiting payment. viewed_by_brand: v2 only (Stripe/etc. webhook for invoice viewed). paid: payment_received_at set. overdue: due_at < now and not paid. disputed: brand has formally disputed (agent sets manually). void: invoice cancelled.",
    )
    due_at: AwareDatetime | None = Field(
        None,
        description="Payment due. Computed as sent_at + agency_profile.invoice_template.default_payment_terms_days (or schedule_entry.payment_terms_days override). Used by overdue cron.",
    )
    payment_received_at: AwareDatetime | None = Field(
        None,
        description="v0.1: agent sets manually when funds confirmed. v2: webhook from Stripe/Xero/QuickBooks auto-populates.",
    )
    payment_method: PaymentMethod | None = None
    payment_amount_received_usd: float | None = Field(
        None,
        description="Actual amount received (may differ from amounts.total_usd due to FX or partial payment). If partial, status stays `sent` with a reconciliation_note explaining.",
        ge=0.0,
    )
    payment_reference: str | None = Field(
        None,
        description="Bank transaction reference / Stripe charge ID / wire reference. For reconciliation.",
    )
    external_invoice_id: str | None = Field(
        None,
        description="v2: Stripe invoice id / Xero invoice id / etc. when sent via external provider.",
    )
    reconciliation_note: str | None = Field(
        None,
        description="Free-text for partial payment / fx adjustment / written-off remainder explanations.",
    )


class Type9(StrEnum):
    AGENT_NOTIFICATION = "agent_notification"
    AGENT_EMAIL_SENT = "agent_email_sent"
    PHONE_FOLLOWUP = "phone_followup"
    ESCALATION = "escalation"
    BRAND_RESPONSE_RECEIVED = "brand_response_received"


class PaymentReminderLogItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    at: AwareDatetime
    type: Type9
    days_overdue: int | None = Field(None, ge=0)
    note: str | None = None
    by_agent_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")


class EditType(StrEnum):
    MERGE_FIELD_OVERRIDE = "merge_field_override"
    LINE_ITEM_EDIT = "line_item_edit"
    AMOUNTS_OVERRIDE = "amounts_override"
    COMPOSED_MARKDOWN_EDIT = "composed_markdown_edit"
    PAYMENT_STATE_UPDATE = "payment_state_update"
    PAYMENT_REMINDER_ADDED = "payment_reminder_added"


class AgentEdit(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    edit_id: str = Field(..., pattern="^edit_[a-z0-9]+$")
    edited_at: AwareDatetime
    edited_by_agent_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    edit_type: EditType
    target: str
    before_excerpt: str | None = None
    after_excerpt: str | None = None


class InvoicePack(BaseModel):
    """
    Phase 4.8 — a versioned invoice generated from the deal's contract-derived invoice schedule + agency invoice template. Lighter weight than contract pack (most fields deterministic; 0-1 LLM passes). Multiple invoice packs per deal supported via `deal.close.invoice_schedule[]` (e.g. 50/50 NET-30 produces 2 invoice packs). Each pack fires when its `trigger_condition` is met (contract_executed / all_deliverables_live / first_post_live / specific_date / manual). Agent reviews rendered PDF before sending. Sending is the approval — no separate gate (lighter than contract's legal review). Payment tracked manually in v0.1; v2 webhooks from Stripe/Xero/QuickBooks auto-populate. Stored at `data/deals/{deal_id}/invoice_packs/v{N}.json` (gitignored). See `docs/invoice_workflow.md`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: str | None = Field(None, alias="$schema")
    agency_id: UUID | None = Field(
        None,
        description="Multi-tenant scope: FK to agency_profile.agency_id. Optional in v0.1 (single-tenant deploys may omit); required in v2 SaaS. When present, all cross-record queries MUST filter by agency_id to prevent cross-tenant data leakage. See docs/data_lineage.md GAP-01/02 for rationale.",
    )
    invoice_pack_id: str = Field(
        ...,
        description="Globally unique. Format: `inv_{deal_id_short}_seq{N}_v{M}` where N is the schedule_sequence (which entry in invoice_schedule this fulfils) and M is the version (revisions to this specific invoice). Example: `inv_2026_q2_alo-yoga_jane-doe_seq2_v1` = second scheduled invoice for the deal, first version.",
        pattern="^inv_[a-z0-9_-]+_seq[0-9]+_v[0-9]+$",
    )
    deal_id: str = Field(..., pattern="^deal_pipeline_[a-z0-9_-]+$")
    schedule_sequence: int = Field(
        ...,
        description="Which entry in `deal.close.invoice_schedule[]` this invoice fulfils. For a single-invoice deal this is always 1. For 50/50 split it's 1 (upfront) or 2 (completion).",
        ge=1,
    )
    version: int = Field(..., ge=1)
    parent_version: int | None = Field(None, ge=1)
    is_latest: bool = Field(
        ...,
        description="Exactly one is_latest=true per (deal_id, schedule_sequence). When a v2 of invoice seq=2 is generated, v1 of seq=2 flips to false but v1 of seq=1 is untouched.",
    )
    generation: Generation
    context_snapshot: ContextSnapshot
    merge_field_values: list[MergeFieldValue] = Field(
        ...,
        description="Same shape as contract_pack.merge_field_values[]. Each value tagged with field, value, source, confidence. Invoice merge fields are highly deterministic (legal names, amounts, dates pulled from contract + talent + agency) — `low`/`missing` confidence on critical fields surfaces before send.",
    )
    line_items: list[LineItem] = Field(
        ...,
        description="Line items composing the invoice. Auto-generated from the schedule entry's percentage applied to deal.proposal.fee_usd, broken down per deliverable. LLM optionally drafts the `description` text if the agency template uses `{{narrative_line_items}}` placeholder.",
        min_length=1,
    )
    amounts: Amounts = Field(
        ...,
        description="Computed totals. subtotal_usd = sum of line_items[].amount_usd. tax handling per agency_profile.invoice_template.tax_handling.",
    )
    composed_markdown: str | None = Field(
        None,
        description="Final composed invoice markdown — agency template with merge fields substituted, line_items table inserted, amounts table inserted, payment instructions appended. Source-of-truth for the PDF render.",
    )
    agent_review: AgentReview = Field(
        ...,
        description="Soft gate. Agent reviews rendered PDF + can edit any merge field / line item / template content. Edits regenerate the PDF. Clicking 'Send' sets sent_at — sending IS the approval (no separate 'approve' event like contracts). All fields optional — absence of `sent_at` means the invoice is still in draft.",
    )
    export_artifacts: list[ExportArtifact] | None = None
    payment_state: PaymentState = Field(
        ...,
        description="Payment lifecycle for this specific invoice. Multiple invoice packs per deal each track independently. The deal's auto-archive trigger requires ALL invoices to have status=paid.",
    )
    payment_reminder_log: list[PaymentReminderLogItem] | None = Field(
        None,
        description="Audit trail of overdue follow-ups. Daily overdue cron appends `agent_notification` entries; agent appends `agent_email_sent` / `phone_followup` / `escalation` entries when they act.",
    )
    agent_edits: list[AgentEdit] | None = Field(
        None,
        description="Direct edits to invoice fields. Edits before send don't increment version (draft mutability). Edits after send create a new version (sent invoices are immutable — must void + re-issue).",
    )
    created_at: AwareDatetime
    updated_at: AwareDatetime | None = None
