# generated by datamodel-codegen:
#   filename:  memo.schema.json
#   timestamp: 2026-06-01T11:52:22+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Scope(StrEnum):
    """
    How broadly this memo applies. deal_specific: only relevant to one deal (e.g. 'agent regenerated slide 4 with feedback X'). brand_relationship: relevant whenever this brand surfaces (e.g. 'Brand X requires GDPR addendum on all contracts'). industry_pattern: pattern observed across multiple brands in an industry. talent_pattern: pattern about a specific talent's deals/preferences. cross_cutting: applies across deals/brands/industries (e.g. 'whitelisting > 60d is usually a redline').
    """

    DEAL_SPECIFIC = "deal_specific"
    BRAND_RELATIONSHIP = "brand_relationship"
    INDUSTRY_PATTERN = "industry_pattern"
    TALENT_PATTERN = "talent_pattern"
    CROSS_CUTTING = "cross_cutting"


class MemoType(StrEnum):
    """
    What kind of memo this is. Drives downstream retrieval — e.g. the proposal pack's writer subagent queries `objection_handler` + `negotiation_pattern` memos for this brand to inform commercial proposal rationale.
    """

    DEAL_SUMMARY = "deal_summary"
    BRAND_OBSERVATION = "brand_observation"
    NEGOTIATION_PATTERN = "negotiation_pattern"
    KPI_PATTERN = "kpi_pattern"
    OBJECTION_HANDLER = "objection_handler"
    CREATIVE_INSIGHT = "creative_insight"
    TALENT_LEARNING = "talent_learning"
    INDUSTRY_INSIGHT = "industry_insight"
    AGENT_DECISION_AUDIT = "agent_decision_audit"
    OTHER = "other"


class TalentId(RootModel[str]):
    root: str = Field(..., pattern="^[a-z0-9][a-z0-9-]*$")


class BrandId(RootModel[str]):
    root: str = Field(..., pattern="^[a-z0-9][a-z0-9-]*$")


class IndustryId(RootModel[str]):
    root: str = Field(..., pattern="^[a-z0-9][a-z0-9-]*$")


class DealIds(RootModel[str]):
    root: str = Field(..., pattern="^deal_pipeline_[a-z0-9_-]+$")


class DealIds1(RootModel[str]):
    root: str = Field(..., pattern="^deal_[a-z0-9_-]+$")


class PhaseContext(StrEnum):
    """
    Which phase of the deal lifecycle was active when this memo was written. cross_phase = memo intentionally spans phases (e.g. 'this brand's contract negotiation always slows delivery by 2 weeks').
    """

    LEAD = "lead"
    PROPOSAL = "proposal"
    CONTRACT = "contract"
    DELIVERY = "delivery"
    CLOSE = "close"
    CROSS_PHASE = "cross_phase"


class Tags(BaseModel):
    """
    Tag filters drive retrieval. The orchestrator and subagents query `read_memos(...)` with combinations of these tags. Multiple values per tag = OR; multiple tag keys = AND.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    talent_ids: list[TalentId] | None = Field(
        None,
        description="Talent slugs this memo references. Empty = not talent-specific.",
    )
    brand_ids: list[BrandId] | None = Field(
        None,
        description="Brand slugs this memo references. Empty = not brand-specific.",
    )
    industry_ids: list[IndustryId] | None = Field(
        None,
        description="Industry slugs this memo applies to. Empty = not industry-specific. Often populated even when memo is brand-specific (broader retrieval surface for cross-brand learning).",
    )
    deal_ids: list[DealIds | DealIds1] | None = Field(
        None,
        description="Deal IDs this memo references. Supports both pipeline (`deal_pipeline_*`) and archived (`deal_*`) deal_id formats.",
    )
    topics: list[str] = Field(
        ...,
        description="Free-form topic tags for fuzzy semantic matching. Convention: lowercase, kebab-case (e.g. 'exclusivity', 'payment-terms', 'usage-rights', 'gdpr', 'audience-mismatch', 'red-line-breach', 'kpi-overperformance'). Required (at least 1) to encourage explicit categorisation.",
        min_length=1,
    )
    phase_context: PhaseContext | None = Field(
        None,
        description="Which phase of the deal lifecycle was active when this memo was written. cross_phase = memo intentionally spans phases (e.g. 'this brand's contract negotiation always slows delivery by 2 weeks').",
    )


class CreatedByAgent(StrEnum):
    """
    Which agent (or human) authored the memo. `human_agent` = the user manually wrote it via the UI. `renderer` is included for completeness but rarely writes memos (deterministic agent, few learnings).
    """

    DEAL_ORCHESTRATOR = "deal_orchestrator"
    RESEARCHER = "researcher"
    WRITER = "writer"
    EXTRACTOR = "extractor"
    RENDERER = "renderer"
    HUMAN_AGENT = "human_agent"


class Memo(BaseModel):
    """
    Cross-invocation memory store for agents. Any subagent (researcher / writer / extractor / renderer) or the deal_orchestrator coordinator can write memos summarising learnings, observations, or patterns. Future agent invocations retrieve memos via the `read_memos` tool using tag filters (talent_id, brand_id, industry_id, deal_id, topics, scope). Persistence is intentionally cross-scope: a memo written during a Phase 4.7 contract negotiation for one brand may surface later when prepping a proposal for a competitor in the same industry. v0.1 = explicit write + deterministic tag-filter retrieval (no vector embedding); v0.2 may add pgvector for semantic retrieval. Stored as a row in Postgres + (optionally) markdown content blobs in S3 if length exceeds DB threshold. See `docs/architecture.md` § 5 Memo store.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: str | None = Field(None, alias="$schema")
    agency_id: UUID | None = Field(
        None,
        description="Multi-tenant scope: FK to agency_profile.agency_id. Optional in v0.1 (single-tenant deploys may omit); required in v2 SaaS. When present, all cross-record queries MUST filter by agency_id to prevent cross-tenant data leakage. See docs/data_lineage.md GAP-01/02 for rationale.",
    )
    memo_id: str = Field(
        ...,
        description="Globally unique. Format: `memo_{nanoid}`.",
        pattern="^memo_[a-z0-9]+$",
    )
    scope: Scope = Field(
        ...,
        description="How broadly this memo applies. deal_specific: only relevant to one deal (e.g. 'agent regenerated slide 4 with feedback X'). brand_relationship: relevant whenever this brand surfaces (e.g. 'Brand X requires GDPR addendum on all contracts'). industry_pattern: pattern observed across multiple brands in an industry. talent_pattern: pattern about a specific talent's deals/preferences. cross_cutting: applies across deals/brands/industries (e.g. 'whitelisting > 60d is usually a redline').",
    )
    memo_type: MemoType = Field(
        ...,
        description="What kind of memo this is. Drives downstream retrieval — e.g. the proposal pack's writer subagent queries `objection_handler` + `negotiation_pattern` memos for this brand to inform commercial proposal rationale.",
    )
    content_markdown: str = Field(
        ...,
        description="The memo body in markdown. Typically 1-5 paragraphs; targets agent consumption (concise, factual, action-oriented). Inline up to MEMO_INLINE_MAX_KB (default 32kB; see docs/configuration.md). Larger memos in v0.2 may be stored in S3 with `content_markdown_s3_key` field overriding inline content; v0.1 = always inline (writes exceeding threshold are rejected with VALIDATION_ERROR rather than silently offloaded). See docs/data_lineage.md GAP-N6.",
        max_length=32768,
    )
    structured: dict[str, Any] | None = Field(
        None,
        description="Optional structured payload alongside the narrative content. Free-form per memo_type — e.g. for `negotiation_pattern` might contain `{redlines_received: [...], counter_offers: [...], final_terms: {...}}`. Schema validation is permissive (additionalProperties: true) to support memo-type evolution.",
    )
    tags: Tags = Field(
        ...,
        description="Tag filters drive retrieval. The orchestrator and subagents query `read_memos(...)` with combinations of these tags. Multiple values per tag = OR; multiple tag keys = AND.",
    )
    created_by_agent: CreatedByAgent = Field(
        ...,
        description="Which agent (or human) authored the memo. `human_agent` = the user manually wrote it via the UI. `renderer` is included for completeness but rarely writes memos (deterministic agent, few learnings).",
    )
    created_in_pack_id: str | None = Field(
        None,
        description="If the memo was written during a pack generation, captures the pack_id (`prep_*` / `pp_*` / `cp_*` / `inv_*_seq*_v*` / `perf_*`). Null for orchestrator-level memos or human-written memos.",
    )
    created_at: AwareDatetime
    updated_at: AwareDatetime | None = None
    supersedes_memo_id: str | None = Field(
        None,
        description="Optional FK to a prior memo this one replaces. The superseded memo's `is_active` flips to false on the orchestrator's next write. Used when a learning evolves (e.g. v1 said 'Brand X never accepts 90d whitelisting'; v2 corrects after they did).",
        pattern="^memo_[a-z0-9]+$",
    )
    expires_at: AwareDatetime | None = Field(
        None,
        description="Optional TTL. After this timestamp, the memo is no longer surfaced by `read_memos` (filtered server-side). Useful for time-bound observations (e.g. 'Brand X paused all influencer campaigns Q3 2026' — expires when Q3 ends).",
    )
    is_active: bool | None = Field(
        True,
        description="Soft-delete flag. Inactive memos are excluded from `read_memos` by default but preserved for audit. Flipped to false when superseded or when an agent/human marks the memo as no-longer-valid.",
    )
    retrieval_count: int | None = Field(
        0,
        description="How many times this memo has been returned by `read_memos`. Auto-incremented. Useful signal: high-retrieval memos are validated learnings; never-retrieved memos may be noise.",
        ge=0,
    )
    last_retrieved_at: AwareDatetime | None = Field(
        None,
        description="Most recent time `read_memos` returned this memo. Stale memos (never retrieved in N months) become v0.2 cleanup candidates.",
    )
