# generated by datamodel-codegen:
#   filename:  performance_report_pack.schema.json
#   timestamp: 2026-05-27T21:00:44+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    RootModel,
)

from ._shared import kpi_metric_schema


class Trigger(StrEnum):
    """
    auto_on_performance_window_end: cron fired generation when `performance_capture_window_ends_at` reached. agent_initiated: agent fired before window end (rare). agent_*regenerate: NL feedback regen. kpi_refresh: cron re-fired because new KPI data arrived after initial generation (e.g. platform API late-reporting).
    """

    AUTO_ON_PERFORMANCE_WINDOW_END = "auto_on_performance_window_end"
    AGENT_INITIATED = "agent_initiated"
    AGENT_FULL_REGENERATE = "agent_full_regenerate"
    AGENT_SECTION_REGENERATE = "agent_section_regenerate"
    KPI_REFRESH = "kpi_refresh"


class PassName(StrEnum):
    KPI_AGGREGATION = "kpi_aggregation"
    BENCHMARK_COMPARISON = "benchmark_comparison"
    NARRATIVE_EXECUTIVE_SUMMARY = "narrative_executive_summary"
    NARRATIVE_WHAT_WORKED = "narrative_what_worked"
    NARRATIVE_LEARNINGS = "narrative_learnings"
    COMPOSE = "compose"
    SECTION_REGEN = "section_regen"


class LlmPass(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pass_name: PassName
    model: str | None = None
    input_tokens: int = Field(..., ge=0)
    output_tokens: int = Field(..., ge=0)
    cached_tokens: int | None = Field(None, ge=0)
    cost_usd: float | None = Field(None, ge=0.0)
    duration_ms: int | None = Field(None, ge=0)


class Generation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trigger: Trigger = Field(
        ...,
        description="auto_on_performance_window_end: cron fired generation when `performance_capture_window_ends_at` reached. agent_initiated: agent fired before window end (rare). agent_*regenerate: NL feedback regen. kpi_refresh: cron re-fired because new KPI data arrived after initial generation (e.g. platform API late-reporting).",
    )
    pre_generation_guidance: str | None = Field(
        None, description="Free-text guidance from agent before generation."
    )
    regeneration_feedback: str | None = Field(
        None, description="NL feedback on parent version."
    )
    target_sections: list[str] | None = None
    fired_at: AwareDatetime | None = None
    generated_at: AwareDatetime
    generated_by_agent_id: str | None = Field(
        None,
        description="Null if cron-triggered (auto_on_performance_window_end / kpi_refresh).",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    llm_model: str | None = None
    llm_passes: list[LlmPass] | None = None


class ComparableBrandDealsForBenchmarkItem(RootModel[str]):
    root: str = Field(..., pattern="^deal_[a-z0-9_-]+$")


class PlatformApisUsedEnum(StrEnum):
    META_GRAPH = "meta_graph"
    TIKTOK_DISPLAY = "tiktok_display"
    YOUTUBE_DATA = "youtube_data"
    LINKEDIN_MARKETING = "linkedin_marketing"
    TWITTER_API = "twitter_api"
    PHYLLO = "phyllo"
    MANUAL_ENTRY = "manual_entry"


class ContextSnapshot(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    captured_at: AwareDatetime
    contract_pack_id_at_gen: str | None = Field(
        None,
        description="Which executed contract this report measures performance against.",
        pattern="^cp_[a-z0-9_-]+_v[0-9]+$",
    )
    proposal_pack_id_at_gen: str | None = Field(
        None,
        description="Which proposal pack defined the brand's stated objectives (for `vs_brand_stated_targets` benchmark).",
        pattern="^pp_[a-z0-9_-]+_v[0-9]+$",
    )
    deal_proposal_snapshot: dict[str, Any] | None = Field(
        None,
        description="Frozen copy of relevant `deal.proposal.*` fields (fee_usd, deliverables[], usage_rights_granted, exclusivity) for performance vs. spend analysis.",
    )
    discovery_debrief_snapshot: dict[str, Any] | None = Field(
        None,
        description="Frozen copy of `deal.lead.discovery_debrief.objectives_heard[]` so the report can measure against what the brand actually said they wanted.",
    )
    performance_capture_window_starts_at: AwareDatetime | None = None
    performance_capture_window_ends_at: AwareDatetime | None = None
    comparable_brand_deals_for_benchmark: (
        list[ComparableBrandDealsForBenchmarkItem] | None
    ) = Field(
        None,
        description="FK list to past `brand_deals` records used for `vs_talent_historical` benchmark (same talent's prior similar deals).",
    )
    platform_apis_used: list[PlatformApisUsedEnum] | None = Field(
        None,
        description="Which platform APIs the KPI capture cron pulled from. Manual entry recorded when API was unavailable or talent's account wasn't connected.",
    )


class Platform(StrEnum):
    INSTAGRAM = "instagram"
    TIKTOK = "tiktok"
    YOUTUBE = "youtube"
    TWITTER_X = "twitter_x"
    LINKEDIN = "linkedin"
    PINTEREST = "pinterest"
    TWITCH = "twitch"
    SNAPCHAT = "snapchat"
    FACEBOOK = "facebook"
    SUBSTACK = "substack"
    PODCAST = "podcast"
    OTHER = "other"


class CaptureMethod(StrEnum):
    META_GRAPH_INSIGHTS = "meta_graph_insights"
    TIKTOK_DISPLAY_METRICS = "tiktok_display_metrics"
    YOUTUBE_ANALYTICS = "youtube_analytics"
    LINKEDIN_ANALYTICS = "linkedin_analytics"
    TWITTER_ANALYTICS = "twitter_analytics"
    PHYLLO = "phyllo"
    MANUAL_ENTRY = "manual_entry"
    BRAND_REPORTED = "brand_reported"


class Placeholder(StrEnum):
    EXECUTIVE_SUMMARY = "executive_summary"
    WHAT_WORKED = "what_worked"
    LEARNINGS = "learnings"
    AUDIENCE_RESONANCE = "audience_resonance"
    CREATIVE_OBSERVATIONS = "creative_observations"
    CUSTOM = "custom"


class NarrativeSection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    placeholder: Placeholder
    content: str
    sources: list[str] | None = Field(
        None,
        description="Context paths drawn from (e.g. 'kpis.reach', 'per_post_kpis[0].kpis.engagement_rate_pct').",
    )
    word_count: int | None = Field(None, ge=0)
    agent_edited: bool | None = False
    agent_edited_at: AwareDatetime | None = None


class SendMethod(StrEnum):
    MANUAL_EMAIL = "manual_email"
    SHARED_LINK = "shared_link"
    STRIPE_DASHBOARD = "stripe_dashboard"
    OTHER = "other"


class AgentReview(BaseModel):
    """
    Soft gate. Agent reviews rendered PDF before sending. Sending sets sent_at and triggers the downstream writes (final_performance_report_attachment_id + final_kpis on deal.close). All fields optional — absence of sent_at means the report is in draft.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    viewed_at: AwareDatetime | None = None
    sent_at: AwareDatetime | None = Field(
        None,
        description="When agent sent report to brand. Setting this auto-populates `deal.close.final_performance_report_attachment_id` (= report.pdf path) AND copies this pack's `kpis` into `deal.close.final_kpis`. If `deal.close.all_invoices_paid_at` is also set, auto-archive fires.",
    )
    sent_by_agent_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    send_method: SendMethod | None = "manual_email"
    sent_to_email: EmailStr | None = None


class Type(StrEnum):
    REPORT_MD = "report_md"
    REPORT_PDF = "report_pdf"
    REPORT_HTML = "report_html"


class Status(StrEnum):
    RENDERED = "rendered"
    PENDING = "pending"
    FAILED = "failed"


class RenderedBy(StrEnum):
    MARKDOWN_WRITER = "markdown_writer"
    PUPPETEER_PDF = "puppeteer_pdf"
    PANDOC = "pandoc"
    JINJA2_HTML = "jinja2_html"


class ExportArtifact(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type
    status: Status
    path: str | None = None
    size_bytes: int | None = Field(None, ge=0)
    rendered_at: AwareDatetime | None = None
    rendered_by: RenderedBy | None = None
    error: str | None = None


class EditType(StrEnum):
    KPI_OVERRIDE = "kpi_override"
    NARRATIVE_EDIT = "narrative_edit"
    BENCHMARK_OVERRIDE = "benchmark_override"
    COMPOSED_MARKDOWN_EDIT = "composed_markdown_edit"


class AgentEdit(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    edit_id: str = Field(..., pattern="^edit_[a-z0-9]+$")
    edited_at: AwareDatetime
    edited_by_agent_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    edit_type: EditType
    target: str
    before_excerpt: str | None = None
    after_excerpt: str | None = None


class KpiMetric(RootModel[kpi_metric_schema.KpiMetric]):
    root: kpi_metric_schema.KpiMetric


class BenchmarkComparison(BaseModel):
    """
    One KPI's comparison against one benchmark set.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    this_campaign_value: float | None = None
    benchmark_value: float | None = None
    delta_pct: float | None = Field(
        None, description="Percentage delta (e.g. +29.4 = 29.4% above benchmark)."
    )
    performance_label: str | None = Field(
        None,
        description="Human-readable summary, e.g. '2.3x category average', '+29% vs talent's historical', '94% of target'. Rendered directly into the report.",
    )
    benchmark_source: str | None = Field(
        None,
        description="What the benchmark was. For vs_industry: source data file. For vs_talent_historical: list of deal_ids averaged. For vs_brand_stated_targets: where in the debrief the target was stated.",
    )


class Kpis(BaseModel):
    """
    Aggregate final KPIs across all deliverables. Each metric carries source provenance per honesty-floor. Shape mirrors `brand_deal.kpis` from Phase 1.5 — on agent send, these values copy verbatim into `deal.close.final_kpis` (which then carries into brand_deal.kpis on auto-archive).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    reach: KpiMetric | None = None
    impressions: KpiMetric | None = None
    engagement_total: KpiMetric | None = None
    engagement_rate_pct: KpiMetric | None = None
    video_views: KpiMetric | None = None
    video_completion_rate_pct: KpiMetric | None = None
    avg_watch_time_seconds: KpiMetric | None = None
    likes: KpiMetric | None = None
    comments: KpiMetric | None = None
    shares: KpiMetric | None = None
    saves: KpiMetric | None = None
    link_clicks: KpiMetric | None = None
    ctr_pct: KpiMetric | None = None
    conversions: KpiMetric | None = None
    sales_attributed_usd: KpiMetric | None = None
    new_followers_for_brand: KpiMetric | None = None
    promo_code_redemptions: KpiMetric | None = None
    cpm_usd: KpiMetric | None = None
    cpe_usd: KpiMetric | None = None
    cpv_usd: KpiMetric | None = None
    emv_usd: KpiMetric | None = None


class PerPostKpi(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    post_url: AnyUrl
    deliverable_ref: str = Field(
        ...,
        description="Matches the deliverable_ref in `deal.delivery.posting_schedule[]`.",
    )
    platform: Platform
    posted_at: AwareDatetime | None = None
    captured_at: AwareDatetime | None = Field(
        None,
        description="When this post's KPIs were last refreshed from the platform API.",
    )
    capture_method: CaptureMethod | None = None
    kpis: dict[str, KpiMetric] = Field(
        ..., description="Per-post KPIs. Same kpiMetric shape as the aggregate block."
    )


class BenchmarkComparisons(BaseModel):
    """
    Per-KPI comparison against three benchmark sets. Computed at generation time. Each entry is human-readable for direct rendering into the report.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    vs_industry: dict[str, BenchmarkComparison] | None = Field(
        None,
        description="Per-KPI comparison against industry benchmarks (from `data/industry_kpi_benchmarks.json` — v2 data file). Map keys = KPI names (matching `kpis.*`); values = comparison record.",
    )
    vs_talent_historical: dict[str, BenchmarkComparison] | None = Field(
        None,
        description="Per-KPI comparison against the talent's average across `comparable_brand_deals_for_benchmark[]`. Same shape as vs_industry.",
    )
    vs_brand_stated_targets: dict[str, BenchmarkComparison] | None = Field(
        None,
        description="Per-KPI comparison against brand's stated targets (extracted from `discovery_debrief.objectives_heard[]` or proposal's commercial rationale). Often empty if brand didn't specify numeric targets.",
    )


class PerformanceReportPack(BaseModel):
    """
    Phase 4.9 — the post-campaign performance report generated when the deal's `performance_capture_window_ends_at` is reached. Aggregates KPIs captured during the performance window (from `deal.delivery.interim_kpi_snapshots[]`) into a final snapshot + benchmark comparisons + LLM-drafted narrative analysis. Soft agent gate; sending IS approval. On send, `deal.close.final_performance_report_attachment_id` + `deal.close.final_kpis` are auto-populated — both required for the deal's auto-archive into Phase 1.5 brand_deals. Stored at `data/deals/{deal_id}/performance_report_packs/v{N}.json` (gitignored). See `docs/performance_report_workflow.md`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: str | None = Field(None, alias="$schema")
    agency_id: UUID | None = Field(
        None,
        description="Multi-tenant scope: FK to agency_profile.agency_id. Optional in v0.1 (single-tenant deploys may omit); required in v2 SaaS. When present, all cross-record queries MUST filter by agency_id to prevent cross-tenant data leakage. See docs/data_lineage.md GAP-01/02 for rationale.",
    )
    performance_report_pack_id: str = Field(
        ...,
        description="Globally unique. Format: `perf_{deal_id_short}_v{N}`. The `perf_` prefix distinguishes from prep / proposal / contract / invoice packs.",
        pattern="^perf_[a-z0-9_-]+_v[0-9]+$",
    )
    deal_id: str = Field(..., pattern="^deal_pipeline_[a-z0-9_-]+$")
    version: int = Field(..., ge=1)
    parent_version: int | None = Field(None, ge=1)
    is_latest: bool
    generation: Generation
    context_snapshot: ContextSnapshot
    kpis: Kpis = Field(
        ...,
        description="Aggregate final KPIs across all deliverables. Each metric carries source provenance per honesty-floor. Shape mirrors `brand_deal.kpis` from Phase 1.5 — on agent send, these values copy verbatim into `deal.close.final_kpis` (which then carries into brand_deal.kpis on auto-archive).",
    )
    per_post_kpis: list[PerPostKpi] | None = Field(
        None,
        description="Per-deliverable KPI breakdown. Each post in the campaign gets its own row with platform-Insights-fetched metrics + capture timestamp. Aggregate sums into the top-level `kpis` block.",
    )
    benchmark_comparisons: BenchmarkComparisons | None = Field(
        None,
        description="Per-KPI comparison against three benchmark sets. Computed at generation time. Each entry is human-readable for direct rendering into the report.",
    )
    narrative_sections: list[NarrativeSection] | None = Field(
        None,
        description="LLM-drafted prose. Default sections: executive_summary (3-line top-line outcome) + what_worked (which deliverables outperformed + why) + learnings (recommendations for future campaigns). Each section cites context paths it drew from.",
    )
    composed_markdown: str | None = Field(
        None,
        description="Final assembled report markdown (executive summary + KPI tables + benchmark callouts + narrative sections + per-post breakdown). Source-of-truth for the PDF render.",
    )
    agent_review: AgentReview | None = Field(
        None,
        description="Soft gate. Agent reviews rendered PDF before sending. Sending sets sent_at and triggers the downstream writes (final_performance_report_attachment_id + final_kpis on deal.close). All fields optional — absence of sent_at means the report is in draft.",
    )
    export_artifacts: list[ExportArtifact] | None = None
    agent_edits: list[AgentEdit] | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime | None = None
