# generated by datamodel-codegen:
#   filename:  pitch_enrollment.schema.json
#   timestamp: 2026-06-01T11:52:22+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum, StrEnum
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field


class State(StrEnum):
    """
    Lifecycle state. `drafted` = AI generated all steps, not approved; `awaiting_approval` = in review queue; `active` = approved and scheduled in Smartlead; `paused` = halted (e.g. by user or by reply on another sequence for the same contact); `completed` = all steps sent without kill; `killed` = stopped early (reply, bounce, unsubscribe, user-killed).
    """

    DRAFTED = "drafted"
    AWAITING_APPROVAL = "awaiting_approval"
    ACTIVE = "active"
    PAUSED = "paused"
    COMPLETED = "completed"
    KILLED = "killed"


class KillReason(Enum):
    """
    If state=killed, why.
    """

    NONE_TYPE_NONE = None
    REPLY_RECEIVED = "reply_received"
    BOUNCED = "bounced"
    UNSUBSCRIBED = "unsubscribed"
    USER_KILLED = "user_killed"
    CONTACT_LEFT_BRAND = "contact_left_brand"
    DO_NOT_CONTACT_SET = "do_not_contact_set"
    EXCLUSIVITY_CONFLICT_DETECTED = "exclusivity_conflict_detected"
    TALENT_PAUSED_OUTREACH = "talent_paused_outreach"


class SmartleadMeta(BaseModel):
    """
    Cross-references to the Smartlead campaign + lead that backs this enrollment.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    campaign_id: str | None = None
    lead_id: str | None = None
    sending_mailbox: str | None = Field(
        None,
        description="The talent's mailbox sending these emails (e.g. `jane@janedoetalent.com`).",
    )
    sending_domain: str | None = None


class ContextSnapshot(BaseModel):
    """
    Snapshot of the (talent, contact, brand) data the AI used at generation time. Stored for reproducibility — if we re-generate later, we can compare to see what changed. v0.1: hashes are populated by orchestrator on enrollment creation but no runtime reader exists yet. v0.2 will introduce a regeneration workflow that diffs against snapshotted_at + the three hashes to surface 'what changed since this enrollment was generated' as agent context. See `docs/data_lineage.md` GAP-12.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    talent_snapshot_hash: str | None = Field(
        None,
        description="SHA-256 of the talent profile fields used at generation time (canonicalised + hashed). Populated for v0.2 reproducibility tooling.",
    )
    contact_snapshot_hash: str | None = Field(
        None, description="SHA-256 of the brand_contact record used at generation time."
    )
    brand_snapshot_hash: str | None = Field(
        None,
        description="SHA-256 of the brand_industry_map entry used at generation time.",
    )
    snapshotted_at: AwareDatetime | None = None


class Status(StrEnum):
    PENDING_GENERATION = "pending_generation"
    DRAFTED = "drafted"
    AWAITING_APPROVAL = "awaiting_approval"
    SCHEDULED = "scheduled"
    SENT = "sent"
    DELIVERED = "delivered"
    SKIPPED = "skipped"
    KILLED = "killed"


class SkipReason(Enum):
    """
    If status=skipped, why.
    """

    NONE_TYPE_NONE = None
    BRANCHING_RULE_FIRED = "branching_rule_fired"
    USER_SKIPPED = "user_skipped"
    SCHEDULING_CONFLICT = "scheduling_conflict"


class Model(StrEnum):
    CLAUDE_SONNET_4_7 = "claude-sonnet-4-7"
    CLAUDE_HAIKU_4_5 = "claude-haiku-4-5"
    CLAUDE_OPUS_4_7 = "claude-opus-4-7"
    CLAUDE_SONNET_4_6 = "claude-sonnet-4-6"
    CLAUDE_HAIKU_4_5_20251001 = "claude-haiku-4-5-20251001"


class AnglesUsed(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    primary: str | None = Field(
        None, description="angle_id from `data/pitch_angles.json`."
    )
    supporting: str | None = Field(
        None, description="Optional second angle the LLM wove in."
    )
    candidates_considered: list[str] | None = Field(
        None,
        description="All angle_ids that fired their trigger and were offered to the LLM as candidates. Even un-picked ones logged for analytics.",
    )


class GenerationMeta(BaseModel):
    """
    Full provenance of how this step's content was produced. The auditable 'why' behind every email.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    generated_at: AwareDatetime | None = None
    model: Model | None = None
    prompt_tokens: int | None = Field(None, ge=0)
    completion_tokens: int | None = Field(None, ge=0)
    cost_usd: float | None = Field(None, ge=0.0)
    angles_used: AnglesUsed | None = None
    personalization_fields_used: list[str] | None = Field(
        None,
        description="Dot-paths into the (talent, contact, brand) data that were merged into the email. e.g. `contact.name.first`, `brand.recent_funding.round`.",
    )
    step_intent: str | None = Field(
        None,
        description="Intent from the template step (mirrored here for portability).",
    )
    prompt_hash: str | None = Field(
        None,
        description="SHA-256 of the exact prompt sent to the LLM. For reproducibility and de-dup detection.",
    )


class SubjectMeta(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    length_chars: int | None = None
    word_count: int | None = None
    has_question_mark: bool | None = None
    has_emoji: bool | None = None
    starts_with: str | None = Field(
        None, description="First word of the subject — useful for pattern analysis."
    )


class BodyMeta(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    length_chars: int | None = None
    word_count: int | None = None
    sentence_count: int | None = None
    link_count: int | None = None
    merge_field_count: int | None = Field(
        None, description="How many data fields were actually merged in."
    )
    reading_level: str | None = Field(
        None, description="e.g. 'grade_8' (Flesch-Kincaid bucket)."
    )


class GeneratedContent(BaseModel):
    """
    The actual subject + body that will be sent. Plus structural metadata for A/B analytics.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    subject: str
    body: str
    subject_meta: SubjectMeta | None = None
    body_meta: BodyMeta | None = None


class SmartleadStepMeta(BaseModel):
    """
    Per-step Smartlead identifiers + send context.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    smartlead_email_id: str | None = None
    sent_via_mailbox: str | None = None
    sent_at_utc: AwareDatetime | None = None
    sent_at_recipient_local: str | None = Field(
        None,
        description="Recipient-local time the email arrived — for time-of-day analytics.",
    )
    sender_domain_age_days: int | None = Field(
        None, description="How long the sending domain has been warmed up at send time."
    )
    sender_warmup_complete: bool | None = None


class Event(StrEnum):
    DELIVERED = "delivered"
    OPENED = "opened"
    CLICKED = "clicked"
    REPLIED = "replied"
    BOUNCED = "bounced"
    UNSUBSCRIBED = "unsubscribed"


class EngagementEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    event: Event
    at: AwareDatetime
    ip_country: str | None = Field(None, pattern="^[A-Z]{2}$")
    client_inferred: str | None = Field(
        None,
        description="Inferred email client (Apple Mail, Outlook, Gmail Web, etc.) from User-Agent.",
    )
    likely_mpp: bool | None = Field(
        None,
        description="True if this open event looks like Apple Mail Privacy Protection pre-loading the tracking pixel (vs a real human read). Filtered out of `human_opens` count.",
    )
    url: AnyUrl | None = Field(
        None, description="For click events — which URL was clicked."
    )
    bounce_code: str | None = Field(
        None,
        description="For bounce events — SMTP error code (5.x.x = hard, 4.x.x = soft).",
    )
    reply_length_chars: int | None = Field(
        None,
        description="For reply events — length of the reply body (proxy for engagement depth).",
    )
    raw_payload_id: str | None = Field(
        None,
        description="Reference to the full Smartlead webhook payload (stored separately for forensic value).",
    )


class BounceType(Enum):
    NONE_TYPE_NONE = None
    HARD = "hard"
    SOFT = "soft"


class EngagementSummary(BaseModel):
    """
    Pre-computed aggregates over `engagement_events[]`. Refreshed every time a new event arrives.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    opens_total: int | None = Field(None, ge=0)
    human_opens: int | None = Field(
        None,
        description="Opens excluding `likely_mpp: true` events. The honest open metric in 2026.",
        ge=0,
    )
    clicks_total: int | None = Field(None, ge=0)
    unique_clicks: int | None = Field(None, ge=0)
    replied: bool | None = None
    bounced: bool | None = None
    bounce_type: BounceType | None = None
    unsubscribed: bool | None = None
    first_human_open_at: AwareDatetime | None = None
    first_click_at: AwareDatetime | None = None
    replied_at: AwareDatetime | None = None
    time_to_first_human_open_seconds: int | None = Field(None, ge=0)
    time_to_reply_seconds: int | None = Field(None, ge=0)


class Outcome(StrEnum):
    """
    Headline classification. `interested` is the conversion-leading-indicator metric tracked in analytics.
    """

    INTERESTED = "interested"
    DECLINED = "declined"
    OUT_OF_OFFICE = "out_of_office"
    UNRELATED = "unrelated"
    UNSUBSCRIBE_REQUEST = "unsubscribe_request"
    NEEDS_MORE_INFO = "needs_more_info"
    WRONG_PERSON_ROUTED = "wrong_person_routed"


class ExtractedSignals(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asked_for_pricing: bool | None = None
    asked_for_meeting: bool | None = None
    asked_for_more_info: bool | None = None
    objections_raised: list[str] | None = None
    next_step_proposed: str | None = None
    ooo_until: date_aliased | None = None
    routed_to_contact: str | None = Field(
        None, description="If they routed us to someone else, the named person/email."
    )


class OutcomeClassification(BaseModel):
    """
    LLM-classified intent of the reply. Populated only when a reply was received. Drives kill-vs-continue decisions and powers the positive_reply_rate metric.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    outcome: Outcome | None = Field(
        None,
        description="Headline classification. `interested` is the conversion-leading-indicator metric tracked in analytics.",
    )
    classified_by: str | None = Field(
        None, description="Model used for classification (typically claude-haiku-4-5)."
    )
    classified_at: AwareDatetime | None = None
    confidence: float | None = Field(None, ge=0.0, le=1.0)
    rationale: str | None = Field(
        None, description="One-line LLM explanation of the classification."
    )
    extracted_signals: ExtractedSignals | None = None


class Step(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    step_number: int = Field(..., ge=1, le=10)
    status: Status
    scheduled_for: AwareDatetime | None = None
    sent_at: AwareDatetime | None = None
    generation_meta: GenerationMeta | None = None
    generated_content: GeneratedContent | None = None
    smartlead_step_meta: SmartleadStepMeta | None = None
    engagement_events: list[EngagementEvent] | None = None
    engagement_summary: EngagementSummary | None = None
    outcome_classification: OutcomeClassification | None = None
    skip_reason: SkipReason | None = Field(None, description="If status=skipped, why.")


class PitchEnrollment(BaseModel):
    """
    A running instance of a pitch_template for a specific (talent, contact) pair. Carries the AI-generated content per step, real-time engagement events from Smartlead webhooks, LLM-classified reply outcomes, and full provenance for A/B analytics. One file per enrollment under `data/pitch_enrollments/{enrollment_id}.json` (gitignored — generated artifact + contact PII). See `docs/outreach_workflow.md`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: str | None = Field(None, alias="$schema")
    agency_id: UUID | None = Field(
        None,
        description="Multi-tenant scope: FK to agency_profile.agency_id. Optional in v0.1 (single-tenant deploys may omit); required in v2 SaaS. When present, all cross-record queries MUST filter by agency_id to prevent cross-tenant data leakage. See docs/data_lineage.md GAP-01/02 for rationale.",
    )
    enrollment_id: str = Field(
        ...,
        description="Globally unique enrollment identifier. Format: `enr_{nanoid}`.",
        pattern="^enr_[a-z0-9]+$",
    )
    talent_id: str = Field(..., pattern="^[a-z0-9][a-z0-9-]*$")
    brand_id: str = Field(..., pattern="^[a-z0-9][a-z0-9-]*$")
    contact_id: str = Field(
        ...,
        description="FK to a contact in `data/brand_contacts/{brand_id}.json`.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    template_id: str = Field(..., pattern="^[a-z0-9][a-z0-9-]*$")
    state: State = Field(
        ...,
        description="Lifecycle state. `drafted` = AI generated all steps, not approved; `awaiting_approval` = in review queue; `active` = approved and scheduled in Smartlead; `paused` = halted (e.g. by user or by reply on another sequence for the same contact); `completed` = all steps sent without kill; `killed` = stopped early (reply, bounce, unsubscribe, user-killed).",
    )
    kill_reason: KillReason | None = Field(None, description="If state=killed, why.")
    killed_at: AwareDatetime | None = None
    created_deal_id: str | None = Field(
        None,
        description="FK to the Phase 4 deal (`data/deals/{deal_id}.json`) that this enrollment spawned via an `interested` reply classification. Populated by the orchestrator when the deal is created from this enrollment. Forms the bidirectional link with `deal.originating_enrollment_id` — anyone reviewing this enrollment can navigate forward to the resulting deal; anyone reviewing the deal can navigate back to the originating pitch. Absent if outcome was not `interested` (declined / unrelated / unresponsive enrollments never spawn deals).",
        pattern="^deal_pipeline_[a-z0-9_-]+$",
    )
    smartlead_meta: SmartleadMeta | None = Field(
        None,
        description="Cross-references to the Smartlead campaign + lead that backs this enrollment.",
    )
    steps: list[Step]
    context_snapshot: ContextSnapshot | None = Field(
        None,
        description="Snapshot of the (talent, contact, brand) data the AI used at generation time. Stored for reproducibility — if we re-generate later, we can compare to see what changed. v0.1: hashes are populated by orchestrator on enrollment creation but no runtime reader exists yet. v0.2 will introduce a regeneration workflow that diffs against snapshotted_at + the three hashes to surface 'what changed since this enrollment was generated' as agent context. See `docs/data_lineage.md` GAP-12.",
    )
    created_at: AwareDatetime
    updated_at: AwareDatetime | None = None
