# generated by datamodel-codegen:
#   filename:  pitch_template.schema.json
#   timestamp: 2026-05-27T21:00:44+00:00

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class TargetDecisionRole(StrEnum):
    """
    Which contact decision_role this template is designed for. The orchestrator routes contacts to templates automatically based on this field. `unknown` contacts default to the buyer template.
    """

    BUYER = "buyer"
    INFLUENCER = "influencer"
    GATEKEEPER = "gatekeeper"
    CHAMPION = "champion"


class SuccessCriteria(BaseModel):
    """
    Targets for this template's performance. Used in the UI to show whether the template is meeting its goal.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    target_reply_rate: float | None = Field(None, ge=0.0, le=1.0)
    target_positive_reply_rate: float | None = Field(None, ge=0.0, le=1.0)


class Tone(StrEnum):
    """
    Overall tone signal passed to the LLM. Tuned per template (buyer = direct_professional; champion = warm_casual; gatekeeper = brief_courteous).
    """

    DIRECT_PROFESSIONAL = "direct_professional"
    WARM_CASUAL = "warm_casual"
    CONFIDENT_ENTHUSIASTIC = "confident_enthusiastic"
    BRIEF_COURTEOUS = "brief_courteous"


class Guardrails(BaseModel):
    """
    Hard rules the AI generation must respect across all steps of this template. Step 1 manual-approval is enforced system-wide and is NOT configurable here — see `docs/outreach_workflow.md` § Review-before-send queue.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    max_body_chars: int | None = Field(600, ge=100, le=2000)
    max_subject_chars: int | None = Field(60, ge=20, le=100)
    require_can_spam_unsubscribe: bool | None = True
    tone: Tone | None = Field(
        None,
        description="Overall tone signal passed to the LLM. Tuned per template (buyer = direct_professional; champion = warm_casual; gatekeeper = brief_courteous).",
    )


class Intent(StrEnum):
    """
    What this step is for. The LLM generation prompt is shaped by intent — e.g. `first_touch_strongest_angle` picks the highest-strength applicable angle; `break_up_door_open` is brief and leaves the door open without new asks.
    """

    FIRST_TOUCH_STRONGEST_ANGLE = "first_touch_strongest_angle"
    FOLLOW_UP_DIFFERENT_ANGLE = "follow_up_different_angle"
    FOLLOW_UP_WITH_CREATIVE_CONCEPT = "follow_up_with_creative_concept"
    FOLLOW_UP_WITH_PROOF_OR_CASE_STUDY = "follow_up_with_proof_or_case_study"
    SPECIFIC_ASK_WITH_PRICING = "specific_ask_with_pricing"
    BREAK_UP_DOOR_OPEN = "break_up_door_open"
    ROUTING_REQUEST = "routing_request"
    WARM_INTRO_REQUEST = "warm_intro_request"


class Channel(StrEnum):
    """
    Send channel for this step. v0.1 supports **email only**. LinkedIn outreach (`linkedin_message`, `linkedin_inmail`, `linkedin_connection`) is deferred to v2 — these values will be re-added to the enum when LinkedIn-send integration ships. Templates authored today must use `email` for every step.
    """

    EMAIL = "email"


class PreferredAngleCategory(StrEnum):
    COMPETITIVE_PROOF = "competitive_proof"
    SIMILAR_TALENT_PRECEDENT = "similar_talent_precedent"
    DEMOGRAPHIC_MATCH = "demographic_match"
    NICHE_FIT = "niche_fit"
    BRAND_MOMENTUM = "brand_momentum"
    GEOGRAPHIC_ALIGNMENT = "geographic_alignment"
    MUTUAL_CONNECTION = "mutual_connection"
    VALUES_ALIGNMENT = "values_alignment"
    RE_ENGAGEMENT = "re_engagement"
    PERFORMANCE_PROOF = "performance_proof"
    TIMELINESS = "timeliness"
    CREATIVE_CONCEPT = "creative_concept"
    INSIDER_OBSERVATION = "insider_observation"
    ROLE_DEFAULT = "role_default"
    COUNTER_POSITIONING = "counter_positioning"


class AiModelOverride(StrEnum):
    """
    Override default model. Defaults: step 1 = Sonnet (highest-value content); steps 2+ = Haiku (cost optimisation). Use Opus only for ultra-high-value pitches (e.g. premium-tier brands).
    """

    CLAUDE_SONNET_4_7 = "claude-sonnet-4-7"
    CLAUDE_HAIKU_4_5 = "claude-haiku-4-5"
    CLAUDE_OPUS_4_7 = "claude-opus-4-7"


class AiPromptOverrides(BaseModel):
    """
    Per-step prompt hints layered on top of the default per-intent prompt. Useful for talent-specific tone overrides without forking the template.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    tone_override: str | None = None
    must_include_phrases: list[str] | None = None
    must_exclude_phrases: list[str] | None = None
    include_attachment_reference: bool | None = None


class JumpToStepOnEngagementThreshold(BaseModel):
    """
    If cumulative engagement exceeds threshold, jump forward to a closing step.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    min_opens: int | None = None
    min_clicks: int | None = None
    jump_to_step_number: int | None = None


class Branching(BaseModel):
    """
    Conditional logic that may skip this step or redirect to a different step based on previous-step engagement.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    skip_if_prior_step_opened: bool | None = Field(
        False,
        description="If the previous step was opened but not replied to, skip this follow-up (gives them more time).",
    )
    skip_if_prior_step_clicked: bool | None = Field(
        False,
        description="If they clicked a link, skip this follow-up (high engagement; wait for reply).",
    )
    jump_to_step_on_engagement_threshold: JumpToStepOnEngagementThreshold | None = (
        Field(
            None,
            description="If cumulative engagement exceeds threshold, jump forward to a closing step.",
        )
    )


class Step(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    step_number: int = Field(
        ..., description="1-indexed step within the sequence.", ge=1, le=10
    )
    intent: Intent = Field(
        ...,
        description="What this step is for. The LLM generation prompt is shaped by intent — e.g. `first_touch_strongest_angle` picks the highest-strength applicable angle; `break_up_door_open` is brief and leaves the door open without new asks.",
    )
    timing_offset_days: int = Field(
        ...,
        description="Days after the PREVIOUS step (or after enrollment for step 1). Step 1 should be 0 (sent immediately). Typical cadence: 0, 3, 7, 14.",
        ge=0,
        le=90,
    )
    channel: Channel = Field(
        ...,
        description="Send channel for this step. v0.1 supports **email only**. LinkedIn outreach (`linkedin_message`, `linkedin_inmail`, `linkedin_connection`) is deferred to v2 — these values will be re-added to the enum when LinkedIn-send integration ships. Templates authored today must use `email` for every step.",
    )
    preferred_angle_categories: list[PreferredAngleCategory] | None = Field(
        None,
        description="Categories the LLM should prefer when picking the angle for this step. Empty array = no preference (LLM picks freely from all applicable).",
    )
    excluded_angle_categories: list[str] | None = Field(
        None,
        description="Categories the LLM must NOT pick for this step (typically used to force variation across steps — e.g. step 2 excludes whatever step 1 used).",
    )
    ai_model_override: AiModelOverride | None = Field(
        None,
        description="Override default model. Defaults: step 1 = Sonnet (highest-value content); steps 2+ = Haiku (cost optimisation). Use Opus only for ultra-high-value pitches (e.g. premium-tier brands).",
    )
    ai_prompt_overrides: AiPromptOverrides | None = Field(
        None,
        description="Per-step prompt hints layered on top of the default per-intent prompt. Useful for talent-specific tone overrides without forking the template.",
    )
    branching: Branching | None = Field(
        None,
        description="Conditional logic that may skip this step or redirect to a different step based on previous-step engagement.",
    )


class PitchTemplate(BaseModel):
    """
    Abstract sequence template — defines the STRUCTURE (steps, timing, intent per step, preferred angles) but not the per-contact CONTENT. Templates are reusable across talents + contacts. The AI generation step fills in subject + body per contact at send time, drawing from `data/pitch_angles.json`. See `docs/outreach_workflow.md`. Default templates ship at `data/pitch_templates/` (kept in repo for version-control of the playbook; per-agency customizations gitignored).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: str | None = Field(None, alias="$schema")
    agency_id: UUID | None = Field(
        None,
        description="Multi-tenant scope: FK to agency_profile.agency_id. Optional in v0.1 (single-tenant deploys may omit); required in v2 SaaS. When present, all cross-record queries MUST filter by agency_id to prevent cross-tenant data leakage. See docs/data_lineage.md GAP-01/02 for rationale.",
    )
    template_id: str = Field(
        ...,
        description="Stable kebab-case slug. e.g. `buyer-direct-pitch`.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    version: str
    name: str = Field(..., description="Short human-readable label.")
    description: str | None = None
    target_decision_role: TargetDecisionRole = Field(
        ...,
        description="Which contact decision_role this template is designed for. The orchestrator routes contacts to templates automatically based on this field. `unknown` contacts default to the buyer template.",
    )
    steps: list[Step] = Field(..., max_length=10, min_length=1)
    success_criteria: SuccessCriteria | None = Field(
        None,
        description="Targets for this template's performance. Used in the UI to show whether the template is meeting its goal.",
    )
    guardrails: Guardrails | None = Field(
        None,
        description="Hard rules the AI generation must respect across all steps of this template. Step 1 manual-approval is enforced system-wide and is NOT configurable here — see `docs/outreach_workflow.md` § Review-before-send queue.",
    )
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
