# generated by datamodel-codegen:
#   filename:  pitch_angle.schema.json
#   timestamp: 2026-06-01T11:52:22+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Category(StrEnum):
    """
    Grouping for UI + analytics aggregation.
    """

    COMPETITIVE_PROOF = "competitive_proof"
    SIMILAR_TALENT_PRECEDENT = "similar_talent_precedent"
    DEMOGRAPHIC_MATCH = "demographic_match"
    NICHE_FIT = "niche_fit"
    BRAND_MOMENTUM = "brand_momentum"
    GEOGRAPHIC_ALIGNMENT = "geographic_alignment"
    MUTUAL_CONNECTION = "mutual_connection"
    VALUES_ALIGNMENT = "values_alignment"
    RE_ENGAGEMENT = "re_engagement"
    PERFORMANCE_PROOF = "performance_proof"
    TIMELINESS = "timeliness"
    CREATIVE_CONCEPT = "creative_concept"
    INSIDER_OBSERVATION = "insider_observation"
    ROLE_DEFAULT = "role_default"
    COUNTER_POSITIONING = "counter_positioning"


class Type(StrEnum):
    """
    Type of trigger condition. The orchestrator has a Python function per type that returns {fires: bool, merge_field_values: {...}} given the (talent, contact, brand) context. New trigger types require both a code update and an enum extension.
    """

    TALENT_WORKED_WITH_COMPETITOR = "talent_worked_with_competitor"
    TALENT_WORKED_IN_SAME_INDUSTRY = "talent_worked_in_same_industry"
    TALENT_WORKED_IN_TERTIARY_INDUSTRY = "talent_worked_in_tertiary_industry"
    SIMILAR_TALENT_PARTNERED_WITH_BRAND = "similar_talent_partnered_with_brand"
    MULTIPLE_SIMILAR_TALENTS_WITH_BRAND = "multiple_similar_talents_with_brand"
    SIMILAR_TALENT_AT_COMPETITOR = "similar_talent_at_competitor"
    IAB_DEMOGRAPHIC_OVERLAP = "iab_demographic_overlap"
    GENDER_SKEW_MATCH = "gender_skew_match"
    AGE_BAND_MATCH = "age_band_match"
    NICHE_PRIMARY_AFFINITY = "niche_primary_affinity"
    NICHE_SPECIFIC_CONTENT_SERIES = "niche_specific_content_series"
    BRAND_RECENT_FUNDING = "brand_recent_funding"
    BRAND_NEW_PRODUCT_LAUNCH = "brand_new_product_launch"
    BRAND_TRENDING_30D = "brand_trending_30d"
    BRAND_MARKET_EXPANSION = "brand_market_expansion"
    BRAND_RECENT_PRESS_AWARD = "brand_recent_press_award"
    GEO_TOP_COUNTRY_MATCH = "geo_top_country_match"
    BRAND_HQ_MATCHES_AUDIENCE = "brand_hq_matches_audience"
    CHAMPION_CONTACT_AT_BRAND = "champion_contact_at_brand"
    AOR_PRIOR_RELATIONSHIP = "aor_prior_relationship"
    EVENT_ATTENDED_TOGETHER = "event_attended_together"
    VALUES_ALIGNED_SEARCH = "values_aligned_search"
    PAST_BRAND_ELIGIBLE_REENGAGEMENT = "past_brand_eligible_reengagement"
    SAME_CONTACT_POSITIVE_HISTORY = "same_contact_positive_history"
    RECENT_HIGH_PERFORMING_POST = "recent_high_performing_post"
    CASE_STUDY_AVAILABLE = "case_study_available"
    SEASONAL_WINDOW_MATCH = "seasonal_window_match"
    TALENT_UPCOMING_LAUNCH = "talent_upcoming_launch"
    AI_CREATIVE_CONCEPT = "ai_creative_concept"
    BRAND_CREATOR_GAP_IN_NICHE = "brand_creator_gap_in_niche"
    BRAND_CONTENT_FORMAT_GAP = "brand_content_format_gap"
    TALENT_IS_CUSTOMER = "talent_is_customer"
    ALWAYS_FOR_BUYER = "always_for_buyer"
    ALWAYS_FOR_INFLUENCER = "always_for_influencer"
    ALWAYS_FOR_GATEKEEPER = "always_for_gatekeeper"
    ALWAYS_FOR_CHAMPION = "always_for_champion"
    ACTIVE_EXCLUSIVITY_WORKAROUND = "active_exclusivity_workaround"
    TALENT_HAS_DEAL_WITH_STRONG_KPI = "talent_has_deal_with_strong_kpi"
    TALENT_HAS_RENEWED_DEAL = "talent_has_renewed_deal"
    TALENT_HAS_DEAL_WITH_CONVERSION_KPIS = "talent_has_deal_with_conversion_kpis"
    TALENT_HAS_HIGH_AUDIENCE_MATCH_PAST_CAMPAIGN = (
        "talent_has_high_audience_match_past_campaign"
    )
    TALENT_HAS_DEAL_BEATING_BENCHMARK = "talent_has_deal_beating_benchmark"


class Trigger(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type = Field(
        ...,
        description="Type of trigger condition. The orchestrator has a Python function per type that returns {fires: bool, merge_field_values: {...}} given the (talent, contact, brand) context. New trigger types require both a code update and an enum extension.",
    )
    config: dict[str, Any] | None = Field(
        None,
        description="Trigger-specific configuration. Free-form by design; each trigger type's evaluator interprets it.",
    )


class ApplicableToDecisionRole(StrEnum):
    BUYER = "buyer"
    INFLUENCER = "influencer"
    GATEKEEPER = "gatekeeper"
    CHAMPION = "champion"
    UNKNOWN = "unknown"


class ApplicableToStep(RootModel[int]):
    root: int = Field(..., ge=1, le=10)


class PairWellWithItem(RootModel[str]):
    root: str = Field(..., pattern="^[a-z0-9][a-z0-9_]*$")


class AvoidCombiningWithItem(RootModel[str]):
    root: str = Field(..., pattern="^[a-z0-9][a-z0-9_]*$")


class Angle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    angle_id: str = Field(
        ...,
        description="Stable snake_case identifier. Used in `pitch_enrollment.steps[].generation_meta.angles_used` for A/B analytics.",
        pattern="^[a-z0-9][a-z0-9_]*$",
    )
    category: Category = Field(
        ..., description="Grouping for UI + analytics aggregation."
    )
    name: str = Field(..., description="Short human-readable label.")
    description: str | None = Field(
        None, description="One-paragraph explanation of when and why this angle works."
    )
    trigger: Trigger
    applicable_to_decision_roles: list[ApplicableToDecisionRole] = Field(
        ...,
        description="Which `decision_role` values this angle can be used for. The 5-value taxonomy matches `schemas/brand_contact.schema.json`.",
        min_length=1,
    )
    applicable_to_steps: list[ApplicableToStep] = Field(
        ...,
        description="Which step numbers in a sequence this angle suits. Step 1 = first touch (strongest angles); later steps reserved for different angles to avoid repetition.",
        min_length=1,
    )
    authored_strength_score: float = Field(
        ...,
        description="Hand-authored expected effectiveness. Used by the orchestrator when ranking candidate angles for an email. Updated manually as the user learns what works (v0.1); auto-tuned from observed reply data in v2.",
        ge=0.0,
        le=1.0,
    )
    example_phrasing: str = Field(
        ...,
        description="Template sentence pattern the LLM adapts. Merge fields in `{curly_braces}`. The LLM rewrites for tone/context, not copy-pastes.",
    )
    merge_fields_required: list[str] | None = Field(
        None,
        description="Dot-path data fields the trigger evaluator must return for this angle to be usable (e.g. `competitor_brand`, `campaign_metric`). If any required field is null after evaluation, the angle is skipped.",
    )
    pair_well_with: list[PairWellWithItem] | None = Field(
        None,
        description="Other `angle_id`s that work well as a supporting angle when this is the primary. The LLM may use one supporting angle alongside the primary.",
    )
    avoid_combining_with: list[AvoidCombiningWithItem] | None = Field(
        None,
        description="Other `angle_id`s that would feel redundant or clash. The orchestrator never picks both.",
    )
    notes: str | None = Field(
        None,
        description="Free-text guidance for human review (rationale, edge cases, tone guidance).",
    )


class PitchAngleLibrary(BaseModel):
    """
    Curated library of pitch angles (hooks) the AI generation pipeline draws from when composing per-contact outreach emails. Each angle has trigger conditions (when it applies), role/step applicability, a strength score, and example phrasing the LLM adapts. Live data lives at `data/pitch_angles.json`. See `docs/outreach_workflow.md` for how angles plug into the generation step.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: str | None = Field(None, alias="$schema")
    agency_id: UUID | None = Field(
        None,
        description="Multi-tenant scope: FK to agency_profile.agency_id. Optional in v0.1 (single-tenant deploys may omit); required in v2 SaaS. When present, all cross-record queries MUST filter by agency_id to prevent cross-tenant data leakage. See docs/data_lineage.md GAP-01/02 for rationale.",
    )
    version: str
    updated: date_aliased | None = None
    field_comment: str | None = Field(None, alias="$comment")
    angles: list[Angle] = Field(
        ...,
        description="All authored angles. Order doesn't matter — orchestrator filters and sorts by strength_score at runtime.",
    )
