# generated by datamodel-codegen:
#   filename:  proposal_pack.schema.json
#   timestamp: 2026-05-28T08:49:29+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Trigger(StrEnum):
    """
    agent_initiated_v1: first version, agent clicked 'draft proposal' after passing commercial gate. agent_*regenerate: NL-feedback regen of various scopes. negotiation_response: regen triggered by brand pushback recorded in deal.proposal.negotiation_log[]; this version is bidirectionally linked to that log entry.
    """

    AGENT_INITIATED_V1 = "agent_initiated_v1"
    AGENT_FULL_REGENERATE = "agent_full_regenerate"
    AGENT_SECTION_REGENERATE = "agent_section_regenerate"
    AGENT_PER_SLIDE_REGENERATE = "agent_per_slide_regenerate"
    NEGOTIATION_RESPONSE = "negotiation_response"


class PassName(StrEnum):
    CONTEXT_ARTEFACT_SUMMARIZE = "context_artefact_summarize"
    DISCOVERY_DEBRIEF_EXTRACT = "discovery_debrief_extract"
    COMMERCIAL_PROPOSAL = "commercial_proposal"
    EXECUTIVE_SUMMARY = "executive_summary"
    SLIDES = "slides"
    SPEAKER_NOTES = "speaker_notes"
    SECTION_REGEN = "section_regen"
    SLIDE_REGEN = "slide_regen"


class LlmPass(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pass_name: PassName
    model: str | None = None
    input_tokens: int = Field(..., ge=0)
    output_tokens: int = Field(..., ge=0)
    cached_tokens: int | None = Field(None, ge=0)
    cost_usd: float | None = Field(None, ge=0.0)
    duration_ms: int | None = Field(None, ge=0)


class Generation(BaseModel):
    """
    Provenance + parameters for this version. Parallels discovery_prep_pack.generation; same versioning model.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    trigger: Trigger = Field(
        ...,
        description="agent_initiated_v1: first version, agent clicked 'draft proposal' after passing commercial gate. agent_*regenerate: NL-feedback regen of various scopes. negotiation_response: regen triggered by brand pushback recorded in deal.proposal.negotiation_log[]; this version is bidirectionally linked to that log entry.",
    )
    pre_generation_guidance: str | None = Field(
        None,
        description="Free-text guidance the agent provided BEFORE generation fired. Example: 'Lead the exec summary with the audience-fit data; brand said on the call they need to convince their CMO who's data-driven.'",
    )
    regeneration_feedback: str | None = Field(
        None,
        description="Natural-language feedback on parent version. Populated when version > 1.",
    )
    target_sections: list[str] | None = Field(
        None,
        description="For section/per-slide regen: which sections were rebuilt. Untargeted sections carry from parent_version.",
    )
    negotiation_log_entry_ref: str | None = Field(
        None,
        description="If trigger=negotiation_response: ISO-timestamp of the deal.proposal.negotiation_log[] entry this version responds to. Closes the bidirectional link between proposal_pack version history and the deal's negotiation audit log.",
    )
    generated_at: AwareDatetime
    generated_by_agent_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    llm_model: str
    llm_passes: list[LlmPass] | None = None


class ComparableBrandDealId(RootModel[str]):
    root: str = Field(..., pattern="^deal_[a-z0-9_-]+$")


class ContextSnapshot(BaseModel):
    """
    Frozen upstream context this version was generated from. Same lock-on-generation pattern as discovery_prep_pack.context_snapshot.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    captured_at: AwareDatetime
    forked_from_prep_pack_id: str | None = Field(
        None,
        description="FK to the discovery prep pack version that this proposal forks from. Slide content (talent_overview, audience_snapshot, recent_work) is lifted from this prep pack. If null, the proposal was generated without a prior discovery deck (rare — e.g. for repeat brands).",
        pattern="^prep_[a-z0-9_-]+_v[0-9]+$",
    )
    talent_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    brand_candidate_id: str | None = None
    primary_contact_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    discovery_debrief_snapshot: dict[str, Any] | None = Field(
        None,
        description="Frozen copy of `deal.lead.discovery_debrief` at generation time. If the canonical block later evolves (e.g. agent adds notes after a follow-up call), this version stays anchored. Shape mirrors `deal.lead.discovery_debrief`.",
    )
    comparable_brand_deal_ids: list[ComparableBrandDealId] | None = Field(
        None, description="Past brand_deals used as commercial + creative comparables."
    )
    external_research_refreshed: bool | None = Field(
        False,
        description="Was Exa research re-run for this proposal? Default false — proposal trusts the discovery prep's external research. Refresh recommended if >14d since prep pack v1.",
    )
    external_research: dict[str, Any] | None = Field(
        None,
        description="Populated only if external_research_refreshed=true. Same shape as discovery_prep_pack.context_snapshot.external_research.",
    )


class Platform(StrEnum):
    INSTAGRAM = "instagram"
    TIKTOK = "tiktok"
    YOUTUBE = "youtube"
    TWITTER_X = "twitter_x"
    LINKEDIN = "linkedin"
    PINTEREST = "pinterest"
    TWITCH = "twitch"
    SNAPCHAT = "snapchat"
    FACEBOOK = "facebook"
    SUBSTACK = "substack"
    PODCAST = "podcast"
    OTHER = "other"


class Format(StrEnum):
    REEL = "reel"
    STORY = "story"
    FEED_POST = "feed_post"
    CAROUSEL = "carousel"
    LIVE = "live"
    VIDEO_LONG_FORM = "video_long_form"
    VIDEO_SHORT = "video_short"
    PODCAST_EPISODE = "podcast_episode"
    PODCAST_READ = "podcast_read"
    NEWSLETTER = "newsletter"
    TWEET_THREAD = "tweet_thread"
    LINKEDIN_POST = "linkedin_post"
    APPEARANCE = "appearance"
    CO_CREATED_PRODUCT = "co_created_product"
    OTHER = "other"


class Deliverable(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    platform: Platform
    format: Format
    count: int = Field(..., ge=1)
    rationale: str | None = Field(
        None,
        description="Why this specific deliverable was proposed (links to a stated objective or pain point from the debrief).",
    )


class UsageRight(StrEnum):
    ORGANIC = "organic"
    WHITELISTING_30D = "whitelisting_30d"
    WHITELISTING_60D = "whitelisting_60d"
    WHITELISTING_90D = "whitelisting_90d"
    WHITELISTING_UNLIMITED = "whitelisting_unlimited"
    PAID_SOCIAL_30D = "paid_social_30d"
    PAID_SOCIAL_90D = "paid_social_90d"
    PAID_SOCIAL_PERPETUAL = "paid_social_perpetual"
    WEBSITE_USE = "website_use"
    BROADCAST = "broadcast"
    PRINT = "print"
    PERPETUAL_ALL_CHANNELS = "perpetual_all_channels"


class Exclusivity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    category: str | None = None
    duration_days: int | None = Field(None, ge=0)
    rationale: str | None = None


class TimelineItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    milestone: str = Field(
        ...,
        description="e.g. 'Contract signed', 'Concept approval', 'First draft delivered', 'Live posting', 'Final report'.",
    )
    target_date: date_aliased
    notes: str | None = None


class Type(StrEnum):
    GIFTED_PRODUCT = "gifted_product"
    COMPED_EVENT = "comped_event"
    COMPED_TRAVEL = "comped_travel"
    EQUITY = "equity"
    DISCOUNT_CODE = "discount_code"
    OTHER = "other"


class AdditionalCompensationItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type
    value_usd: float | None = Field(None, ge=0.0)
    description: str | None = None


class LlmProposed(BaseModel):
    """
    What the LLM proposed, with rationale per field. Built from briefing's commercial_range + objectives heard + comparables + scope/budget signals from discovery_debrief.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    deliverables: list[Deliverable]
    fee_usd: float = Field(..., ge=0.0)
    fee_rationale: str | None = Field(
        None,
        description="How the fee was derived. Cites commercial_range + budget_signal + comparable_deal_ids.",
    )
    fee_currency_original: str | None = Field(None, pattern="^[A-Z]{3}$")
    fee_original_amount: float | None = Field(None, ge=0.0)
    usage_rights: list[UsageRight] | None = None
    usage_rights_rationale: str | None = None
    exclusivity: Exclusivity | None = None
    timeline: list[TimelineItem] | None = None
    timeline_rationale: str | None = None
    additional_compensation: list[AdditionalCompensationItem] | None = None
    payment_terms: str | None = Field(
        None,
        description="e.g. '50% upon contract execution, 50% upon final delivery, NET-30'. Free-text but conventional patterns.",
    )
    exclusions: list[str] | None = Field(
        None,
        description="Explicit list of what is NOT included. Clarity reduces friction during execution. e.g. 'Paid amplification beyond 60d whitelisting', 'Original music licensing', 'Additional revisions beyond 2 rounds'.",
    )
    overall_rationale: str = Field(
        ...,
        description="Top-level rationale tying the whole proposal together — references the discovery debrief signals it responds to. The LLM's pitch to the agent for why this is the right proposal.",
    )


class ConfirmedOverride(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field: str = Field(
        ...,
        description="Which field was overridden. e.g. 'fee_usd', 'usage_rights', 'exclusivity.duration_days', 'deliverables[1].count'.",
    )
    from_: Any = Field(..., alias="from", description="LLM-proposed value (any type).")
    to: Any = Field(..., description="Agent-confirmed value (any type).")
    note: str | None = Field(
        None, description="Why the override. Optional but encouraged."
    )


class CommercialProposal(BaseModel):
    """
    The LLM's commercial proposal + the agent's confirmation event. SLIDES CANNOT RENDER until `confirmed_at` is set. On confirmation, the confirmed values write into `deal.proposal.*` (canonical) — this block holds the provenance.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    llm_proposed: LlmProposed = Field(
        ...,
        description="What the LLM proposed, with rationale per field. Built from briefing's commercial_range + objectives heard + comparables + scope/budget signals from discovery_debrief.",
    )
    proposed_at: AwareDatetime = Field(
        ...,
        description="When the LLM completed Stage C (commercial proposal). Slides cannot render until confirmed_at is also set.",
    )
    confirmed_at: AwareDatetime | None = Field(
        None,
        description="When the agent passed the commercial gate. ABSENT = slides not yet rendered. Setting this triggers Stage D (slide generation) AND copies values into deal.proposal.*.",
    )
    confirmed_by_agent_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    confirmed_overrides: list[ConfirmedOverride] | None = Field(
        None,
        description="Agent's edits to LLM-proposed values, captured per field. If empty, agent accepted all LLM values verbatim. If non-empty, each entry records the override + optional reasoning. Powers analytics (do we systematically overprice / underprice vs comparables?).",
    )


class Type13(StrEnum):
    """
    What kind of artefact this is. Drives how the LLM weights it during generation — brand_brief gets highest weight; reference_material is supplementary.
    """

    BRAND_BRIEF = "brand_brief"
    DISCOVERY_CALL_NOTES = "discovery_call_notes"
    CALL_TRANSCRIPT = "call_transcript"
    REFERENCE_MATERIAL = "reference_material"
    COMPETITOR_EXAMPLE = "competitor_example"
    INTERNAL_MEMO = "internal_memo"
    OTHER = "other"


class Role(StrEnum):
    """
    Generation weighting. primary_input: heavily influences output. supplementary: cited if relevant. reference: available but not actively used.
    """

    PRIMARY_INPUT = "primary_input"
    SUPPLEMENTARY = "supplementary"
    REFERENCE = "reference"


class Parser(StrEnum):
    """
    v0.1: pypdf (PDF) / python_docx (Word) / text_reader (txt, md). v2: external_transcript_link (Otter / Fireflies / Grain URL — no parsing, just reference).
    """

    PYPDF = "pypdf"
    PYTHON_DOCX = "python_docx"
    TEXT_READER = "text_reader"
    EXTERNAL_TRANSCRIPT_LINK = "external_transcript_link"


class LlmExtractedSignals(BaseModel):
    """
    Optional structured extraction from the artefact (e.g. brand_brief → stated objectives, deliverables requested, budget mentioned). Used to seed the discovery_debrief block on the deal record.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    stated_objectives: list[str] | None = None
    stated_budget: str | None = None
    stated_timeline: str | None = None
    deliverables_requested: list[str] | None = None
    exclusivity_requested: str | None = None
    usage_rights_requested: str | None = None


class RelevanceTag(StrEnum):
    """
    Agent's manual tagging. `drop` = excluded from generation; `low` = available but de-prioritised; `context` = supplementary background; `core` = heavily weighted.
    """

    CORE = "core"
    CONTEXT = "context"
    LOW = "low"
    DROP = "drop"


class ContextArtefact(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artefact_id: str = Field(..., pattern="^ctx_[a-z0-9]+$")
    type: Type13 = Field(
        ...,
        description="What kind of artefact this is. Drives how the LLM weights it during generation — brand_brief gets highest weight; reference_material is supplementary.",
    )
    role: Role | None = Field(
        "primary_input",
        description="Generation weighting. primary_input: heavily influences output. supplementary: cited if relevant. reference: available but not actively used.",
    )
    original_filename: str
    stored_filepath: str | None = Field(
        None,
        description="Relative path to the uploaded raw file. v0.1: `data/deals/{deal_id}/context_uploads/{artefact_id}_{filename}`. v2: S3 key.",
    )
    mime_type: str | None = None
    size_bytes: int | None = Field(None, ge=0)
    uploaded_at: AwareDatetime
    uploaded_by_agent_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    parser: Parser = Field(
        ...,
        description="v0.1: pypdf (PDF) / python_docx (Word) / text_reader (txt, md). v2: external_transcript_link (Otter / Fireflies / Grain URL — no parsing, just reference).",
    )
    parsed_text: str | None = Field(
        None,
        description="Raw extracted text. Truncated for very large files (configurable cap, default 100k chars). Preserved for the life of the deal; purged on archive.",
    )
    parsed_text_length: int | None = Field(None, ge=0)
    external_url: AnyUrl | None = Field(
        None,
        description="Used when parser=external_transcript_link. URL to the transcript on the recording service (Otter/Fireflies/Grain). No content extraction in v0.1; v2 may fetch the transcript via the service's API.",
    )
    llm_summary: str | None = Field(
        None,
        description="LLM-generated summary of the artefact's content. Used as compressed input during proposal generation (full parsed_text reserved for direct-cite needs).",
    )
    llm_extracted_signals: LlmExtractedSignals | None = Field(
        None,
        description="Optional structured extraction from the artefact (e.g. brand_brief → stated objectives, deliverables requested, budget mentioned). Used to seed the discovery_debrief block on the deal record.",
    )
    relevance_tag: RelevanceTag | None = Field(
        "core",
        description="Agent's manual tagging. `drop` = excluded from generation; `low` = available but de-prioritised; `context` = supplementary background; `core` = heavily weighted.",
    )
    include_in_generation: bool | None = Field(
        True,
        description="Hard inclusion gate. Set to false to fully exclude (different from relevance_tag=drop in that it's a binary switch the agent can toggle without re-uploading).",
    )


class Type14(StrEnum):
    """
    Drives renderer layout. Proposal-specific types: executive_summary (the one slide the buyer's boss reads); objectives_recap (lifts discovery_debrief.objectives_heard to confirm we listened); recommendation (the angle/concept); deliverables (table); investment (fee + payment terms); usage_rights / exclusivity / exclusions (commercial); next_steps_proposal (what brand does to move forward). Forked types from discovery: talent_overview / audience_snapshot / recent_work. agency_process is renamed from discovery's `process` for clarity.
    """

    TITLE = "title"
    EXECUTIVE_SUMMARY = "executive_summary"
    OBJECTIVES_RECAP = "objectives_recap"
    TALENT_OVERVIEW = "talent_overview"
    AUDIENCE_SNAPSHOT = "audience_snapshot"
    RECENT_WORK = "recent_work"
    RECOMMENDATION = "recommendation"
    DELIVERABLES = "deliverables"
    TIMELINE = "timeline"
    INVESTMENT = "investment"
    USAGE_RIGHTS = "usage_rights"
    EXCLUSIVITY = "exclusivity"
    EXCLUSIONS = "exclusions"
    AGENCY_PROCESS = "agency_process"
    NEXT_STEPS_PROPOSAL = "next_steps_proposal"
    CUSTOM = "custom"


class KpiTile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    value: str
    label: str
    source: str | None = None
    as_of: date_aliased | None = None


class ImageRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    alt: str | None = None
    caption: str | None = None


class Table(BaseModel):
    """
    For deliverables / timeline / investment slides. Renderer turns this into a styled table.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    columns: list[str] | None = None
    rows: list[list[str]] | None = None


class LiveBody(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    headline: str | None = None
    subheadline: str | None = None
    body_text: str | None = None
    bullets: list[str] | None = None
    kpi_tiles: list[KpiTile] | None = None
    image_refs: list[ImageRef] | None = None
    table: Table | None = Field(
        None,
        description="For deliverables / timeline / investment slides. Renderer turns this into a styled table.",
    )
    callout: str | None = None


class LeaveBehindExtension(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    expanded_body: str | None = None
    supporting_data: str | None = None
    footnotes: list[str] | None = None


class Source(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    claim: str
    source: str
    as_of: date_aliased | None = None


class Slide(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    slide_id: str = Field(..., pattern="^slide_[a-z0-9_-]+$")
    position: int = Field(..., ge=1)
    title: str
    type: Type14 = Field(
        ...,
        description="Drives renderer layout. Proposal-specific types: executive_summary (the one slide the buyer's boss reads); objectives_recap (lifts discovery_debrief.objectives_heard to confirm we listened); recommendation (the angle/concept); deliverables (table); investment (fee + payment terms); usage_rights / exclusivity / exclusions (commercial); next_steps_proposal (what brand does to move forward). Forked types from discovery: talent_overview / audience_snapshot / recent_work. agency_process is renamed from discovery's `process` for clarity.",
    )
    forked_from_prep_slide_id: str | None = Field(
        None,
        description="If this slide was forked from the discovery prep pack rather than generated fresh, the prep pack's slide_id is captured here. Used by the renderer to flag (in editor mode) which slides are inherited vs new — agent can choose to re-generate forked slides if discovery context evolved.",
    )
    live_body: LiveBody
    leave_behind_extension: LeaveBehindExtension | None = None
    speaker_notes: str | None = None
    sources: list[Source] | None = None
    agent_edited: bool | None = False
    agent_edited_at: AwareDatetime | None = None


class Type15(StrEnum):
    HTML_LIVE = "html_live"
    HTML_LEAVE_BEHIND = "html_leave_behind"
    PDF_LIVE = "pdf_live"
    PDF_LEAVE_BEHIND = "pdf_leave_behind"
    SPEAKER_NOTES_MD = "speaker_notes_md"
    PPTX = "pptx"
    COMMERCIAL_SUMMARY_MD = "commercial_summary_md"


class Status(StrEnum):
    RENDERED = "rendered"
    PENDING = "pending"
    FAILED = "failed"
    BLOCKED_BY_COMMERCIAL_GATE = "blocked_by_commercial_gate"


class RenderedBy(StrEnum):
    JINJA2_HTML = "jinja2_html"
    PUPPETEER_PDF = "puppeteer_pdf"
    SLIDE_SKILL = "slide_skill"
    MARKDOWN_WRITER = "markdown_writer"


class ExportArtifact(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type15
    status: Status
    path: str | None = None
    size_bytes: int | None = Field(None, ge=0)
    rendered_at: AwareDatetime | None = None
    rendered_by: RenderedBy | None = None
    error: str | None = None


class EditType(StrEnum):
    SLIDE_HTML_DIRECT = "slide_html_direct"
    COMMERCIAL_OVERRIDE = "commercial_override"
    SLIDE_REORDER = "slide_reorder"
    SLIDE_DELETE = "slide_delete"
    SLIDE_INSERT = "slide_insert"
    CONTEXT_ARTEFACT_RETAG = "context_artefact_retag"
    CONTEXT_ARTEFACT_EXCLUDE = "context_artefact_exclude"


class AgentEdit(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    edit_id: str = Field(..., pattern="^edit_[a-z0-9]+$")
    edited_at: AwareDatetime
    edited_by_agent_id: str | None = Field(None, pattern="^[a-z0-9][a-z0-9-]*$")
    edit_type: EditType
    target: str = Field(
        ...,
        description="What was edited. e.g. 'slides[3].live_body', 'commercial_proposal.fee_usd', 'context_artefacts[ctx_abc].relevance_tag'.",
    )
    before_excerpt: str | None = None
    after_excerpt: str | None = None


class ProposalPack(BaseModel):
    """
    Phase 4.6 — a versioned commercial proposal the agency sends to the brand after the discovery call. Forks structured content from the discovery prep pack (Phase 4.5) and adds proposal-specific sections: executive summary, objectives recap, deliverables, fee, usage rights, exclusivity, timeline, exclusions, next steps. Generation is gated on the agent explicitly confirming pricing + deliverables — slides cannot render until the commercial gate is passed. Each version is a single source of truth for that round of proposal; the confirmed commercial values write into `deal.proposal.*` (canonical). Stored at `data/deals/{deal_id}/proposal_packs/v{N}.json` (gitignored). See `docs/proposal_pack_workflow.md`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: str | None = Field(None, alias="$schema")
    agency_id: UUID | None = Field(
        None,
        description="Multi-tenant scope: FK to agency_profile.agency_id. Optional in v0.1 (single-tenant deploys may omit); required in v2 SaaS. When present, all cross-record queries MUST filter by agency_id to prevent cross-tenant data leakage. See docs/data_lineage.md GAP-01/02 for rationale.",
    )
    proposal_pack_id: str = Field(
        ...,
        description="Globally unique identifier. Format: `pp_{deal_id_short}_v{N}` (e.g. `pp_2026_q2_alo-yoga_jane-doe_v3`). The `pp_` prefix distinguishes from prep packs (`prep_*`).",
        pattern="^pp_[a-z0-9_-]+_v[0-9]+$",
    )
    deal_id: str = Field(
        ...,
        description="FK to the Phase 4 deal. The deal's `proposal.proposal_pack_ids[]` array references all versions; `proposal.latest_proposal_pack_id` points to the current `is_latest: true` version.",
        pattern="^deal_pipeline_[a-z0-9_-]+$",
    )
    version: int = Field(..., ge=1)
    parent_version: int | None = Field(
        None,
        description="Which version this regenerated from. Null/absent for v1. Linear history.",
        ge=1,
    )
    is_latest: bool = Field(
        ..., description="Exactly one version per deal_id at any time."
    )
    generation: Generation = Field(
        ...,
        description="Provenance + parameters for this version. Parallels discovery_prep_pack.generation; same versioning model.",
    )
    context_snapshot: ContextSnapshot = Field(
        ...,
        description="Frozen upstream context this version was generated from. Same lock-on-generation pattern as discovery_prep_pack.context_snapshot.",
    )
    context_artefacts: list[ContextArtefact] | None = Field(
        None,
        description="Files uploaded by the agent to augment generation context — briefs, notes, transcripts, reference material. Each parsed (pypdf / python-docx / text reader), LLM-summarised, and optionally signal-extracted. Agent can tag relevance to demote/exclude from generation.",
    )
    commercial_proposal: CommercialProposal = Field(
        ...,
        description="The LLM's commercial proposal + the agent's confirmation event. SLIDES CANNOT RENDER until `confirmed_at` is set. On confirmation, the confirmed values write into `deal.proposal.*` (canonical) — this block holds the provenance.",
    )
    slides: list[Slide] | None = Field(
        None,
        description="Generated only after commercial gate passed. Forks talent_overview / audience_snapshot / recent_work / fit_angle slides from the source discovery prep pack; adds proposal-specific slides (executive_summary, objectives_recap, recommendation, deliverables, timeline, investment, usage_rights, exclusivity, exclusions, next_steps_proposal). Same `live_body` + `leave_behind_extension` + `speaker_notes` + `sources` shape as discovery prep pack slides.",
    )
    export_artifacts: list[ExportArtifact] | None = None
    agent_edits: list[AgentEdit] | None = Field(
        None,
        description="Append-only audit log of direct edits to this version (no LLM regen). Same shape as discovery_prep_pack.agent_edits[].",
    )
    created_at: AwareDatetime
    updated_at: AwareDatetime | None = None
