# generated by datamodel-codegen:
#   filename:  talent.schema.json
#   timestamp: 2026-05-28T08:49:29+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    RootModel,
    constr,
)


class ProfessionalRole(StrEnum):
    CREATOR = "creator"
    ACTOR = "actor"
    COMEDIAN = "comedian"
    ATHLETE = "athlete"
    MUSICIAN = "musician"
    MODEL = "model"
    WRITER = "writer"
    PODCASTER = "podcaster"
    SPEAKER = "speaker"
    FOUNDER = "founder"
    EXECUTIVE = "executive"
    JOURNALIST = "journalist"
    CHEF = "chef"
    DESIGNER = "designer"


class Location(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    city: str | None = None
    region: str | None = None
    country: str | None = Field(
        None, description="ISO 3166-1 alpha-2, e.g. 'GB', 'US'."
    )


class Manager(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str | None = None
    email: EmailStr | None = None
    phone: str | None = None
    agency: str | None = None


class Contact(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: EmailStr | None = None
    phone: str | None = None
    manager: Manager | None = None


class PaymentMethod(StrEnum):
    BANK_TRANSFER = "bank_transfer"
    PAYPAL = "paypal"
    STRIPE = "stripe"
    WISE = "wise"
    CRYPTO = "crypto"
    OTHER = "other"


class BillingEntity(BaseModel):
    """
    Legal/tax info needed to invoice brands. Used as the FROM party on every Phase 4.8 invoice generated for deals involving this talent. Distinguished from `agency_profile.billing_entity` which is the agency's own legal entity (used for outreach signature CAN-SPAM compliance, not invoicing). Whether the agency invoices on the talent's behalf or the talent invoices directly is governed by the `commission_split` model on `agency_profile.default_commission_model` + per-talent overrides via `talent.commission_override`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    legal_name: str | None = None
    company_number: str | None = None
    country: str | None = Field(None, description="ISO 3166-1 alpha-2.")
    tax_id: str | None = Field(None, description="VAT/EIN/equivalent.")
    address: str | None = None
    payment_methods: list[PaymentMethod] | None = None


class CommissionModel(StrEnum):
    """
    How money flows for this talent's deals. agency_invoices_brand_pays_talent_net: agency invoices brand for full fee; agency receives payment; agency pays talent (fee × (1-commission_rate)) net. talent_invoices_brand_agency_invoices_talent: talent invoices brand directly + agency separately invoices talent for commission. talent_invoices_brand_talent_pays_agency: talent invoices brand + manually pays agency commission. v0.1 Phase 4.8 invoicing uses the configured model to determine FROM-party on the brand-facing invoice + whether a sibling commission invoice is auto-generated.
    """

    AGENCY_INVOICES_BRAND_PAYS_TALENT_NET = "agency_invoices_brand_pays_talent_net"
    TALENT_INVOICES_BRAND_AGENCY_INVOICES_TALENT = (
        "talent_invoices_brand_agency_invoices_talent"
    )
    TALENT_INVOICES_BRAND_TALENT_PAYS_AGENCY = (
        "talent_invoices_brand_talent_pays_agency"
    )


class CommissionOverride(BaseModel):
    """
    Per-talent override of agency-default commission terms. When absent, deals for this talent use `agency_profile.default_commission_rate` + `default_commission_model`. When present, these values take precedence. Captured in Phase 1 onboarding Step 5 (typically) or 7.5.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    commission_rate: float | None = Field(
        None,
        description="Decimal — 0.20 = 20% agency commission. Per-talent override of `agency_profile.default_commission_rate`.",
        ge=0.0,
        le=1.0,
    )
    commission_model: CommissionModel | None = Field(
        None,
        description="How money flows for this talent's deals. agency_invoices_brand_pays_talent_net: agency invoices brand for full fee; agency receives payment; agency pays talent (fee × (1-commission_rate)) net. talent_invoices_brand_agency_invoices_talent: talent invoices brand directly + agency separately invoices talent for commission. talent_invoices_brand_talent_pays_agency: talent invoices brand + manually pays agency commission. v0.1 Phase 4.8 invoicing uses the configured model to determine FROM-party on the brand-facing invoice + whether a sibling commission invoice is auto-generated.",
    )


class PreferredPaymentMethod(StrEnum):
    BANK_TRANSFER = "bank_transfer"
    WIRE = "wire"
    ACH = "ach"
    STRIPE = "stripe"
    PAYPAL = "paypal"
    WISE = "wise"
    CHECK = "check"
    OTHER = "other"


class InvoicePaymentOverride(BaseModel):
    """
    Per-talent override of agency-wide invoice payment instructions. When the talent's deals route payment to a different account than the agency's default, capture here. Renders into the `payment_instructions` block of invoices for this talent's deals (replaces `agency_profile.invoice_template.payment_instructions_markdown` for those invoices). Captured in Phase 1 onboarding Step 5.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    payment_instructions_markdown: str | None = Field(
        None,
        description="Bank details / IBAN / SWIFT / Stripe link / PayPal address. Supports merge fields (e.g. `{{invoice_number}}` as bank reference).",
    )
    preferred_payment_method: PreferredPaymentMethod | None = None


class GenderSplit(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    female: float | None = Field(None, ge=0.0, le=100.0)
    male: float | None = Field(None, ge=0.0, le=100.0)
    non_binary: float | None = Field(None, ge=0.0, le=100.0)
    unknown: float | None = Field(None, ge=0.0, le=100.0)


class TopCountry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    country: str = Field(..., description="ISO 3166-1 alpha-2.")
    share: float = Field(..., ge=0.0, le=100.0)


class TopCity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    city: str
    country: str | None = None
    share: float = Field(..., ge=0.0, le=100.0)


class TopLanguage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    language: str
    share: float = Field(..., ge=0.0, le=100.0)


class AudienceDemographics(BaseModel):
    """
    Aggregate audience demographics across all platforms. Per-platform overrides live on each platform entry.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    age_bands: dict[constr(pattern=r"^.*$"), float] | None = Field(
        None,
        description="Share by age band as a percentage 0–100. Keys MUST be IAB Audience Taxonomy 1.1 Age Range bands so demographics bridge cleanly to industry audience profiles. IAB has no under-18 segment; if your platform analytics report under-18 share, exclude it from these percentages (re-normalise to 100% over 18+).",
    )
    gender_split: GenderSplit | None = None
    top_countries: list[TopCountry] | None = None
    top_cities: list[TopCity] | None = None
    top_languages: list[TopLanguage] | None = None
    interests: list[str] | None = None


class Deliverables(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    price: float = Field(..., ge=0.0)
    notes: str | None = None


class Bundle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    includes: list[str] | None = None
    price: float = Field(..., ge=0.0)
    notes: str | None = None


class Uplifts(BaseModel):
    """
    Percentage uplifts on base price for extra rights.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    usage_rights_pct: float | None = Field(None, ge=0.0)
    whitelisting_pct: float | None = Field(None, ge=0.0)
    exclusivity_pct: float | None = Field(None, ge=0.0)


class RateCard(BaseModel):
    """
    Per-platform rate card.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    currency: str | None = Field(None, description="ISO 4217, e.g. 'GBP', 'USD'.")
    deliverables: dict[str, Deliverables] | None = Field(
        None,
        description="Keyed by deliverable type, e.g. 'reel','story','feed_post','carousel','live','long_form_video','short','tweet','thread','podcast_mention','newsletter'.",
    )
    bundles: list[Bundle] | None = None
    uplifts: Uplifts | None = Field(
        None, description="Percentage uplifts on base price for extra rights."
    )


class DefaultUsageRights(StrEnum):
    ORGANIC_ONLY = "organic_only"
    ORGANIC_PLUS_WHITELISTING = "organic_plus_whitelisting"
    ORGANIC_PLUS_PAID_SOCIAL = "organic_plus_paid_social"
    FULL_PAID_MEDIA = "full_paid_media"


class BlackoutDate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start: date_aliased
    end: date_aliased
    reason: str | None = None


class WorkingTerms(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    default_usage_rights: DefaultUsageRights | None = None
    default_usage_duration_days: int | None = Field(None, ge=0)
    default_turnaround_days: int | None = Field(None, ge=0)
    revisions_included: int | None = Field(None, ge=0)
    blackout_dates: list[BlackoutDate] | None = None


class Source(StrEnum):
    """
    Where the value comes from. `agent_input` = agent must provide (typically brand legal entity info). `computed` = derived from other fields (e.g. signed_date = today).
    """

    TALENT_PROFILE = "talent_profile"
    TALENT_BILLING_ENTITY = "talent_billing_entity"
    TALENT_WORKING_TERMS = "talent_working_terms"
    AGENCY_PROFILE = "agency_profile"
    DEAL_PROPOSAL = "deal_proposal"
    DISCOVERY_DEBRIEF = "discovery_debrief"
    CONTEXT_ARTEFACT = "context_artefact"
    AGENT_INPUT = "agent_input"
    COMPUTED = "computed"


class MergeFieldDefinition(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field: str = Field(
        ...,
        description="Merge field name (without braces). e.g. 'talent_legal_name', 'brand_legal_name', 'fee_usd', 'campaign_start_date'.",
    )
    source: Source = Field(
        ...,
        description="Where the value comes from. `agent_input` = agent must provide (typically brand legal entity info). `computed` = derived from other fields (e.g. signed_date = today).",
    )
    source_path: str | None = Field(
        None,
        description="Dotted path within the source (e.g. 'billing_entity.legal_name', 'proposal.fee_usd'). Optional — omit for free-text fields the agent fills.",
    )
    required: bool | None = Field(
        True,
        description="If true, draft contract cannot pass legal review until value is set. Critical fields (legal names, fees, dates) should be required.",
    )
    default: Any | None = Field(
        None, description="Fallback value if source extraction fails or returns null."
    )
    description: str | None = Field(
        None, description="Human-readable explanation for the agent reviewing in UI."
    )


class DefaultDecision(StrEnum):
    """
    If `include` / `exclude`, decision is fixed — LLM doesn't evaluate. `llm_decide` runs Stage C evaluation.
    """

    INCLUDE = "include"
    EXCLUDE = "exclude"
    LLM_DECIDE = "llm_decide"


class ApplicabilitySource(StrEnum):
    """
    Hint to LLM about which context block to inspect.
    """

    DEAL_PROPOSAL = "deal_proposal"
    DISCOVERY_DEBRIEF = "discovery_debrief"
    TALENT_PROFILE = "talent_profile"
    AGENCY_PROFILE = "agency_profile"
    CONTEXT_ARTEFACT = "context_artefact"
    BRAND_LEGAL_INFO = "brand_legal_info"


class ClauseApplicabilityRule(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    clause_id: str = Field(
        ...,
        description="Matches the `{{#if clause_id}}` identifier in markdown_source.",
    )
    description: str = Field(
        ...,
        description="What this clause covers (e.g. 'EU GDPR data-processing addendum').",
    )
    condition: str = Field(
        ...,
        description="Plain-language condition the LLM evaluates (e.g. 'brand registered address is in the EU', 'deal.proposal.exclusivity.duration_days > 0'). Structured JSONLogic could replace this in v0.2 for deterministic evaluation; v0.1 lets the LLM interpret natural-language conditions for flexibility.",
    )
    default_decision: DefaultDecision | None = Field(
        "llm_decide",
        description="If `include` / `exclude`, decision is fixed — LLM doesn't evaluate. `llm_decide` runs Stage C evaluation.",
    )
    applicability_source: ApplicabilitySource | None = Field(
        None, description="Hint to LLM about which context block to inspect."
    )


class NarrativePlaceholder(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    placeholder: str = Field(
        ...,
        description="Matches the `{{narrative_*}}` identifier in markdown_source (e.g. 'narrative_scope_of_work').",
    )
    description: str | None = Field(None, description="What the section should cover.")
    draws_from: list[str] = Field(
        ...,
        description="List of context sources to draw from (e.g. ['deal.proposal.deliverables', 'discovery_debrief.objectives_heard']).",
    )
    tone: str | None = Field(
        None,
        description="Tone guidance (e.g. 'formal legal prose, no marketing language').",
    )
    max_word_count: int | None = Field(
        None, description="Soft cap — prevents narrative bloat.", ge=0
    )


class ContractTemplate(BaseModel):
    """
    Per-talent contract template used by the Phase 4.7 contract pack generator (`docs/contract_pack_workflow.md`). Captured during Phase 1 talent onboarding. Markdown source with `{{merge_field}}` placeholders, `{{#if condition}}...{{/if}}` conditional sections, and `{{narrative_*}}` LLM-drafted blocks. Party identification (legal entity name, country, tax ID, address) is pulled from `talent.billing_entity` — single source of truth. Working defaults (usage rights, turnaround, revisions) are pulled from `talent.working_terms`. Agencies can ship starter templates in `data/contract_template_starters/` that the onboarding flow copies into this field for editing.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    markdown_source: str | None = Field(
        None,
        description="The full contract template text in markdown. Contains `{{merge_field}}` for deterministic substitution, `{{#if condition}}...{{/if}}` for conditional clauses (closes with matching `{{/if}}`), and `{{narrative_*}}` for LLM-drafted sections. The renderer composes this markdown source after merge/condition/narrative passes and emits .md (source-of-truth), .docx (via python-docx), .pdf (via Puppeteer or pandoc).",
    )
    merge_field_definitions: list[MergeFieldDefinition] | None = Field(
        None,
        description="Every merge field the template uses, with its expected source. Drives Stage B (merge field extraction) — LLM knows where to pull each value from and can flag low-confidence extractions for agent review.",
    )
    clause_applicability_rules: list[ClauseApplicabilityRule] | None = Field(
        None,
        description="Per-conditional-block rule that determines whether the clause fires. Evaluated in Stage C. Each rule has a human-readable description (for agent + audit) AND a structured condition (machine-evaluatable). The LLM evaluates the condition against full deal/proposal/debrief context and decides include/exclude with rationale.",
    )
    narrative_placeholders: list[NarrativePlaceholder] | None = Field(
        None,
        description="Sections the LLM drafts (Stage D). Each placeholder names what context to draw from + tone guidance.",
    )
    default_governing_law: str | None = Field(
        None,
        description="Default governing-law jurisdiction (e.g. 'England and Wales', 'State of California, USA'). Used as merge field default if not overridden per deal.",
    )
    default_jurisdiction: str | None = Field(
        None, description="Default court jurisdiction for disputes."
    )
    legal_reviewer_id: str | None = Field(
        None,
        description="Optional. If set, only this identity can pass the hard legal review gate (e.g. external legal counsel). Defaults to the deal's assigned_agent_id if absent. The reviewer's identity is captured in `contract_pack.legal_review.approved_by_agent_id` on gate-pass.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    template_version: str | None = Field(
        None,
        description="Semver or freeform version label. Updated whenever markdown_source / merge_field_definitions / clause_applicability_rules / narrative_placeholders / default_governing_law / default_jurisdiction change. Captured in `contract_pack.context_snapshot.template_version_used` for traceability — if a template changes mid-deal, prior contract packs stay anchored to the version they were generated from. ENFORCEMENT (GAP-08): API layer MUST bump this string + set template_updated_at on every modification to those fields. Version bump is a DB-enforced trigger or a service-layer guard — never trust manual update. Critical for legal audit trail: a signed contract's clause set must always be reproducible from the captured template_version.",
    )
    template_updated_at: AwareDatetime | None = None
    based_on_starter_template_id: str | None = Field(
        None,
        description="If the template was adopted from one of the agency's starter templates (`data/contract_template_starters/`), the starter's ID is captured here. Provenance — easier to track which talent templates have diverged from which starters.",
    )


class PressMention(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    publication: str | None = None
    url: AnyUrl
    date: date_aliased | None = None


class PressKit(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    media_kit_url: AnyUrl | None = None
    headshot_urls: list[AnyUrl] | None = None
    demo_reel_urls: list[AnyUrl] | None = None
    press_mentions: list[PressMention] | None = None
    awards: list[str] | None = None


class Style(StrEnum):
    AD = "#ad"
    SPONSORED = "#sponsored"
    PAID_PARTNERSHIP = "Paid partnership"
    GIFTED = "Gifted"
    OTHER = "other"


class DisclosureDefaults(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    style: Style | None = None
    notes: str | None = None


class Platform(StrEnum):
    INSTAGRAM = "instagram"
    TIKTOK = "tiktok"
    YOUTUBE = "youtube"
    X = "x"
    TWITTER = "twitter"
    FACEBOOK = "facebook"
    SNAPCHAT = "snapchat"
    TWITCH = "twitch"
    LINKEDIN = "linkedin"
    PINTEREST = "pinterest"
    THREADS = "threads"
    SUBSTACK = "substack"
    PODCAST = "podcast"
    OTHER = "other"


class Stats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    followers: int | None = Field(None, ge=0)
    engagement_rate_pct: float | None = Field(None, ge=0.0, le=100.0)
    avg_views: int | None = Field(None, ge=0)
    avg_likes: int | None = Field(None, ge=0)
    avg_comments: int | None = Field(None, ge=0)
    avg_shares: int | None = Field(None, ge=0)
    last_updated: date_aliased | None = None


class ApiCredentials(BaseModel):
    """
    References to credentials — never the raw secret.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    access_token_ref: str | None = Field(
        None,
        description="e.g. 'env:INSTAGRAM_TOKEN' or 'vault:nativ2/instagram/jane-doe'.",
    )
    refresh_token_ref: str | None = None
    client_id_ref: str | None = None
    client_secret_ref: str | None = None
    scopes: list[str] | None = None
    expires_at: AwareDatetime | None = None
    scope_validated_at: AwareDatetime | None = Field(
        None,
        description="Set by the OAuth callback after a successful test API call confirms the granted scopes work.",
    )


class Fee(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    amount: float | None = Field(None, ge=0.0)
    currency: str | None = None


class BrandContact(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str | None = None
    role: str | None = None
    email: EmailStr | None = None


class Handle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    platform: str
    handle: str
    url: AnyUrl | None = None


class Confidence(StrEnum):
    """
    Aggregated strength across all this creator's previous brands. `primary` if multiple brands point at this niche at primary tier; weaker otherwise.
    """

    PRIMARY = "primary"
    SECONDARY = "secondary"
    TERTIARY = "tertiary"


class Status(StrEnum):
    """
    `seed` = name+handles only; `researching` = AI run in flight; `enriched` = previous_brands + inferred_niches populated; `failed` = AI couldn't enrich; `stale` = enriched but past refresh window.
    """

    SEED = "seed"
    RESEARCHING = "researching"
    ENRICHED = "enriched"
    FAILED = "failed"
    STALE = "stale"


class Research(BaseModel):
    """
    AI-research workflow metadata. Tracks enrichment state so the app knows when to refresh.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    status: Status | None = Field(
        None,
        description="`seed` = name+handles only; `researching` = AI run in flight; `enriched` = previous_brands + inferred_niches populated; `failed` = AI couldn't enrich; `stale` = enriched but past refresh window.",
    )
    last_researched_at: AwareDatetime | None = None
    sources: list[str] | None = Field(
        None, description="URLs / source notes the AI used to enrich this record."
    )


class NicheId(RootModel[str]):
    root: str = Field(
        ...,
        description="Kebab-case slug that MUST match an `id` in `data/niches.json`. Pattern-validated here; semantic match enforced at load time by the app.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )


class IndustryId(RootModel[str]):
    root: str = Field(
        ...,
        description="Kebab-case slug that MUST match an `id` in `data/industries.json`. Pattern-validated here; semantic match enforced at load time by the app.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )


class AudienceDemographicsModel(AudienceDemographics):
    """
    Aggregate audience demographics across all platforms. Per-platform overrides live on each platform entry.
    """


class ActiveExclusivity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    industry_id: str = Field(
        ...,
        description="Industry the talent is exclusive in. Must match an `id` in `data/industries.json`.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    brand: str | None = Field(None, description="The brand the exclusivity is with.")
    ends_on: date_aliased | None = None


class BrandPreferences(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    preferred_industries: list[IndustryId] | None = Field(
        None,
        description="Industry IDs from `data/industries.json` the talent actively wants to work with.",
    )
    blocked_industries: list[IndustryId] | None = Field(
        None,
        description="Industry IDs from `data/industries.json` the talent will not work with.",
    )
    values_red_lines: list[str] | None = Field(
        None,
        description="Free-form hard nos beyond industry-level blocks (e.g. 'diet culture messaging').",
    )
    active_exclusivities: list[ActiveExclusivity] | None = None


class PlatformAccount(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    platform: Platform
    handle: str
    url: AnyUrl | None = None
    primary: bool | None = Field(
        None, description="True if this is the talent's main platform."
    )
    stats: Stats | None = None
    audience_demographics_override: AudienceDemographicsModel | None = Field(
        None,
        description="Optional per-platform override of the top-level audience_demographics.",
    )
    api_credentials: ApiCredentials | None = Field(
        None, description="References to credentials — never the raw secret."
    )


class BrandDeal(BaseModel):
    """
    Light index entry for a past brand campaign. The full rich record (KPIs, vs-benchmark, audience-overlap, re-engagement metadata, etc.) lives in `data/brand_deals/{talent_id}.json`. Optional `deal_id` field links the two — when present, the orchestrator reads the rich record from there. Kept in talent.json for backwards compatibility + fast scans without loading the deals file.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    brand: str = Field(..., description="Brand/company name as commonly written.")
    industry_id: str = Field(
        ...,
        description="Industry ID from `data/industries.json`. The app auto-suggests this from `brand` via `data/brand_industry_map.json` (exact + alias + domain match) and falls back to AI inference.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    deal_id: str | None = Field(
        None,
        description="Optional FK to a rich deal record in `data/brand_deals/{talent_id}.json`. When set, the rich KPIs, vs-benchmark performance, audience-overlap, and re-engagement metadata are sourced from there. When absent (legacy or skeleton entries), the orchestrator falls back to the inline fields below.",
        pattern="^deal_[a-z0-9_]+$",
    )
    campaign_date: date_aliased | None = None
    platforms: list[str] | None = None
    deliverables: list[str] | None = None
    fee: Fee | None = None
    usage_rights_granted: str | None = None
    performance_notes: str | None = None
    brand_contact: BrandContact | None = None


class PreviousBrand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    brand: str
    industry_id: str | None = Field(
        None,
        description="Industry ID from `data/industries.json`. Optional on input — resolved by the app from the brand name.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    source: str | None = Field(
        None,
        description="Where this collaboration was observed (URL, post handle, manual entry).",
    )


class InferredNich(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    niche_id: str = Field(
        ...,
        description="Kebab-case slug that MUST match an `id` in `data/niches.json`. Pattern-validated here; semantic match enforced at load time by the app.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    confidence: Confidence = Field(
        ...,
        description="Aggregated strength across all this creator's previous brands. `primary` if multiple brands point at this niche at primary tier; weaker otherwise.",
    )
    supporting_brands: list[str] | None = Field(
        None,
        description="The previous_brands entries (by brand name) that contributed to this inference.",
    )


class SimilarTalent(BaseModel):
    """
    Thin pointer to a competitor/comparable creator. Starts as a seed (name + handles) and is enriched by AI research over time. `previous_brands` is the source of truth; `inferred_niches` is back-derived from those brands by inverting `data/niche_industry_affinity.json` (industry -> niches that resonate).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: str | None = Field(
        None,
        description="Optional slug for cross-referencing.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    name: str
    handles: list[Handle] | None = Field(
        None, description="Public platform handles. Starting point for AI research."
    )
    previous_brands: list[PreviousBrand] | None = Field(
        None,
        description="Known brand collaborations. Each `industry_id` is auto-resolved via `data/brand_industry_map.json` (or AI inference fallback). This list is the source of truth — niches are derived from it, not authored.",
    )
    inferred_niches: list[InferredNich] | None = Field(
        None,
        description="Niches back-derived from `previous_brands` by inverting `data/niche_industry_affinity.json` — for each industry, which niches list it as a primary/secondary/tertiary match? Computed by the app, not hand-authored. Stored on the record so it persists between sessions and can be reviewed/overridden.",
    )
    notes: str | None = None
    research: Research | None = Field(
        None,
        description="AI-research workflow metadata. Tracks enrichment state so the app knows when to refresh.",
    )


class TalentProfile(BaseModel):
    """
    Profile of an influencer/creator for the NATIV2 AI marketing assistant. One file per talent (multi-talent roster).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: str | None = Field(
        None,
        alias="$schema",
        description="Optional reference to this schema for IDE validation.",
    )
    agency_id: UUID | None = Field(
        None,
        description="Multi-tenant scope: FK to agency_profile.agency_id. Optional in v0.1 (single-tenant deploys may omit); required in v2 SaaS. When present, all cross-record queries MUST filter by agency_id to prevent cross-tenant data leakage. See docs/data_lineage.md GAP-01/02 for rationale.",
    )
    id: str = Field(
        ...,
        description="Stable kebab-case slug, e.g. 'jane-doe'. Used as the primary key across phases. UNIQUENESS SCOPE: v0.1 globally unique (single tenant); v2 agency-scoped via composite UNIQUE `(agency_id, talent.id)` constraint — two agencies may both have `riley-carter`. See docs/id_conventions.md § 4 + GAP-N3.",
        pattern="^[a-z0-9][a-z0-9-]*$",
    )
    name: str = Field(
        ...,
        description="Public / stage name used in outreach + on the talent's media kit.",
    )
    legal_name: str | None = Field(
        None,
        description="Legal name for contracts and invoices when distinct from `name`. v0.1 captured at onboarding so Phase 4.7 contract pack doesn't need to ask later.",
    )
    pronouns: str | None = None
    gender_identity: str | None = Field(
        None,
        description="Free-form gender identity (the talent's preferred descriptor). Suggested presets: female, male, non-binary, prefer-not-to-say, or a self-describe value. Used by Phase 2 brand discovery to filter for campaigns with gender-targeted briefs.",
    )
    age: int | None = Field(None, ge=13, le=120)
    date_of_birth: date_aliased | None = None
    career_start_year: int | None = Field(
        None,
        description='Year the talent started creating professionally. Powers credibility-signal copy in Phase 4.5 discovery prep packs ("creating since 2018").',
        ge=1950,
        le=2099,
    )
    professional_roles: list[ProfessionalRole] | None = Field(
        None,
        description='Other professional hats the talent wears beyond "content creator". Boosts Phase 2 brand-discovery scoring for category-adjacent campaigns (e.g. fitness brands love athlete-creators).',
    )
    content_pillars: list[str] | None = Field(
        None,
        description='Signature content formats the talent is known for, beyond the broader `content_niches`. e.g. "morning routines", "GRWM", "behind-the-scenes", "long-form interviews". Free-form strings, captured during onboarding.',
    )
    location: Location | None = None
    timezone: str | None = Field(
        None, description="IANA timezone, e.g. 'Europe/London'."
    )
    languages: list[str] | None = None
    bio: str | None = Field(None, description="Short pitch — 1–3 sentences.")
    content_niches: list[NicheId] | None = Field(
        None,
        description="Primary content categories. Each value MUST be an `id` from `data/niches.json` (kebab-case slug, e.g. 'fitness', 'skincare', 'pc-gaming').",
    )
    contact: Contact | None = None
    billing_entity: BillingEntity | None = Field(
        None,
        description="Legal/tax info needed to invoice brands. Used as the FROM party on every Phase 4.8 invoice generated for deals involving this talent. Distinguished from `agency_profile.billing_entity` which is the agency's own legal entity (used for outreach signature CAN-SPAM compliance, not invoicing). Whether the agency invoices on the talent's behalf or the talent invoices directly is governed by the `commission_split` model on `agency_profile.default_commission_model` + per-talent overrides via `talent.commission_override`.",
    )
    commission_override: CommissionOverride | None = Field(
        None,
        description="Per-talent override of agency-default commission terms. When absent, deals for this talent use `agency_profile.default_commission_rate` + `default_commission_model`. When present, these values take precedence. Captured in Phase 1 onboarding Step 5 (typically) or 7.5.",
    )
    invoice_payment_override: InvoicePaymentOverride | None = Field(
        None,
        description="Per-talent override of agency-wide invoice payment instructions. When the talent's deals route payment to a different account than the agency's default, capture here. Renders into the `payment_instructions` block of invoices for this talent's deals (replaces `agency_profile.invoice_template.payment_instructions_markdown` for those invoices). Captured in Phase 1 onboarding Step 5.",
    )
    platforms: list[PlatformAccount] = Field(
        ...,
        description="One entry per social platform the talent is active on.",
        min_length=1,
    )
    audience_demographics: AudienceDemographics | None = Field(
        None,
        description="Aggregate audience demographics across all platforms. Per-platform overrides live on each platform entry.",
    )
    previous_brands: list[BrandDeal] | None = Field(
        None, description="Brands the talent has worked with previously."
    )
    similar_talent: list[SimilarTalent] | None = Field(
        None,
        description="Other creators in the same competitive set — used for positioning and brand discovery.",
    )
    rate_card: dict[str, RateCard] | None = Field(
        None, description="Price per deliverable, keyed by platform → deliverable type."
    )
    brand_preferences: BrandPreferences | None = None
    working_terms: WorkingTerms | None = None
    contract_template: ContractTemplate | None = Field(
        None,
        description="Per-talent contract template used by the Phase 4.7 contract pack generator (`docs/contract_pack_workflow.md`). Captured during Phase 1 talent onboarding. Markdown source with `{{merge_field}}` placeholders, `{{#if condition}}...{{/if}}` conditional sections, and `{{narrative_*}}` LLM-drafted blocks. Party identification (legal entity name, country, tax ID, address) is pulled from `talent.billing_entity` — single source of truth. Working defaults (usage rights, turnaround, revisions) are pulled from `talent.working_terms`. Agencies can ship starter templates in `data/contract_template_starters/` that the onboarding flow copies into this field for editing.",
    )
    press_kit: PressKit | None = None
    disclosure_defaults: DisclosureDefaults | None = None
    other_stats: dict[str, Any] | None = Field(
        None,
        description="Free-form key/value bag for anything that doesn't fit (newsletter subs, Discord size, podcast downloads, etc.).",
    )
